(function() {
var _UDS_CONST_LOCALE = 'zh-CN';
var _UDS_CONST_SHORT_DATE_PATTERN = 'YMD'; 
var _UDS_MSG_SEARCHER_IMAGE = ('\u56fe\u7247'); 
var _UDS_MSG_SEARCHER_WEB = ('\u7f51\u7edc'); 
var _UDS_MSG_SEARCHER_BLOG = ('\u535a\u5ba2'); 
var _UDS_MSG_SEARCHER_VIDEO = ('\u89c6\u9891'); 
var _UDS_MSG_SEARCHER_LOCAL = ('\u672c\u5730\u641c\u7d22'); 
var _UDS_MSG_SEARCHCONTROL_SAVE = ('\u4fdd\u5b58'); 
var _UDS_MSG_SEARCHCONTROL_KEEP = ('\u4fdd\u5b58'); 
var _UDS_MSG_SEARCHCONTROL_INCLUDE = ('\u5305\u542b'); 
var _UDS_MSG_SEARCHCONTROL_COPY = ('\u590d\u5236'); 
var _UDS_MSG_SEARCHCONTROL_CLOSE = ('\u5173\u95ed'); 
var _UDS_MSG_SEARCHCONTROL_SPONSORED_LINKS = ('\u8d5e\u52a9\u94fe\u63a5'); 
var _UDS_MSG_SEARCHCONTROL_SEE_MORE = ('\u67e5\u770b\u66f4\u591a'); 
var _UDS_MSG_SEARCHCONTROL_WATERMARK = ('\u526a\u5207\u81ea Google'); 
var _UDS_MSG_SEARCHER_CONFIG_SET_LOCATION = ('\u641c\u7d22\u4f4d\u7f6e'); 
var _UDS_MSG_SEARCHER_CONFIG_DISABLE_ADDRESS_LOOKUP = ('\u7981\u7528\u5730\u5740\u67e5\u8be2'); 
var _UDS_MSG_SEARCHER_NEWS = ('\u8d44\u8baf'); 
function _UDS_MSG_MINUTES_AGO(AGE_MINUTES_AGO) {return ('' + AGE_MINUTES_AGO + ' \u5206\u949f\u524d');} 
var _UDS_MSG_ONE_HOUR_AGO = ('1 \u5c0f\u65f6\u524d'); 
function _UDS_MSG_HOURS_AGO(AGE_HOURS_AGO) {return ('' + AGE_HOURS_AGO + ' \u5c0f\u65f6\u524d');} 
function _UDS_MSG_NEWS_ALL_N_RELATED(NUMBER) {return ('\u6240\u6709' + NUMBER + '\u6761\u76f8\u5173\u8d44\u8baf');} 
var _UDS_MSG_NEWS_RELATED = ('\u76f8\u5173\u6587\u7ae0'); 
var _UDS_MSG_BRANDING_STRING = ('\u7531 Google \u5f15\u52a8'); 
var _UDS_MSG_SORT_BY_DATE = ('\u6309\u65e5\u671f\u6392\u5e8f'); 
var _UDS_MSG_MONTH_ABBR_JAN = ('1 \u6708'); 
var _UDS_MSG_MONTH_ABBR_FEB = ('2 \u6708'); 
var _UDS_MSG_MONTH_ABBR_MAR = ('3 \u6708'); 
var _UDS_MSG_MONTH_ABBR_APR = ('4 \u6708'); 
var _UDS_MSG_MONTH_ABBR_MAY = ('5 \u6708'); 
var _UDS_MSG_MONTH_ABBR_JUN = ('6 \u6708'); 
var _UDS_MSG_MONTH_ABBR_JUL = ('7 \u6708'); 
var _UDS_MSG_MONTH_ABBR_AUG = ('8 \u6708'); 
var _UDS_MSG_MONTH_ABBR_SEP = ('9 \u6708'); 
var _UDS_MSG_MONTH_ABBR_OCT = ('10 \u6708'); 
var _UDS_MSG_MONTH_ABBR_NOV = ('11 \u6708'); 
var _UDS_MSG_MONTH_ABBR_DEC = ('12 \u6708'); 
var _UDS_MSG_DIRECTIONS = ('\u8def\u7ebf'); 
var _UDS_MSG_CLEAR_RESULTS = ('\u6e05\u9664\u7ed3\u679c'); 
var _UDS_MSG_SHOW_ONE_RESULT = ('\u663e\u793a\u4e00\u4e2a\u7ed3\u679c'); 
var _UDS_MSG_SHOW_MORE_RESULTS = ('\u663e\u793a\u66f4\u591a\u7ed3\u679c'); 
var _UDS_MSG_SHOW_ALL_RESULTS = ('\u663e\u793a\u6240\u6709\u7ed3\u679c'); 
var _UDS_MSG_SETTINGS = ('\u8bbe\u7f6e'); 
var _UDS_MSG_SEARCH = ('\u641c\u7d22'); 
var _UDS_MSG_SEARCH_UC = ('\u641c\u7d22'); 
var _UDS_MSG_POWERED_BY = ('powered by'); 
function _UDS_MSG_LOCAL_ATTRIBUTION(LOCAL_RESULTS_PROVIDER) {return ('\u7531 ' + LOCAL_RESULTS_PROVIDER + ' \u63d0\u4f9b\u7684\u5546\u4e1a\u5217\u8868');} 
var _UDS_MSG_SEARCHER_BOOK = ('\u4e66\u7c4d'); 
function _UDS_MSG_FOUND_ON_PAGE(FOUND_ON_PAGE) {return ('\u7b2c ' + FOUND_ON_PAGE + ' \u9875');} 
function _UDS_MSG_TOTAL_PAGE_COUNT(PAGE_COUNT) {return ('' + PAGE_COUNT + ' \u9875');} 
var _UDS_MSG_SEARCHER_BY = ('\u4f5c\u8005'); 
var _UDS_MSG_SEARCHER_CODE = ('\u4ee3\u7801'); 
var _UDS_MSG_UNKNOWN_LICENSE = ('\u8bb8\u53ef\u672a\u77e5'); 
var _UDS_MSG_SEARCHER_GSA = ('Search Appliance'); 
var _UDS_MSG_SEARCHCONTROL_MORERESULTS = ('\u66f4\u591a\u7ed3\u679c'); 
var _UDS_MSG_SEARCHCONTROL_PREVIOUS = ('\u4e0a\u4e00\u7ec4'); 
var _UDS_MSG_SEARCHCONTROL_NEXT = ('\u4e0b\u4e00\u7ec4'); 
var _UDS_MSG_GET_DIRECTIONS = ('\u83b7\u53d6\u9a7e\u8f66\u6307\u5357'); 
var _UDS_MSG_GET_DIRECTIONS_TO_HERE = ('\u524d\u5f80\u6b64\u5904'); 
var _UDS_MSG_GET_DIRECTIONS_FROM_HERE = ('\u4ece\u6b64\u5904\u51fa\u53d1'); 
var _UDS_MSG_CLEAR_RESULTS_UC = ('\u6e05\u9664\u7ed3\u679c'); 
var _UDS_MSG_SEARCH_THE_MAP = ('\u641c\u7d22\u5730\u56fe'); 
var _UDS_MSG_SCROLL_THROUGH_RESULTS = ('\u6eda\u52a8\u6d4f\u89c8\u7ed3\u679c'); 
var _UDS_MSG_EDIT_TAGS = ('\u4fee\u6539\u6807\u8bb0'); 
var _UDS_MSG_TAG_THIS_SEARCH = ('\u6807\u8bb0\u6b64\u641c\u7d22'); 
var _UDS_MSG_SEARCH_STRING = ('\u641c\u7d22\u5b57\u7b26\u4e32'); 
var _UDS_MSG_OPTIONAL_LABEL = ('\u53ef\u9009\u6807\u7b7e'); 
var _UDS_MSG_DELETE = ('\u5220\u9664'); 
var _UDS_MSG_DELETED = ('\u5df2\u5220\u9664'); 
var _UDS_MSG_CANCEL = ('\u53d6\u6d88'); 
var _UDS_MSG_UPLOAD_YOUR_VIDEOS = ('\u4e0a\u4f20\u81ea\u5df1\u7684\u89c6\u9891'); 
var _UDS_MSG_IM_DONE_WATCHING = ('\u89c2\u770b\u5b8c\u6bd5'); 
var _UDS_MSG_CLOSE_VIDEO_PLAYER = ('\u5173\u95ed\u89c6\u9891\u64ad\u653e\u5668'); 
var _UDS_MSG_NO_RESULTS = ('\u65e0\u7ed3\u679c'); 
var _UDS_MSG_LINKEDCSE_ERROR_RESULTS = ('\u6b64\u81ea\u5b9a\u4e49\u641c\u7d22\u5f15\u64ce\u6b63\u5728\u52a0\u8f7d\u3002\u8bf7\u5728\u6570\u79d2\u540e\u518d\u6b21\u5c1d\u8bd5\u3002'); 
var _UDS_MSG_COUPONS = ('\u4f18\u60e0\u5238'); 
var _UDS_MSG_BACK = ('\u8fd4\u56de'); 
var _UDS_MSG_SUBSCRIBE = ('\u8ba2\u9605'); 
var _UDS_MSG_SEARCHER_PATENT = ('\u4e13\u5229'); 
var _UDS_MSG_USPAT = ('\u7f8e\u56fd\u4e13\u5229'); 
var _UDS_MSG_USPAT_APP = ('\u7f8e\u56fd\u4e13\u5229\u7533\u8bf7\u7f16\u53f7'); 
var _UDS_MSG_PATENT_FILED = ('\u7533\u8bf7\u65e5\u671f'); 
var _UDS_MSG_ADS_BY_GOOGLE = ('Google \u63d0\u4f9b\u7684\u5e7f\u544a'); 
var _UDS_MSG_SET_DEFAULT_LOCATION = ('\u8bbe\u7f6e\u9ed8\u8ba4\u4f4d\u7f6e'); 
var _UDS_MSG_NEWSCAT_TOPSTORIES = ('\u7126\u70b9'); 
var _UDS_MSG_NEWSCAT_WORLD = ('\u56fd\u9645/\u6e2f\u53f0'); 
var _UDS_MSG_NEWSCAT_NATION = ('\u56fd\u5185'); 
var _UDS_MSG_NEWSCAT_BUSINESS = ('\u8d22\u7ecf'); 
var _UDS_MSG_NEWSCAT_SCITECH = ('\u79d1\u6280'); 
var _UDS_MSG_NEWSCAT_ENTERTAINMENT = ('\u5a31\u4e50'); 
var _UDS_MSG_NEWSCAT_HEALTH = ('\u5065\u5eb7'); 
var _UDS_MSG_NEWSCAT_SPORTS = ('\u4f53\u80b2'); 
var _UDS_MSG_NEWSCAT_POLITICS = ('\u653f\u6cbb');
var a=true,b=null,g=false,i=encodeURIComponent,j=google_exportSymbol,aa=_UDS_CONST_SHORT_DATE_PATTERN,l=window,p=google,ba=navigator,ca=undefined,da=parseInt,ga=parseFloat,ha=_UDS_CONST_LOCALE,q=document,r=Math;function ia(c,d){return c.onload=d}function ja(c,d){return c.onreadystatechange=d}function t(c,d){return c.title=d}function u(c,d){return c.className=d}function ka(c,d){return c.input=d}function la(c,d){return c.width=d}function ma(c,d){return c.checked=d}
function v(c,d){return c.innerHTML=d}function na(c,d){return c.value=d}function oa(c,d){return c.type=d}function pa(c,d){return c.onclick=d}function qa(c,d){return c.display=d}function ra(c,d){return c.execute=d}function sa(c,d){return c.height=d}function ta(c,d){return c.visibility=d}
var w="appendChild",ua="push",z="length",va="title",A="prototype",C="cursor",ya="className",za="clearTimeout",D="input",E="width",Aa="Version",Ba="round",Ca="checked",Da="setTimeout",F="replace",Ea="split",Fa="floor",Ga="content",Ha="userAgent",Ia="value",Ja="location",Ka="indexOf",La="getComputedStyle",G="style",Oa="close",H="search",Pa="call",Qa="match",Ra="readyState",Sa="focus",J="createElement",Ta="setAttribute",K="loader",Ua="currentStyle",Va="cloneNode",Wa="type",Ya="apply",Za="recordStat",
$a="ServiceBase",ab="CurrentLocale",L="execute",bb="height",cb="getTime",db="toLowerCase",M;if(!p[H].NoOldNames){j("UDS_ServiceBase",p[K][$a]);j("UDS_OriginalAppPath",p[K].OriginalAppPath);j("UDS_ApiKey",p[K].ApiKey);j("UDS_KeyVerified",p[K].KeyVerified);j("UDS_LoadFailure",p[K].LoadFailure);j("UDS_CurrentLocale",ha);j("UDS_ShortDatePattern",aa);j("UDS_Version",p[H][Aa]);j("UDS_JSHash",p[H].JSHash)}if(!N)var N=j;if(!O)var O=google_exportProperty;var P={};P.blank="&nbsp;";P.image=_UDS_MSG_SEARCHER_IMAGE;P.web=_UDS_MSG_SEARCHER_WEB;P.blog=_UDS_MSG_SEARCHER_BLOG;P.video=_UDS_MSG_SEARCHER_VIDEO;P.local=_UDS_MSG_SEARCHER_LOCAL;P.news=_UDS_MSG_SEARCHER_NEWS;P.book=_UDS_MSG_SEARCHER_BOOK;P.patent="Patent";P["ads-by-google"]=_UDS_MSG_ADS_BY_GOOGLE;P.cse="Custom Search Control";P.save=_UDS_MSG_SEARCHCONTROL_SAVE;P.keep=_UDS_MSG_SEARCHCONTROL_KEEP;P.include=_UDS_MSG_SEARCHCONTROL_INCLUDE;P.copy=_UDS_MSG_SEARCHCONTROL_COPY;P.close=_UDS_MSG_SEARCHCONTROL_CLOSE;
P["sponsored-links"]=_UDS_MSG_SEARCHCONTROL_SPONSORED_LINKS;P["see-more"]=_UDS_MSG_SEARCHCONTROL_SEE_MORE;P.watermark=_UDS_MSG_SEARCHCONTROL_WATERMARK;P["search-location"]=_UDS_MSG_SEARCHER_CONFIG_SET_LOCATION;P["disable-address-lookup"]=_UDS_MSG_SEARCHER_CONFIG_DISABLE_ADDRESS_LOOKUP;P["sort-by-date"]=_UDS_MSG_SORT_BY_DATE;P.pbg=_UDS_MSG_BRANDING_STRING;P["n-minutes-ago"]=_UDS_MSG_MINUTES_AGO;P["n-hours-ago"]=_UDS_MSG_HOURS_AGO;P["one-hour-ago"]=_UDS_MSG_ONE_HOUR_AGO;P["all-n-related"]=_UDS_MSG_NEWS_ALL_N_RELATED;
P["related-articles"]=_UDS_MSG_NEWS_RELATED;P["page-count"]=_UDS_MSG_TOTAL_PAGE_COUNT;var Q=[];Q[0]=_UDS_MSG_MONTH_ABBR_JAN;Q[1]=_UDS_MSG_MONTH_ABBR_FEB;Q[2]=_UDS_MSG_MONTH_ABBR_MAR;Q[3]=_UDS_MSG_MONTH_ABBR_APR;Q[4]=_UDS_MSG_MONTH_ABBR_MAY;Q[5]=_UDS_MSG_MONTH_ABBR_JUN;Q[6]=_UDS_MSG_MONTH_ABBR_JUL;Q[7]=_UDS_MSG_MONTH_ABBR_AUG;Q[8]=_UDS_MSG_MONTH_ABBR_SEP;Q[9]=_UDS_MSG_MONTH_ABBR_OCT;Q[10]=_UDS_MSG_MONTH_ABBR_NOV;Q[11]=_UDS_MSG_MONTH_ABBR_DEC;P["month-abbr"]=Q;P.directions=_UDS_MSG_DIRECTIONS;
P["clear-results"]=_UDS_MSG_CLEAR_RESULTS;P["show-one-result"]=_UDS_MSG_SHOW_ONE_RESULT;P["show-more-results"]=_UDS_MSG_SHOW_MORE_RESULTS;P["show-all-results"]=_UDS_MSG_SHOW_ALL_RESULTS;P.settings=_UDS_MSG_SETTINGS;P.search=_UDS_MSG_SEARCH;P["search-uc"]=_UDS_MSG_SEARCH_UC;P["powered-by"]=_UDS_MSG_POWERED_BY;P.sa=_UDS_MSG_SEARCHER_GSA;P.by=_UDS_MSG_SEARCHER_BY;P.code=_UDS_MSG_SEARCHER_CODE;P["unknown-license"]=_UDS_MSG_UNKNOWN_LICENSE;P["more-results"]=_UDS_MSG_SEARCHCONTROL_MORERESULTS;
P.previous=_UDS_MSG_SEARCHCONTROL_PREVIOUS;P.next=_UDS_MSG_SEARCHCONTROL_NEXT;P["get-directions"]=_UDS_MSG_GET_DIRECTIONS;P["to-here"]=_UDS_MSG_GET_DIRECTIONS_TO_HERE;P["from-here"]=_UDS_MSG_GET_DIRECTIONS_FROM_HERE;P["clear-results-uc"]=_UDS_MSG_CLEAR_RESULTS_UC;P["search-the-map"]=_UDS_MSG_SEARCH_THE_MAP;P["scroll-results"]=_UDS_MSG_SCROLL_THROUGH_RESULTS;P["edit-tags"]=_UDS_MSG_EDIT_TAGS;P["tag-search"]=_UDS_MSG_TAG_THIS_SEARCH;P["search-string"]=_UDS_MSG_SEARCH_STRING;P["optional-label"]=_UDS_MSG_OPTIONAL_LABEL;
P["delete"]=_UDS_MSG_DELETE;P.deleted=_UDS_MSG_DELETED;P.cancel=_UDS_MSG_CANCEL;P["upload-video"]=_UDS_MSG_UPLOAD_YOUR_VIDEOS;P["im-done"]=_UDS_MSG_IM_DONE_WATCHING;P["close-player"]=_UDS_MSG_CLOSE_VIDEO_PLAYER;P["no-results"]=_UDS_MSG_NO_RESULTS;P["linked-cse-error-results"]=_UDS_MSG_LINKEDCSE_ERROR_RESULTS;P.back=_UDS_MSG_BACK;P.subscribe=_UDS_MSG_SUBSCRIBE;P["us-pat"]="US Pat.";P["us-pat-app"]="US Pat. App";P["us-pat-filed"]="Filed";function eb(c,d){var e=function(){};e.prototype=d[A];c.prototype=new e;c[A].jg=function(f){var h=Array[A].splice[Ya](arguments,[1,arguments[z]]);return f[Ya](c,h)}}var _json_cache_defeater_=(new Date)[cb](),_json_request_require_prep=a;function fb(c,d){if(gb("msie")&&hb("msie 6.0")){var e=R(this,ib,[c,d]);l[Da](e,0)}else ib(c,d)}
function ib(c,d){var e=q.getElementsByTagName("head")[0];e||(e=q.body.parentNode[w](q[J]("head")));var f=q[J]("script");oa(f,"text/javascript");f.charset="utf-8";var h=_json_request_require_prep?c+"&key="+p[K].ApiKey+"&v="+d:c;if(jb()||kb())h=h+"&nocache="+_json_cache_defeater_++;f.src=h;var k=function(){ia(f,b);f.parentNode.removeChild(f);delete f},n=function(m){var o,s=m?m:l.event;o=s.target?s.target:s.srcElement;if(o[Ra]=="loaded"||o[Ra]=="complete"){ja(o,b);k()}};if(ba.product=="Gecko")ia(f,k);
else ja(f,n);e[w](f)}function lb(c,d){return function(){return d[Ya](c,arguments)}}function R(c,d,e){return function(){return d[Ya](c,e)}}function mb(c){for(;c.firstChild;)c.removeChild(c.firstChild)}function S(c,d){try{c[w](d)}catch(e){}return d}function U(c,d){var e=q[J]("div");if(c)v(e,c);if(d)u(e,d);return e}function V(c){var d=q[J]("div");if(c)u(d,c);return d}function nb(c,d){var e=q[J]("span");c&&S(e,q.createTextNode(c?c:""));if(d)u(e,d);return e}
function ob(c,d,e){var f=q[J]("table");f[Ta]("cellSpacing",c?c:0);f[Ta]("cellPadding",d?d:0);if(e)u(f,e);return f}function pb(c,d,e){var f=c.insertRow(-1);f||alert(f);for(var h=0;h<d;h++)W(f,e);return f}function W(c,d){var e=c.insertCell(-1);if(d)u(e,d);return e}function qb(c){var d=q[J]("td");if(c)u(d,c);return d}function rb(c,d,e,f){var h=q[J]("img");h.src=c;if(d)la(h,d);if(e)sa(h,e);if(f)u(h,f);return h}
function tb(c,d,e,f,h){var k=q[J]("a");k.href=c;if(d)f?S(k,nb(d,f)):S(k,q.createTextNode(d?d:""));if(e)k.target=e;if(h)t(k,h);return k}function X(c,d,e,f,h){var k=U(b,f),n=q[J]("a");n.href=c;v(n,d);if(f)u(n,f);if(e)n.target=e;if(h)t(n,h);k[w](n);return k}function vb(c){var d=q[J]("form");if(c)u(d,c);return d}function wb(c,d){var e=q[J]("input");oa(e,"submit");na(e,c);if(d)u(e,d);return e}
function xb(c,d,e){var f=q[J]("input");f[Ta]("autoComplete","off");oa(f,"text");if(c==-1)Y(f,"util-css-expand");else f.size=c>0?c:10;d&&yb(f,d);if(e)na(f,e);return f}function zb(c,d,e,f){var h=q[J]("input");oa(h,"checkbox");h.name=c;na(h,d);if(f)u(h,f);if(e)ma(h,e);return h}function Ab(c,d){u(c,d)}function yb(c,d){Y(c,d)}function Bb(c,d){$(c,d)}function Y(c,d){var e;a:if(c==b||c[ya]==b)e=g;else{for(var f=c[ya][Ea](" "),h=0;h<f[z];h++)if(f[h]==d){e=a;break a}e=g}e||(c.className+=" "+d)}
function $(c,d){if(!(c[ya]==b)){for(var e=c[ya][Ea](" "),f=[],h=g,k=0;k<e[z];k++)if(e[k]!=d)e[k]&&f[ua](e[k]);else h=a;if(h)u(c,f.join(" "))}}function Cb(c){if(Db!="")return Db;var d=c[db]()[Ea](".");if(d[z]<2)Db=".com";var e=d.pop(),f=d.pop();return Db=e[z]==2?Eb[f]&&Eb[f][e]==1?"."+f+"."+e:"."+e:".com"}
var Db="",Eb={Ye:{tg:1,xg:1,Fg:1,id:1,Gg:1,"in":1,Ig:1,Kg:1,Lg:1,Mg:1,Pg:1,Yg:1,mh:1,qh:1,rh:1,vh:1,wh:1,zh:1},ug:{kg:1,ng:1,pg:1,qg:1,rg:1,sg:1,Ye:1,yg:1,"do":1,zg:1,Ag:1,Bg:1,Cg:1,Dg:1,Eg:1,Jg:1,Qg:1,Rg:1,Sg:1,Tg:1,Ug:1,Vg:1,Wg:1,Xg:1,$g:1,ah:1,bh:1,dh:1,eh:1,fh:1,hh:1,jh:1,lh:1,nh:1,oh:1,ph:1,th:1,uh:1,yh:1},Zg:{lg:1}};function gb(c){if(c in Fb)return Fb[c];return Fb[c]=ba[Ha][db]()[Ka](c)!=-1}function hb(c){if(c in Gb)return Gb[c];return Gb[c]=ba.appVersion[db]()[Ka](c)!=-1}var Fb={},Gb={};
function jb(){return gb("msie")}function kb(){return gb("safari")||gb("konqueror")}var Hb,Ib,Jb,Kb,Lb,Mb,Nb;if(l.ig){Hb=a;if(l.XMLHttpRequest)Ib=a;else Jb=a}else if(l.opera)Kb=a;else if(q.childNodes&&!q.all&&!ba.taintEnabled){Lb=a;if(ba[Ha][Ka]("iPhone")>0)Mb=a}else if(q.getBoxObjectFor!=b)Nb=a;
function Ob(c){this.ac=c+"branding";this.Pb=c+"branding-vertical";this.Hg=c+"branding-img";this.sh=c+"branding-user-defined";this.ee=c+"branding-img-noclear";this.Xe=c+"branding-clickable";this.text=c+"branding-text"};p[H].a=function(){this.da=this.vg=b;this.Cc=this.fg=0;this.ae=a;this.M={width:100,height:75};this.Ea=p[H].a.ab;this.ie=1;this.pa(p[H].a.ba);this.Rd();this.gwsUrl=this.v=this.G=this.ih=this.z=this.Gb=this.wb=this.Za=this.rc=this.Mb=this.gc=this.ec=b;this.oa=[];this.ce=typeof l==="object"&&l[Ja]&&l[Ja].hostname&&l[Ja].hostname!=""?Cb(l[Ja].hostname):".com";this.mb=this.gb=b};N("google.search.Search",p[H].a);p[H].a.Gc=p[K][$a];O(p[H].a,"BASE",p[H].a.Gc);p[H].a.ta="large";O(p[H].a,"LARGE_RESULTSET",p[H].a.ta);
p[H].a.ba="small";O(p[H].a,"SMALL_RESULTSET",p[H].a.ba);p[H].a.De=8;O(p[H].a,"LARGE_RESULTS",p[H].a.De);p[H].a.Ne=4;O(p[H].a,"SMALL_RESULTS",p[H].a.Ne);p[H].a.ld=5000;O(p[H].a,"KEEP_SWEEPER_DELAY",p[H].a.ld);p[H].a.Ge="_top";O(p[H].a,"LINK_TARGET_TOP",p[H].a.Ge);p[H].a.Fe="_self";O(p[H].a,"LINK_TARGET_SELF",p[H].a.Fe);p[H].a.Ee="_parent";O(p[H].a,"LINK_TARGET_PARENT",p[H].a.Ee);p[H].a.ab="_blank";O(p[H].a,"LINK_TARGET_BLANK",p[H].a.ab);p[H].a.la="order-by-relevance";
O(p[H].a,"ORDER_BY_RELEVANCE",p[H].a.la);p[H].a.ka="order-by-date";O(p[H].a,"ORDER_BY_DATE",p[H].a.ka);p[H].a.nd="order-by-ascending-date";O(p[H].a,"ORDER_BY_ASCENDING_DATE",p[H].a.nd);p[H].a.xb="restrict-type";O(p[H].a,"RESTRICT_TYPE",p[H].a.xb);p[H].a.Sb="restrict-safesearch";O(p[H].a,"RESTRICT_SAFESEARCH",p[H].a.Sb);p[H].a.Vb="active";O(p[H].a,"SAFESEARCH_STRICT",p[H].a.Vb);p[H].a.Ub="off";O(p[H].a,"SAFESEARCH_OFF",p[H].a.Ub);p[H].a.Tb="moderate";O(p[H].a,"SAFESEARCH_MODERATE",p[H].a.Tb);
p[H].a.Rb="restrict-extended";O(p[H].a,"RESTRICT_EXTENDED_ARGS",p[H].a.Rb);p[H].a.ag=P;O(p[H].a,"strings",p[H].a.ag);p[H].a[A].Gf=function(){var c=this.ma+"?hl="+p[H][ab]+"&source=uds";c=this.v?c+this.v:c+"&q=";return this.wa&&this.wa!=""?this.wa:c};p[H].a[A].Tf=function(c){this.G=c==b||c==""?b:c};O(p[H].a[A],"setQueryAddition",p[H].a[A].Tf);
p[H].a[A].ya=function(c,d,e){var f=p[H].a.Gc+this.Aa+"?callback="+c+"&context="+d+"&lstkp="+this.We()+"&rsz="+this.Wa+"&hl="+p[H][ab];if(this.rb)f+="&source="+i(this.rb);if(this.ce)f+="&gss="+this.ce;if(p[H].JSHash)f+="&sig="+p[H].JSHash;if(e)f+="&start="+e;return f};p[H].a[A].Xf=function(c){this.rb=c};O(p[H].a[A],"setSearcherSrc",p[H].a[A].Xf);p[H].a[A].sb=function(c){this.Ea=c};O(p[H].a[A],"setLinkTarget",p[H].a[A].sb);M=p[H].a[A];M.t=function(){return this.Ea&&this.Ea!=""?this.Ea:b};
M.rf=function(){this.fg++;this.Cc++;this.Gb&&l[za](this.Gb);this.Gb=l[Da](R(this,this[L],[b]),p[H].a.ld)};M.We=function(){l[za](this.Gb);var c=this.Cc;this.Cc=0;return c};M.lc=function(){if(this.ec==b)this.ec="gsc-"+this.z+"Result";return this.ec};M.ha=function(){if(this.gc==b)this.gc="gs-"+this.z+"Result";return this.gc};M.of=function(){if(this.Mb==b)this.Mb=P[this.z];return this.Za?this.Za:this.Mb};M.mf=function(){if(this.rc==b)this.rc=P[this.z];return this.Za?this.Za:this.rc};M.nf=function(){return this.Wa};
O(p[H].a[A],"getResultSetSize",p[H].a[A].nf);p[H].a[A].pa=function(c){switch(c){case p[H].a.ta:this.Wa=p[H].a.ta;break;default:case p[H].a.ba:this.Wa=p[H].a.ba;break}};O(p[H].a[A],"setResultSetSize",p[H].a[A].pa);ra(p[H].a[A],function(c){var d=(new Date)[cb]();this.Bc=d%100==1?d:-1;var e=this.ga(c,b,b);if(l._googleudsextrastuff)e=e+l._googleudsextrastuff;this.cursor=b;this.vf=c;fb(e,p[H][Aa]);if(this.oa&&this.oa[z]>0)for(var f=0;f<this.oa[z];f++)this.oa[f][L](c)});O(p[H].a[A],"execute",p[H].a[A][L]);
p[H].a[A].de=function(c){if(this[C]&&c<this[C].pages[z]){var d=this.ga(this.vf,b,b,this[C].pages[c].start);this.cursor=b;fb(d,p[H][Aa])}};O(p[H].a[A],"gotoPage",p[H].a[A].de);p[H].a[A].Pe=function(c){this.oa&&this.oa[ua](c)};O(p[H].a[A],"addRelatedSearcher",p[H].a[A].Pe);p[H].a[A].lf=function(c,d,e){return this.ga(c,d,e)+"&key="+p[K].ApiKey+"&v="+p[H][Aa]};O(p[H].a[A],"getExecuteUrl",p[H].a[A].lf);
p[H].a[A].ua=function(c){var d=P.watermark+" - "+this.Ze(),e=X("http://code.google.com/apis/ajaxsearch/faq.html",d,"_blank","gs-watermark");S(c,e)};p[H].a[A].Ze=function(){var c=new Date;return c.getMonth()+1+"/"+c.getFullYear()};
p[H].a[A].Ta=function(c){var d,e=c.getFullYear(),f=c.getMonth(),h=P["month-abbr"][f],k=c.getDate();if(k<10)k="0"+k;switch(p[H].ShortDatePattern){case "MDY":d=h+" "+k+", "+e;break;case "YMD":if(p[H][ab]=="zh-CN"||p[H][ab]=="zh-TW"||p[H][ab]=="ja"||p[H][ab]=="ko"){var n=Pb[p[H][ab]];d=e+n.year+(f+1)+n.month+k+n.day}else d=e+" "+h+" "+k;break;default:case "DMY":d=k+" "+h+" "+e;break}return d};O(p[H].a[A],"formatToShortDate",p[H].a[A].Ta);
var Pb={"zh-CN":{month:" \u6708 ",year:" \u5e74 ",day:" \u65e5 "},"zh-TW":{month:" \u6708 ",year:" \u5e74 ",day:" \u65e5 "},ja:{month:"\u6708",year:"\u5e74",day:"\u65e5"},ko:{month:" \uc6d4 ",year:" \ub144 ",day:" \uc77c "}};p[H].a.md=3600000;p[H].a.Le=60000;p[H].a.Ke=86400000;
p[H].a[A].kc=function(c){var d=(new Date)[cb](),e=c[cb](),f;if(d<e)return P["n-minutes-ago"](2);var h=d-e;if(h<p[H].a.md){var k=r[Fa](h/p[H].a.Le);f=k<=1?2:k;return P["n-minutes-ago"](f)}if(h<p[H].a.Ke){var n=r[Fa](h/p[H].a.md);if(n<=1)return P["one-hour-ago"];else{f=n;return P["n-hours-ago"](f)}}return this.Ta(c)};O(p[H].a[A],"formatToRelativeDate",p[H].a[A].kc);p[H].a[A].Rd=function(){this.gh=this.gwsUrl=b;this.results=[]};O(p[H].a[A],"clearResults",p[H].a[A].Rd);
p[H].a[A].ff=function(){this.Sd&&this.Sd();if(this.Bc!=-1){p[K][Za]("asa_"+this.z,"req."+((new Date)[cb]()-this.Bc),a);this.Bc=-1}};
p[H].a[A].U=function(c,d,e,f){if(!(c==b&&d==204)){this.gwsUrl=b;if(this.results&&this.results[z]>0)for(var h=0;h<this.results[z];h++)this.results[h].html&&Qb(this.results[h].html);if(c&&c.results&&c.results[z]>0){this.results=c.results;if(c[C]&&c[C].moreResultsUrl)this.gwsUrl=this.wa&&this.wa!=""?this.wa:c[C].moreResultsUrl;else if(this.v&&this.ma)this.gwsUrl=this.Gf()}else this.results=[];this.completionStatus=d;this.hashStatus=f;this.wg=e;this.le=c&&c.resultAttribution&&c.resultAttribution!=b&&
c.resultAttribution!=""?c.resultAttribution:b;if(c&&c[C]&&c[C].pages&&c[C].pages[z]>0)this.cursor=c[C];else typeof this[C]!="undefined"&&delete this[C];if(c&&c.context)this.context=c.context;else typeof this.context!="undefined"&&delete this.context;if(c&&c.promotions)this.promotions=c.promotions;else typeof this.promotions!="undefined"&&delete this.promotions;if(c&&c.omittedResults)this.omittedResults=c.omittedResults;else typeof this.omittedResults!="undefined"&&delete this.omittedResults;this.ae&&
this.Se();this.ff()}};O(p[H].a[A],"onSearchComplete",p[H].a[A].U);p[H].a[A].be=function(){var c=b;if(this.le)c=U(this.le,"gs-results-attribution");return c};O(p[H].a[A],"getAttribution",p[H].a[A].be);p[H].a[A].Se=function(){var c,d;for(c=0;c<this.results[z];c++){d=this.results[c];this.D(d)}};p[H].a[A].tb=function(c,d,e){e||(e=[b]);this.Sd=R(c,d,e)};O(p[H].a[A],"setSearchCompleteCallback",p[H].a[A].tb);
p[H].a.ia=function(c,d){var e=g,f;if(c[z])for(var h=0;h<c[z];h++)if(c[h]==b){c[h]=d;f=h;e=a;break}if(!e){f=c[z];c[ua](d)}return f};O(p[H].a,"AllocateCompletionMapContext",p[H].a.ia);p[H].a[A].vb=function(c){this.Za=c};O(p[H].a[A],"setUserDefinedLabel",p[H].a[A].vb);p[H].a[A].Zf=function(c){this.wb=c};O(p[H].a[A],"setUserDefinedClassSuffix",p[H].a[A].Zf);p[H].a[A].Rf=function(){this.ae=g};O(p[H].a[A],"setNoHtmlGeneration",p[H].a[A].Rf);
p[H].a.Xa=function(c,d,e,f,h){var k=r.min(e[E]/c,e[bb]/d),n=r.min(k,1),m={};la(m,r[Ba](c*n));sa(m,r[Ba](d*n));if(f){la(f,m[E]);sa(f,m[bb]);if(h)f[G].left=(e[E]-m[E])/2+"px"}return m};O(p[H].a,"scaleImage",p[H].a.Xa);p[H].a.Ld=1;O(p[H].a,"VERTICAL_BRANDING",p[H].a.Ld);p[H].a.ye=2;O(p[H].a,"HORIZONTAL_BRANDING",p[H].a.ye);
p[H].a.jf=function(c,d,e){var f,h=new Ob("gsc-"),k=V(h.ac),n=ob(b,b,h.ac);S(k,n);var m=!(d&&d==p[H].a.Ld);if(!m){Y(k,h.Pb);Y(n,h.Pb)}var o=pb(n,0),s,x;if(m)x=s=o;else{s=o;x=pb(n,0)}var y="/css/small-logo.png",I=51,B=15;if(e)if(typeof e=="string")if(e[Qa](/^http:\/\/www\.youtube\.com/)){y="/css/youtube-logo-55x24.png";I=55;B=24;Y(k,h.ac+"-youtube");if(!m){Y(k,h.Pb+"-youtube");Y(n,h.Pb+"-youtube")}}var T=W(s,h.text),Z=W(x,h.ee),Xa=U(P["powered-by"],h.text),ea,wa=p[K][$a]+y,fa=h.ee,xa;if(Hb&&!Ib){xa=
V(fa);xa[G].filter='progid:DXImageTransform.Microsoft.AlphaImageLoader(src="'+wa+'")';la(xa[G],I+"px");sa(xa[G],B+"px")}else xa=rb(wa,b,b,fa);ea=xa;S(T,Xa);if(e){var sb="http://www.google.com";if(typeof e=="string"&&(e[Qa](/^http:\/\/[a-z]*\.google\.com/)||e[Qa](/^http:\/\/www\.youtube\.com/)))sb=e;var Ma=tb(sb,b,"_BLANK");u(Ma,h.Xe);S(Ma,ea);S(Z,Ma)}else S(Z,ea);if(c){var Na;Na=typeof c=="string"?q.getElementById(c):c;mb(Na);S(Na,k)}return f=k};O(p[H].a,"getBranding",p[H].a.jf);
p[H].a.setOnLoadCallback=function(c,d){p.setOnLoadCallback(c,d)};O(p[H].a,"setOnLoadCallback",p[H].a.setOnLoadCallback);var Rb;function Qb(c){Rb||(Rb=q[J]("DIV"));Rb[w](c);v(Rb,"")}p[H].a[A].gf=function(c){var d=this.gb;if(c)d=c;var e={},f=V(this.ha());Y(f,"gs-result");Y(f,"gs-error-result");var h;h=U(d,"gs-snippet");S(f,h);e.html=f;return e};
p[H].a[A].hf=function(c){var d=this.mb;if(c)d=c;var e={},f=V(this.ha());Y(f,"gs-result");Y(f,"gs-no-results-result");var h;h=U(d,"gs-snippet");S(f,h);e.html=f;return e};j("google.search.CurrentLocale",ha);j("google.search.ShortDatePattern",aa);p[H].r=function(){p[H].a[Pa](this);this.z="blog";this.Aa="/GblogSearch";this.ma="http://blogsearch.google.com/blogsearch";this.m=b;this.N=g;this.Ra=a;this.da=lb(this,p[H].r[A].na);this.Qa="gsc-blogConfig";this.k=b};N("google.search.BlogSearch",p[H].r);eb(p[H].r,p[H].a);p[H].r.C="GblogSearch";O(p[H].r,"RESULT_CLASS",p[H].r.C);p[H].r.o=[];p[H].r.H=function(c,d,e,f,h){var k=0;if(c)k=da(c,10);var n=p[H].r.o[k];p[H].r.o[k]=b;n.U(d,e,f,h)};O(p[H].r,"RawCompletion",p[H].r.H);
p[H].r[A].ga=function(c,d,e,f){var h;h=e==b?p[H].a.ia(p[H].r.o,this):e;var k;k=d==b?"google.search.BlogSearch.RawCompletion":d;var n=this.ya(k,h,f);if(c){var m,o=c;if(this.G)o=o+" "+this.G;if(this.m)o=o+" blogurl:"+this.m;m="&q="+i(o);if(this.N)m=m+"&scoring=d";n=n+m;this.v=m}return n};
p[H].r[A].D=function(c){c.html&&delete c.html;var d=V(this.ha());Y(d,"gs-result");var e;e=X(c.postUrl,c[va],this.t(),"gs-title");S(d,e);var f=new Date(c.publishedDate);e=U(this.Ta(f),"gs-publishedDate");S(d,e);f=new Date(c.publishedDate);e=U(this.kc(f),"gs-relativePublishedDate");S(d,e);e=U(c[Ga],"gs-snippet");S(d,e);e=X(c.blogUrl,c.blogUrl,this.t(),"gs-visibleUrl");S(d,e);c.html=d;this.ua(c.html)};O(p[H].r[A],"createResultHtml",p[H].r[A].D);p[H].r[A].qa=function(c){this.m=c==b||c==""?b:c};
O(p[H].r[A],"setSiteRestriction",p[H].r[A].qa);p[H].r[A].K=function(c){this.N=c==p[H].a.ka?a:c==p[H].a.la?g:g};O(p[H].r[A],"setResultOrder",p[H].r[A].K);
p[H].r[A].na=function(c,d){if(d)if(this.k==b){var e=V("gsc-configSetting");this.k=zb(b,"0",this.N,"gsc-configSettingCheckbox");S(e,this.k);S(e,U(P["sort-by-date"],"gsc-configSettingCheckboxLabel"));var f=V("gsc-configSettingSubmit");S(f,wb(P[Oa],"gsc-configSettingSubmit"));S(e,f);S(c,e);this.k[Sa]()}else{ma(this.k,this.N);this.k[Sa]()}else if(this.k)this.k[Ca]?this.K(p[H].a.ka):this.K(p[H].a.la)};p[H].l=function(){p[H].a[Pa](this);this.z="book";this.Aa="/GbookSearch";this.ma="http://books.google.com/books";this.Fb=g;this.Dc=b};N("google.search.BookSearch",p[H].l);eb(p[H].l,p[H].a);p[H].l.C="GbookSearch";O(p[H].l,"RESULT_CLASS",p[H].l.C);p[H].l.Kd="user-list";O(p[H].l,"USER_LIST",p[H].l.Kd);p[H].l.Cd=1;O(p[H].l,"TYPE_ALL_BOOKS",p[H].l.Cd);p[H].l.Gd=2;O(p[H].l,"TYPE_FULL_VIEW_BOOKS",p[H].l.Gd);p[H].l.o=[];
p[H].l.H=function(c,d,e,f,h){var k=0;if(c)k=da(c,10);var n=p[H].l.o[k];p[H].l.o[k]=b;n.U(d,e,f,h)};O(p[H].l,"RawCompletion",p[H].l.H);p[H].l[A].ga=function(c,d,e,f){var h;h=e==b?p[H].a.ia(p[H].l.o,this):e;var k;k=d==b?"google.search.BookSearch.RawCompletion":d;var n=this.ya(k,h,f);if(c){var m,o=c;if(this.G)o=o+" "+this.G;m="&q="+i(o);if(this.Fb)m=m+"&as_brr=1";if(this.Dc)m=m+"&as_list="+this.Dc;n=n+m;this.v=m}return n};
p[H].l[A].D=function(c){c.html&&delete c.html;c.thumbnailHtml=this.fc(c);var d=V(this.ha());Y(d,"gs-result");var e=V("gs-text-box"),f=ob(),h=pb(f,0),k=W(h,"gs-image-box"),n=W(h,"gs-text-box");S(k,c.thumbnailHtml[Va](a));S(n,e);S(d,f);var m;m=X(c.unescapedUrl,c[va],this.t(),"gs-title");S(e,m);m=U(P.by+"&nbsp;"+c.authors,"gs-author");S(e,m);m=V("gs-spacer");S(e,m);if(c.publishedYear){m=U(c.publishedYear,"gs-publishedDate");S(e,m)}if(da(c.pageCount,10)>0){m=U("-&nbsp;"+P["page-count"](c.pageCount),"gs-pageCount");
S(e,m)}m=X("http://books.google.com","books.google.com",this.t(),"gs-visibleUrl");S(e,m);c.html=d;this.ua(c.html)};O(p[H].l[A],"createResultHtml",p[H].l[A].D);
p[H].l[A].fc=function(c){var d=V("gs-image-box gs-book-image-box"),e=V("gs-row-1"),f=rb("http://books.google.com/googlebooks/pages-trans.gif",b,b,"gs-pages");S(e,f);f=rb("http://books.google.com/googlebooks/p_edge-trans.gif",b,b,"gs-page-edge");S(e,f);S(d,e);e=V("gs-row-2");var h=p[H].a.Xa(c.tbWidth,c.tbHeight,this.M);f=rb(c.tbUrl,h[E],h[bb],"gs-image");var k=tb(c.unescapedUrl,b,this.t(),"gs-image");u(k,"gs-image");S(k,f);S(e,k);S(d,e);return d};
p[H].l[A].V=function(c,d){if(c==p[H].a.xb)if(d)if(d==p[H].l.Cd)this.Fb=g;else if(d==p[H].l.Gd)this.Fb=a;else this.V(c,b);else this.Fb=g;else if(c==p[H].l.Kd)this.Dc=d&&d[Qa](/^[a-zA-Z0-9\-_]*$/)?d:b};O(p[H].l[A],"setRestriction",p[H].l[A].V);p[H].c=function(){p[H].a[Pa](this);this.ie=2;this.z="image";this.Aa="/GimageSearch";this.ma="http://images.google.com/images";this.m=this.wc=this.jc=this.pc=this.nc=this.mc=this.oc=this.Ga=b;this.M={width:112,height:84}};N("google.search.ImageSearch",p[H].c);eb(p[H].c,p[H].a);p[H].c.C="GimageSearch";O(p[H].c,"RESULT_CLASS",p[H].c.C);p[H].c.ud="restrict-imagesize";O(p[H].c,"RESTRICT_IMAGESIZE",p[H].c.ud);p[H].c.Ce=["icon"];O(p[H].c,"IMAGESIZE_SMALL",p[H].c.Ce);p[H].c.Be=["small","medium","large","xlarge"];
O(p[H].c,"IMAGESIZE_MEDIUM",p[H].c.Be);p[H].c.Ae=["xxlarge"];O(p[H].c,"IMAGESIZE_LARGE",p[H].c.Ae);p[H].c.ze=["huge"];O(p[H].c,"IMAGESIZE_EXTRA_LARGE",p[H].c.ze);p[H].c.rd="restrict-coloration";O(p[H].c,"RESTRICT_COLORIZATION",p[H].c.rd);p[H].c.Hc="mono";O(p[H].c,"COLORIZATION_BLACK_AND_WHITE",p[H].c.Hc);p[H].c.Jc="gray";O(p[H].c,"COLORIZATION_GRAYSCALE",p[H].c.Jc);p[H].c.Ic="color";O(p[H].c,"COLORIZATION_COLOR",p[H].c.Ic);p[H].c.qd="restrict-colorfilter";O(p[H].c,"RESTRICT_COLORFILTER",p[H].c.qd);
p[H].c.Sc="red";O(p[H].c,"COLOR_RED",p[H].c.Sc);p[H].c.Pc="orange";O(p[H].c,"COLOR_ORANGE",p[H].c.Pc);p[H].c.Vc="yellow";O(p[H].c,"COLOR_YELLOW",p[H].c.Vc);p[H].c.Oc="green";O(p[H].c,"COLOR_GREEN",p[H].c.Oc);p[H].c.Tc="teal";O(p[H].c,"COLOR_TEAL",p[H].c.Tc);p[H].c.Lc="blue";O(p[H].c,"COLOR_BLUE",p[H].c.Lc);p[H].c.Rc="purple";O(p[H].c,"COLOR_PURPLE",p[H].c.Rc);p[H].c.Qc="pink";O(p[H].c,"COLOR_PINK",p[H].c.Qc);p[H].c.Uc="white";O(p[H].c,"COLOR_WHITE",p[H].c.Uc);p[H].c.Nc="gray";
O(p[H].c,"COLOR_GRAY",p[H].c.Nc);p[H].c.Kc="black";O(p[H].c,"COLOR_BLACK",p[H].c.Kc);p[H].c.Mc="brown";O(p[H].c,"COLOR_BROWN",p[H].c.Mc);p[H].c.td="restrict-filetype";O(p[H].c,"RESTRICT_FILETYPE",p[H].c.td);p[H].c.Zc="jpg";O(p[H].c,"FILETYPE_JPG",p[H].c.Zc);p[H].c.$c="png";O(p[H].c,"FILETYPE_PNG",p[H].c.$c);p[H].c.Yc="gif";O(p[H].c,"FILETYPE_GIF",p[H].c.Yc);p[H].c.Xc="bmp";O(p[H].c,"FILETYPE_BMP",p[H].c.Xc);p[H].c.vd="restrict-imagetype";O(p[H].c,"RESTRICT_IMAGETYPE",p[H].c.vd);p[H].c.bd="face";
O(p[H].c,"IMAGETYPE_FACES",p[H].c.bd);p[H].c.ad="clipart";O(p[H].c,"IMAGETYPE_CLIPART",p[H].c.ad);p[H].c.cd="lineart";O(p[H].c,"IMAGETYPE_LINEART",p[H].c.cd);p[H].c.dd="news";O(p[H].c,"IMAGETYPE_NEWS",p[H].c.dd);p[H].c.ed="photo";O(p[H].c,"IMAGETYPE_PHOTO",p[H].c.ed);p[H].c.pd="restrict";O(p[H].c,"RESTRICT",p[H].c.pd);p[H].c.sd="cc_attribute";O(p[H].c,"RESTRICT_CREATIVE_COMMONS",p[H].c.sd);p[H].c.o=[];p[H].c.H=function(c,d,e,f,h){var k=0;if(c)k=da(c,10);var n=p[H].c.o[k];p[H].c.o[k]=b;n.U(d,e,f,h)};
O(p[H].c,"RawCompletion",p[H].c.H);
p[H].c[A].ga=function(c,d,e,f){var h;h=e==b?p[H].a.ia(p[H].c.o,this):e;var k;k=d==b?"google.search.ImageSearch.RawCompletion":d;var n=this.ya(k,h,f);if(c){var m,o=c;if(this.G)o=o+" "+this.G;m="&q="+i(o);if(this.Ga)m=m+"&safe="+this.Ga;if(this.oc)m=m+"&imgsz="+i(this.oc);if(this.mc)m=m+"&imgc="+i(this.mc);if(this.nc)m=m+"&imgcolor="+i(this.nc);if(this.pc)m=m+"&imgtype="+i(this.pc);if(this.jc)m=m+"&as_filetype="+i(this.jc);if(this.wc)m=m+"&restrict="+i(this.wc);if(this.m)m=m+"&as_sitesearch="+i(this.m);
n=n+m;this.v=m;if(f&&f!=0)this.v=this.v+"&start="+f}return n};
p[H].c[A].D=function(c){c.html&&delete c.html;var d=V(this.ha());Y(d,"gs-result");var e=V("gs-image-box"),f=p[H].a.Xa(c.tbWidth,c.tbHeight,this.M),h=rb(c.tbUrl,f[E],f[bb],"gs-image");h[G].left=(this.M[E]-f[E])/2+"px";t(h,c.titleNoFormatting+" ("+c.visibleUrl+")");var k=tb(c.unescapedUrl,b,this.t(),"gs-image");u(k,"gs-image");S(k,h);S(e,k);S(d,e);var n=V("gs-text-box"),m;m=U(c[Ga],"gs-snippet");t(m,c.contentNoFormatting);S(n,m);m=U(c[E]+" x "+c[bb],"gs-size");S(n,m);m=X(c.originalContextUrl,c.visibleUrl,
this.t(),"gs-visibleUrl");t(m,c.visibleUrl);S(n,m);S(d,n);c.html=d;this.ua(c.html)};O(p[H].c[A],"createResultHtml",p[H].c[A].D);p[H].c[A].qa=function(c){this.m=c};O(p[H].c[A],"setSiteRestriction",p[H].c[A].qa);
p[H].c[A].V=function(c,d){if(c==p[H].a.Sb)this.Ga=d?d==p[H].a.Vb||d==p[H].a.Ub?d:d==p[H].a.Tb?b:b:b;else if(c==p[H].c.ud)this.oc=d?d.join("|"):b;else if(c==p[H].c.rd)this.mc=d?d==p[H].c.Hc||d==p[H].c.Jc||d==p[H].c.Ic?d:b:b;else if(c==p[H].c.qd)this.nc=d?d==p[H].c.Sc||d==p[H].c.Pc||d==p[H].c.Vc||d==p[H].c.Oc||d==p[H].c.Tc||d==p[H].c.Lc||d==p[H].c.Rc||d==p[H].c.Qc||d==p[H].c.Uc||d==p[H].c.Nc||d==p[H].c.Kc||d==p[H].c.Mc?d:b:b;else if(c==p[H].c.td)this.jc=d?d==p[H].c.Zc||d==p[H].c.$c||d==p[H].c.Yc||d==
p[H].c.Xc?d:b:b;else if(c==p[H].c.vd)this.pc=d?d==p[H].c.bd||d==p[H].c.ad||d==p[H].c.cd||d==p[H].c.dd||d==p[H].c.ed?d:b:b;else if(c==p[H].c.pd)this.wc=d?d==p[H].c.sd?d:b:b};O(p[H].c[A],"setRestriction",p[H].c[A].V);p[H].e=function(){p[H].a[Pa](this);this.Z=b;this.Y="San Francisco, CA";this.ca={y:37.77916,x:-122.42009};this.Pa=b;this.lb=a;this.bb=g;this.Va=b;this.Ra=a;this.da=lb(this,this.na);this.Qa="gsc-locationConfig";this.z="local";this.Aa="/GlocalSearch";this.ma="http://www.google.com/local";this.Ma=this.F=b};N("google.search.LocalSearch",p[H].e);eb(p[H].e,p[H].a);p[H].e.C="GlocalSearch";O(p[H].e,"RESULT_CLASS",p[H].e.C);p[H].e.Fd="blended";O(p[H].e,"TYPE_BLENDED_RESULTS",p[H].e.Fd);p[H].e.Id="kmlonly";
O(p[H].e,"TYPE_KMLONLY_RESULTS",p[H].e.Id);p[H].e.Jd="localonly";O(p[H].e,"TYPE_LOCALONLY_RESULTS",p[H].e.Jd);p[H].e.Ec="disabled";O(p[H].e,"ADDRESS_LOOKUP_DISABLED",p[H].e.Ec);p[H].e.Fc="enabled";O(p[H].e,"ADDRESS_LOOKUP_ENABLED",p[H].e.Fc);p[H].e.zd=17;O(p[H].e,"STATIC_MAP_ZOOM_FARTHEST",p[H].e.zd);p[H].e.Oe=4;O(p[H].e,"STATIC_MAP_ZOOM_DEFAULT",p[H].e.Oe);p[H].e.yd=0;O(p[H].e,"STATIC_MAP_ZOOM_CLOSEST",p[H].e.yd);p[H].e.Zb=8;O(p[H].e,"STATIC_MAP_MAX_POINTS",p[H].e.Zb);p[H].e.Ff=3.141592653589;
p[H].e.ef=6367000;p[H].e.eg=16093;p[H].e.o=[];p[H].e.H=function(c,d,e,f,h){var k=0;if(c)k=da(c,10);var n=p[H].e.o[k];p[H].e.o[k]=b;n.resultViewport=d&&d.viewport?d.viewport:b;n.U(d,e,f,h)};O(p[H].e,"RawCompletion",p[H].e.H);
p[H].e[A].ga=function(c,d,e,f){var h;h=e==b?p[H].a.ia(p[H].e.o,this):e;var k;k=d==b?"google.search.LocalSearch.RawCompletion":d;var n=this.ya(k,h,f),m="";if(c){m="&q="+i(c);n=n+m}this.xh=b;var o;if(this.Z){var s,x;if(this.lb){s=this.Z.getCenterLatLng();x=this.Z.getSpanLatLng();o="&sll="+s.y+","+s.x;o+="&sspn="+x[bb]+","+x[E];o+=p[H].e.Ab(s.y,s.x);n+=o;m+=o}else{s=this.Z.getCenter();x=this.Z.getBounds().toSpan().toUrlValue();o="&sll="+s.y+","+s.x;o+="&sspn="+x;o+=p[H].e.Ab(s.y,s.x);n+=o;m+=o}}else if(this.ca){o=
"&sll="+this.ca.y+","+this.ca.x;if(this.Pa)o=o+"&sspn="+this.Pa.lat+","+this.Pa.lng;o+=p[H].e.Ab(this.ca.y,this.ca.x);n+=o;m+=o}else if(this.Y){o="&near="+i(this.Y);n+=o;m+=o}if(this.bb){n+="&nogeocode=t";m+="&nogeocode=t"}if(this.Va){n+="&mrt="+i(this.Va);m+="&mrt="+i(this.Va)}if(m)this.v=m;return n};p[H].e.Ab=function(c,d){var e=2*p[H].e.eg/p[H].e.ef*2*p[H].e.Ff,f=d-e,h=c+e,k=d+e;return"&gll="+r[Fa]((c-e)*1000000)+","+r[Fa](f*1000000)+","+r[Fa](h*1000000)+","+r[Fa](k*1000000)+"&llsep=500,500"};
O(p[H].e,"centerToGll",p[H].e.Ab);
p[H].e[A].D=function(c){c.html&&delete c.html;var d=V(this.ha());Y(d,"gs-result");var e;e=X(c.url,c[va],this.t(),"gs-title");S(d,e);if(c.listingType=="kml"&&c[Ga]&&c[Ga]!=""){e=U(c[Ga],"gs-snippet");S(d,e)}var f=V("gs-address");if(c.addressLines&&c.addressLines[z]>0)for(var h=0;h<c.addressLines[z];h++){var k=c.addressLines[h],n="gs-addressLine";if(h==0)n="gs-street gs-addressLine";else if(h==1)n="gs-city gs-addressLine";e=U(k,n);S(f,e)}else{e=U(c.streetAddress,"gs-street");S(f,e);var m="";if(c.city!=
""){m=c.city;if(c.region!="")m+=", "}e=U(m,"gs-city");S(f,e);e=U(c.region,"gs-region");S(f,e)}e=U(c.country,"gs-country");S(f,e);S(d,f);if(c.phoneNumbers&&c.phoneNumbers[z]){for(var o=b,s=b,x=c.phoneNumbers[0],y,I=0;I<c.phoneNumbers[z];I++){y=c.phoneNumbers[I];if(y[Wa]=="main"){o=y;break}if(y[Wa]==""||y[Wa]=="mobile"&&s==b)s=y}y=o?o:s?s:x;e=U(y.number,"gs-phone");S(d,e)}if(c.ddUrl&&c.ddUrl!=""){e=X(c.ddUrl,P.directions,this.t(),"gs-directions");S(d,e)}if(c.ddUrlToHere&&c.ddUrlToHere!=""&&c.ddUrlFromHere&&
c.ddUrlFromHere!=""){e=V("gs-directions-to-from");var B=U(P["get-directions"]+":","gs-label");e[w](B);B=X(c.ddUrlToHere,P["to-here"],this.t(),"gs-secondary-link");e[w](B);B=U("-","gs-spacer");e[w](B);B=X(c.ddUrlFromHere,P["from-here"],this.t(),"gs-secondary-link");e[w](B);S(d,e)}c.html=d;this.ua(c.html)};O(p[H].e[A],"createResultHtml",p[H].e[A].D);
p[H].e[A].oe=function(c){if(c.centerAndZoom){this.lb=a;this.Z=c;this.ca=b;this.Y="";if(this.F)this.F=b}else if(c.setCenter){this.lb=g;this.Z=c;this.Pa=this.ca=b;this.Y="";if(this.F)this.F=b}else if(c.x&&c.y){this.lb=a;this.ca=c;this.Z=this.Pa=b;this.Y="";if(this.F)this.F=b}else if(c!=b&&c!=""){this.lb=a;this.Z=b;this.Y=c;this.ca=b;if(this.F)this.F=b;var d=new p[H].e;d.tb(this,this.Re,[d,c]);d[L](c)}};O(p[H].e[A],"setCenterPoint",p[H].e[A].oe);
p[H].e[A].Re=function(c,d){if(c.results&&c.results[z]){var e={};e.y=ga(c.results[0].lat);e.x=ga(c.results[0].lng);this.ca=e;this.Y=d;this.Ra=a;this.Z=b;if(c.resultViewport){var f={};f.Ng=ga(c.resultViewport.span.lat)/2;f.Og=ga(c.resultViewport.span.lng)/2;this.Pa=f}}};
p[H].e[A].na=function(c,d){if(d){if(this.F==b){var e=b;if(this.Z==b){var f=V("gsc-configSetting");this.F=xb(b,"gsc-configSettingInput",this.Y==""?b:this.Y);S(f,U(P["search-location"],"gsc-configSettingInputLabel"));S(f,this.F);S(c,f);e=this.F}f=V("gsc-configSetting");this.Ma=zb(b,"0",this.bb,"gsc-configSettingCheckbox");S(f,this.Ma);S(f,U(P["disable-address-lookup"],"gsc-configSettingCheckboxLabel"));if(e==b)e=this.Ma;var h=U(b,"gsc-configSettingSubmit");S(h,wb(P[Oa],"gsc-configSettingSubmit"));S(f,
h);S(c,f);e[Sa]()}}else{if(this.F){if(this.F[Ia]){this.Y=this.F[Ia];this.oe(this.Y)}this.F=b}if(this.Ma){this.bb=this.Ma[Ca];this.Ma=b}mb(c)}};p[H].e[A].Of=function(c){if(c==p[H].e.Ec)this.bb=a;else if(c==p[H].e.Fc)this.bb=g};O(p[H].e[A],"setAddressLookupMode",p[H].e[A].Of);p[H].e.ke=function(c,d,e,f){var h=c.staticMapUrl;h=h[F](/&h=\d*/,"&h="+d);h=h[F](/&w=\d*/,"&w="+e);if(f&&f>=p[H].e.yd&&f<=p[H].e.zd)h=h[F](/&zl=\d*/,"&zl="+f);return c.staticMapUrl=h};O(p[H].e,"resizeStaticMapUrl",p[H].e.ke);
p[H].e.$e=function(c,d,e,f){var h="",k="http://mt.google.com/mapdata?cc=us&tstyp=5&zl=4&w=150&h=100",n={};n.staticMapUrl=k;k=p[H].e.ke(n,d,e,f);if(f==b)k=k[F](/&zl=\d*/,"");var m=c[z];if(m>p[H].e.Zb)m=p[H].e.Zb;for(var o=0;o<m;o++){var s,x,y=c[o];if(y.lat&&y.lng)if(typeof y.lat=="string"){s=ga(y.lat);x=ga(y.lng)}else{s=y.lat;x=y.lng}else if(y.x&&y.y){s=y.y;x=y.x}else return b;var I=x*1000000,B="&Point=b&Point.latitude_e6=__LAT__&Point.longitude_e6=__LNG__&Point.iconid=__ICONID__&Point=e"[F](/__LAT__/,
r[Fa](s*1000000));B=B[F](/__LNG__/,r[Fa](I));var T=51+o;if(m==1)T=15;B=B[F](/__ICONID__/,T);h=h+B}return k+h};O(p[H].e,"computeStaticMapUrl",p[H].e.$e);p[H].e[A].V=function(c,d){if(c==p[H].a.xb)if(d){this.Va=b;this.Va=d==p[H].e.Fd||d==p[H].e.Id||d==p[H].e.Jd?d:b}else this.Va=b};O(p[H].e[A],"setRestriction",p[H].e[A].V);p[H].n=function(){p[H].a[Pa](this);this.z="news";this.Aa="/GnewsSearch";this.ma="http://news.google.com/nwshp";this.kh=b;this.Ya="site:";this.N=g;this.Ra=a;this.da=lb(this,this.na);this.Qa="gsc-newsConfig";this.h=this.k=b};N("google.search.NewsSearch",p[H].n);eb(p[H].n,p[H].a);p[H].n.C="GnewsSearch";O(p[H].n,"RESULT_CLASS",p[H].n.C);p[H].n.od="GnewsSearch.quote";O(p[H].n,"QUOTE_RESULT_CLASS",p[H].n.od);p[H].n.o=[];
p[H].n.H=function(c,d,e,f,h){var k=0;if(c)k=da(c,10);var n=p[H].n.o[k];p[H].n.o[k]=b;n.U(d,e,f,h)};O(p[H].n,"RawCompletion",p[H].n.H);
p[H].n[A].ga=function(c,d,e,f){var h;h=e==b?p[H].a.ia(p[H].n.o,this):e;var k;k=d==b?"google.search.NewsSearch.RawCompletion":d;var n=this.ya(k,h,f);if(c||!c&&this.h){var m,o=b;if(c)o=c;if(this.G)o=o==b?this.G:o+" "+this.G;if(this.m)o=o==b?this.Ya+this.m:o+" "+this.Ya+this.m;m=o?"&q="+i(o):"";if(this.N)m=m+"&scoring=d";if(this.h){var s="";for(var x in this.h)if(x.charAt(0)==":")s+="&"+this.h[x];m=m+s}if(this.m&&this.Ya=="source:")n=n[F](/&hl=.*&/,"&hl=en&");n=n+m;this.v=m;if(f&&f!=0)this.v=this.v+
"&start="+f}return n};
p[H].n[A].D=function(c){c.html&&delete c.html;if(!(c.GsearchResultClass==p[H].n.od)){var d=V(this.ha());Y(d,"gs-result");var e;e=X(c.unescapedUrl,c[va],this.t(),"gs-title");S(d,e);e=U(c.publisher,"gs-publisher");S(d,e);var f=c[Ja][Ea](",");if(f[z]>1){e=U(", "+f[f[z]-1],"gs-location");S(d,e)}var h=new Date(c.publishedDate);e=U(" - "+this.Ta(h),"gs-publishedDate");S(d,e);h=new Date(c.publishedDate);e=U(" - "+this.kc(h),"gs-relativePublishedDate");S(d,e);e=U(c[Ga],"gs-snippet");S(d,e);if(c.clusterUrl&&
c.clusterUrl!=""){e=X(c.clusterUrl,P["related-articles"]+"&nbsp;&raquo;",this.t(),"gs-clusterUrl");S(d,e)}c.html=d;this.ua(c.html)}};O(p[H].n[A],"createResultHtml",p[H].n[A].D);p[H].n[A].qa=function(c){if(c==b||c==""){this.m=b;this.Ya="site:"}else if(c[Qa]("[./:]")){this.Ya="site:";this.m=c}else{this.Ya="source:";this.m=c[F](/\s/g,"_")}};O(p[H].n[A],"setSiteRestriction",p[H].n[A].qa);p[H].n[A].K=function(c){this.N=c==p[H].a.ka?a:c==p[H].a.la?g:g};O(p[H].n[A],"setResultOrder",p[H].n[A].K);
p[H].n[A].na=function(c,d){if(d)if(this.k==b){var e=V("gsc-configSetting");this.k=zb(b,"0",this.N,"gsc-configSettingCheckbox");S(e,this.k);S(e,U(P["sort-by-date"],"gsc-configSettingCheckboxLabel"));var f=V("gsc-configSettingSubmit");S(f,wb(P[Oa],"gsc-configSettingSubmit"));S(e,f);S(c,e);this.k[Sa]()}else{ma(this.k,this.N);this.k[Sa]()}else if(this.k)this.k[Ca]?this.K(p[H].a.ka):this.K(p[H].a.la)};
p[H].n[A].V=function(c,d){if(c==p[H].a.Rb)if(d)for(var e in d){var f=d[e];if(e=="geo"){if(this.h==b)this.h={};this.h[":geo"]=e+"="+i(f)}if(e=="qsid"){if(this.h==b)this.h={};this.h[":qsid"]=e+"="+i(f)}if(e=="quotesearch"){if(this.h==b)this.h={};this.h[":quotesearch"]=e+"="+i(f)}if(e=="topic"){if(this.h==b)this.h={};this.h[":topic"]=e+"="+i(f)}if(e=="ned"){if(this.h==b)this.h={};this.h[":ned"]=e+"="+i(f)}if(e=="as_mind"){if(this.h==b)this.h={};this.h[":as_mind"]=e+"="+i(f)}if(e=="as_minm"){if(this.h==
b)this.h={};this.h[":as_minm"]=e+"="+i(f)}if(e=="as_miny"){if(this.h==b)this.h={};this.h[":as_miny"]=e+"="+i(f)}if(e=="as_maxd"){if(this.h==b)this.h={};this.h[":as_maxd"]=e+"="+i(f)}if(e=="as_maxm"){if(this.h==b)this.h={};this.h[":as_maxm"]=e+"="+i(f)}if(e=="as_maxy"){if(this.h==b)this.h={};this.h[":as_maxy"]=e+"="+i(f)}}else this.h=b};O(p[H].n[A],"setRestriction",p[H].n[A].V);p[H].i=function(){p[H].a[Pa](this);this.z="patent";this.Aa="/GpatentSearch";this.ma="http://www.google.com/patents";this.ue="";this.ob=b;this.Ra=a;this.da=lb(this,this.na);this.Qa="gsc-patentConfig";this.k=b};N("google.search.PatentSearch",p[H].i);eb(p[H].i,p[H].a);p[H].i.C="GpatentSearch";O(p[H].i,"RESULT_CLASS",p[H].i.C);p[H].i.Dd=1;O(p[H].i,"TYPE_ANY_STATUS",p[H].i.Dd);p[H].i.Hd=2;O(p[H].i,"TYPE_ISSUED_PATENTS",p[H].i.Hd);p[H].i.Ed=3;O(p[H].i,"TYPE_APPLICATIONS",p[H].i.Ed);p[H].i.o=[];
p[H].i.H=function(c,d,e,f,h){var k=0;if(c)k=da(c,10);var n=p[H].i.o[k];p[H].i.o[k]=b;n.U(d,e,f,h)};O(p[H].i,"RawCompletion",p[H].i.H);p[H].i[A].ga=function(c,d,e,f){var h;h=e==b?p[H].a.ia(p[H].i.o,this):e;var k;k=d==b?"google.search.PatentSearch.RawCompletion":d;var n=this.ya(k,h,f);if(c){var m,o=c;if(this.G)o=o+" "+this.G;m="&q="+i(o)+this.ue;if(this.ob)m=m+this.ob;n=n+m;this.v=m}return n};
p[H].i[A].D=function(c){c.html&&delete c.html;c.thumbnailHtml=this.fc(c);var d=V(this.ha());Y(d,"gs-result");var e=V("gs-text-box"),f=ob(),h=pb(f,0),k=W(h,"gs-image-box"),n=W(h,"gs-text-box");S(k,c.thumbnailHtml[Va](a));S(n,e);S(d,f);var m;m=X(c.unescapedUrl,c[va],this.t(),"gs-title");S(e,m);var o=V("gs-patent-info gs-metadata");S(e,o);var s=b;s=c.patentNumber?c.patentStatus=="issued"?P["us-pat"]+"&nbsp;"+c.patentNumber:P["us-pat-app"]+"&nbsp;"+c.patentNumber:P["us-pat-app"]+"&nbsp; N/A";m=U(s,"gs-patent-number");
S(o,m);if(c.applicationDate){m=U(" - "+this.Ta(new Date(c.applicationDate)),"gs-publishedDate");S(o,m)}if(c.assignee){m=U(" - "+c.assignee,"gs-author");S(o,m)}m=U(c[Ga],"gs-snippet");S(e,m);S(e,m);c.html=d;this.ua(c.html)};O(p[H].i[A],"createResultHtml",p[H].i[A].D);p[H].i[A].fc=function(c){var d=V("gs-patent-image"),e=rb(c.tbUrl,75,100,"gs-image"),f=tb(c.unescapedUrl,b,this.t(),"gs-image");u(f,"gs-image");S(f,e);S(d,f);return d};
p[H].i[A].K=function(c){this.ob=c==p[H].a.ka?"&scoring=d":c==p[H].a.nd?"&scoring=ad":c==p[H].a.la?b:b};O(p[H].i[A],"setResultOrder",p[H].i[A].K);p[H].i[A].V=function(c,d){if(c==p[H].a.xb)this.ue=d?d==p[H].i.Dd?"":d==p[H].i.Hd?"&as_psrg=1":d==p[H].i.Ed?"&as_psra=1":"":""};O(p[H].i[A],"setRestriction",p[H].i[A].V);
p[H].i[A].na=function(c,d){if(d){var e=g;if(this.ob&&this.ob=="&scoring=d")e=a;if(this.k==b){var f=V("gsc-configSetting");this.k=zb(b,"0",e,"gsc-configSettingCheckbox");S(f,this.k);S(f,U(P["sort-by-date"],"gsc-configSettingCheckboxLabel"));var h=V("gsc-configSettingSubmit");S(h,wb(P[Oa],"gsc-configSettingSubmit"));S(f,h);S(c,f);this.k[Sa]()}else{ma(this.k,e);this.k[Sa]()}}else if(this.k)this.k[Ca]?this.K(p[H].a.ka):this.K(p[H].a.la)};p[H].B=function(){this.je=this.X=p[H].b.Ca;this.j=b;this.M={width:112,height:84};this.Qb={width:100,height:75};this.mb=b};N("google.search.SearcherOptions",p[H].B);p[H].B[A].qe=function(c){switch(c){case p[H].b.Wc:case p[H].b.Ka:case p[H].b.Ca:this.X=c;break;default:this.X=p[H].b.Ca;break}this.je=this.X};O(p[H].B[A],"setExpandMode",p[H].B[A].qe);p[H].B[A].Uf=function(c){mb(c);this.j=c};O(p[H].B[A],"setRoot",p[H].B[A].Uf);p[H].B[A].Kb=function(c){this.mb=c};O(p[H].B[A],"setNoResultsString",p[H].B[A].Kb);
p[H].B[A].Pf=function(c){if(c>100)c=100;sa(this.M,c);la(this.M,r[Ba](c*1.33))};O(p[H].B[A],"setImageResultsTbHeight",p[H].B[A].Pf);p[H].B[A].$f=function(c){if(c>100)c=100;sa(this.Qb,c);la(this.Qb,r[Ba](c*1.33))};O(p[H].B[A],"setVideoResultsTbHeight",p[H].B[A].$f);p[H].R=function(){ka(this,b);this.te=b;this.W=p[H].b.ra};N("google.search.DrawOptions",p[H].R);p[H].R[A].Qf=function(c){ka(this,c)};O(p[H].R[A],"setInput",p[H].R[A].Qf);
p[H].R[A].Vf=function(c){if(c&&typeof c=="string")c=q.getElementById(c);this.te=c};O(p[H].R[A],"setSearchFormRoot",p[H].R[A].Vf);p[H].R[A].pe=function(c){this.W=c==p[H].b.ra||c==p[H].b.Ja?c:p[H].b.ra};O(p[H].R[A],"setDrawMode",p[H].R[A].pe);
p[H].A=function(c,d,e){this.u=e;this.dc=this.ic=g;this.f=c;this.w=b;this.Kf=R(d,p[H].b[A].Ef,[this]);this.Nf=R(d,p[H].b[A].uc,[this,p[H].A.Yb]);this.Mf=R(d,p[H].b[A].uc,[this,p[H].A.Xb]);this.Lf=R(d,p[H].b[A].uc,[this,p[H].A.xd]);this.Jf=R(d,p[H].b[A].Df,[this]);this.If=R(d,p[H].b[A].zf,[this]);this.f.tb(d,p[H].b[A].U,[this]);this.f.pa(d.Ib);this.f.sb(d.Ea);this.Q=this.Sa=this.va=this.xc=this.ib=this.Ob=this.j=b;this.kb=a};p[H].A.Wb=0;p[H].A.Yb=1;p[H].A.Xb=2;p[H].A.xd=3;
p[H].A[A].Ac=function(c){var d="gsc-results-selector ";d+=c==p[H].A.Wb?this.u.X==p[H].b.Ca?"gsc-one-result-active":this.f.Wa==p[H].a.ba?"gsc-more-results-active":"gsc-all-results-active":c==p[H].A.Yb?"gsc-one-result-active":c==p[H].A.Xb?"gsc-more-results-active":"gsc-all-results-active";u(this.xc,d)};
p[H].b=function(c){if(!p[K].KeyVerified)if(p[H].b.he())p[K].KeyVerified=a;else return;this.Ib=p[H].a.ba;this.W=p[H].b.ra;this.Jb=this.j=b;ka(this,b);this.Nb=p[H].b.yb;this.sf=R(this,p[H].b[A].Af,[b]);this.tf=R(this,p[H].b[A].Bf,[b]);this.Ua=this.pb=this.yc=this.Hb=b;this.cb=this.xf=g;this.Ea=p[H].a.ab;this.qc=P.copy;this.d=[];this.og=[];var d;if(c)for(var e=0;e<c[z];e++){d=new p[H].A(c[e],this,g);this.d[ua](d)}};N("google.search.SearchControl",p[H].b);p[H].b.Me=P["no-results"];
O(p[H].b,"NO_RESULTS_DEFAULT_STRING",p[H].b.Me);p[H].b.Bd=350;O(p[H].b,"TIMEOUT_SHORT",p[H].b.Bd);p[H].b.yb=500;O(p[H].b,"TIMEOUT_MEDIUM",p[H].b.yb);p[H].b.Ad=700;O(p[H].b,"TIMEOUT_LONG",p[H].b.Ad);p[H].b.Wc=1;O(p[H].b,"EXPAND_MODE_CLOSED",p[H].b.Wc);p[H].b.Ka=2;O(p[H].b,"EXPAND_MODE_OPEN",p[H].b.Ka);p[H].b.Ca=3;O(p[H].b,"EXPAND_MODE_PARTIAL",p[H].b.Ca);p[H].b.ra=1;O(p[H].b,"DRAW_MODE_LINEAR",p[H].b.ra);p[H].b.Ja=2;O(p[H].b,"DRAW_MODE_TABBED",p[H].b.Ja);p[H].b.kd="save";
O(p[H].b,"KEEP_LABEL_SAVE",p[H].b.kd);p[H].b.jd="keep";O(p[H].b,"KEEP_LABEL_KEEP",p[H].b.jd);p[H].b.hd="include";O(p[H].b,"KEEP_LABEL_INCLUDE",p[H].b.hd);p[H].b.gd="copy";O(p[H].b,"KEEP_LABEL_COPY",p[H].b.gd);p[H].b.fd="blank";O(p[H].b,"KEEP_LABEL_BLANK",p[H].b.fd);try{p[H].b.appPath=l[Ja].href}catch(Sb){p[H].b.appPath=b}
p[H].b.he=function(){var c=a,d;{var e=l[Ja].host[db]()[Ea](".");if(e[z]<2)d=g;else{var f=e.pop(),h=e.pop();if((h=="igoogle"||h=="gmodules"||h=="googlesyndication")&&f=="com")d=a;else{if(f[z]==2&&e[z]>0)if(Eb[h]&&Eb[h][f]==1)h=e.pop();d=h=="google"}}}if(d)return a;if(p[K].LoadFailure)if(p[K].OriginalAppPath&&p[H].b.appPath)if(p[H].b.appPath==p[K].OriginalAppPath){p[K].LoadFailure=g;c=a}else{p[K].LoadFailure=g;c=a}p[K].KeyVerified=a;p[K].LoadFailure=g;return c};O(p[H].b,"keyCheck",p[H].b.he);
p[H].b[A].eb=function(c,d){this.Na=a;this.Oa=c;if(d){if(d.includeVerticalAds!=ca)this.Ba=d.includeVerticalAds;if(d.includeSideAds!=ca)this.Ba=d.includeSideAds;if(d.iframes!=ca)this.hb=d.iframes;if(d.useNarrowTopAd!=ca)if(this.hb)this.we=d.useNarrowTopAd;if(d.channel)this.Nd=d.channel;if(d.clientIP)this.Od=d.clientIP;if(d.safe)this.Pd=d.safe;if(d[Ha])this.Qd=d[Ha];var e=d.adtest||d.debug;if(e)this.$b=e;if(d.numTopAds!=ca){this.Fa=d.numTopAds;this.Fa=r.max(0,r.min(4,this.Fa))}if(d.numSideAds!=ca){this.xa=
d.numSideAds;this.Ba=(this.xa=r.max(0,r.min(8,this.xa)))?a:g}this.ne=d.enableSearchCompleteCallback?a:g}p[K][Za]("hl","afs_ads")};O(p[H].b[A],"enableAds",p[H].b[A].eb);p[H].b[A].La=function(c,d){d||(d=new p[H].B);c.oa=b;this.d[ua](new p[H].A(c,this,d));if(this.qb(c))this.pf=a;c.rb="gsc"};O(p[H].b[A],"addSearcher",p[H].b[A].La);
p[H].b[A].Ud=function(c){if(this.d[c].u.j){this.d[c].kb=g;this.d[c].j=this.d[c].u.j;Y(this.d[c].j,"gsc-resultsRoot");$(this.d[c].j,"gsc-resultsbox-visible");Y(this.d[c].j,"gsc-resultsbox-invisible")}else this.d[c].j=V("gsc-resultsRoot");this.d[c].f.wb&&yb(this.d[c].j,"gsc-resultsRoot-"+this.d[c].f.wb);if(this.W==p[H].b.Ja)this.q[c].fa=this.d[c].j;var d=ob(b,b,"gsc-resultsHeader"),e=pb(d,0);this.d[c].Ia=W(e,"gsc-twiddleRegionCell");var f=W(e,"gsc-configLabelCell");this.d[c].Ob=U("","gsc-twiddle");
S(this.d[c].Ia,this.d[c].Ob);var h=U(this.d[c].f.mf(),"gsc-title");S(this.d[c].Ob,h);this.d[c].ib=U("","gsc-stats");S(this.d[c].Ia,this.d[c].ib);var k=U(),n=U(P.blank,"gsc-result-selector gsc-one-result"),m=U(P.blank,"gsc-result-selector gsc-more-results"),o=U(P.blank,"gsc-result-selector gsc-all-results");t(n,P["show-one-result"]);t(m,P["show-more-results"]);t(o,P["show-all-results"]);S(k,n);S(k,m);S(k,o);pa(n,this.d[c].Nf);pa(m,this.d[c].Mf);pa(o,this.d[c].Lf);this.d[c].xc=k;this.d[c].Ac(p[H].A.Wb);
S(this.d[c].Ia,this.d[c].xc);pa(this.d[c].Ob,this.d[c].Kf);if(this.d[c].f.da){this.d[c].P=nb("","gsc-configLabel");v(this.d[c].P,P.blank);Y(this.d[c].P,"gsc-twiddle-closed");S(f,this.d[c].P);pa(this.d[c].P,this.d[c].Jf);t(this.d[c].P,P.settings);this.d[c].va=V("gsc-config");Y(this.d[c].va,this.d[c].f.Qa);this.d[c].Sa=vb("gsc-config");Y(this.d[c].Sa,this.d[c].f.Qa);this.d[c].Sa.onsubmit=this.d[c].If;S(this.d[c].va,this.d[c].Sa);qa(this.d[c].va[G],"none")}this.d[c].Q=V("gsc-results");var s=this.d[c].f.lc();
Y(this.d[c].Q,s);this.d[c].u.j==b&&S(this.za,this.d[c].j);S(this.d[c].j,d);this.d[c].va&&S(this.d[c].j,this.d[c].va);S(this.d[c].j,this.d[c].Q)};p[H].b[A].Vd=function(c){var d=this.d[c],e={},f=d.f.of();f=f[F](/ /g,"&nbsp;");e.T=U(f);e.fa=b;e.zc=d.f;e.z=d.f.z;pa(e.T,R(this,this.dg,[c]));this.q[c]=e;S(this.$,e.T);var h="gs-spacer";if(gb("opera"))h=h+" gs-spacer-opera";var k=nb(" ",h);S(this.$,k);d.u.qe(p[H].b.Ka)};
p[H].b[A].Eb=function(c,d){var e=b,f=b;if(d)if(d.W){this.W=d.W;e=d[D];f=d.te}else this.W=p[H].b.ra;else this.W=p[H].b.ra;this.j=V("gsc-control");if(e!=b){ka(this,e);this[D].onkeyup=this.sf;this[D].onpaste=this.tf}else{if(f==b)f=this.j;var h=new p[H].L(a,f);h.se(this,this.submit);h.re(this,this.bc);ka(this,h[D]);this.fb&&h.qf()}this.za=V("gsc-resultsbox-invisible");if(this.W==p[H].b.Ja){this.$=V("gsc-tabsAreaInvisible");S(this.j,this.$);this.q=[];for(var k=this.I=0;k<this.d[z];k++)this.Vd(k)}this.aa=
this.j;if(this.Na){this.aa=V("gsc-wrapper");this.O=V("gsc-adBlockInvisible");this.S=V("gsc-adBlockVerticalInvisible");S(this.aa,this.O);S(this.j,this.S);S(this.j,this.aa);this.$b&&yb(this.j,"gsc-ad-preview")}S(this.aa,this.za);for(k=0;k<this.d[z];k++){this.Ud(k);if(this.W==p[H].b.Ja){Y(this.q[k].T,"gsc-tabHeader");Y(this.q[k].fa,"gsc-tabData");if(k==this.I){Y(this.q[k].T,"gsc-tabhActive");Y(this.q[k].fa,"gsc-tabdActive")}else{Y(this.q[k].T,"gsc-tabhInactive");Y(this.q[k].fa,"gsc-tabdInactive")}}}if(c&&
typeof c=="string")c=q.getElementById(c);if(c){var n=this.j;if(c)try{mb(c);c[w](n)}catch(m){}var o=this.kf();if(o&&o<300){this.xf=a;Y(this.j,"gsc-narrow")}}};O(p[H].b[A],"draw",p[H].b[A].Eb);p[H].b[A].Yf=function(c){switch(c){case p[H].b.Bd:case p[H].b.yb:case p[H].b.Ad:this.Nb=c;break;default:this.Nb=p[H].b.yb;break}};O(p[H].b[A],"setTimeoutInterval",p[H].b[A].Yf);
p[H].b[A].Sf=function(c,d,e){if(e)switch(e){case p[H].b.kd:case p[H].b.jd:case p[H].b.hd:case p[H].b.gd:case p[H].b.fd:this.qc=P[e];break;default:this.qc=e;break}this.Hb=lb(c,d)};O(p[H].b[A],"setOnKeepCallback",p[H].b[A].Sf);M=p[H].b[A];M.qb=function(c){var d=c.z;if(this.fb){if(d=="web"&&c.J!=p[H].g.ea)return g;return a}else return d=="blog"||d=="image"?a:g};
M.dg=function(c){if(!(this.I==c)){$(this.q[this.I].T,"gsc-tabhActive");$(this.q[this.I].fa,"gsc-tabdActive");Y(this.q[this.I].T,"gsc-tabhInactive");Y(this.q[this.I].fa,"gsc-tabdInactive");this.I=c;Y(this.q[this.I].T,"gsc-tabhActive");Y(this.q[this.I].fa,"gsc-tabdActive");$(this.q[this.I].T,"gsc-tabhInactive");$(this.q[this.I].fa,"gsc-tabdInactive");if(this.Na){var d=this.q[this.I].zc;this.qb(d)?this.jb():this.Wd()}}};
M.jb=function(){if(this.Na){u(this.O,"gsc-adBlockInvisible");u(this.S,"gsc-adBlockVerticalInvisible");this.Ba&&Bb(this.aa,"gsc-thinWrapper")}};M.Wd=function(){if(this.Na){this.tc>0?Ab(this.O,"gsc-adBlock"):Ab(this.O,"gsc-adBlockInvisible");if(this.Ba)if(this.sc>0){u(this.S,"gsc-adBlockVertical");Y(this.aa,"gsc-thinWrapper")}else{u(this.S,"gsc-adBlockVerticalInvisible");$(this.aa,"gsc-thinWrapper")}}};M.submit=function(){this[D][Ia][z]?this[L]():this.bc();return g};O(p[H].b[A],"submit",p[H].b[A].submit);
p[H].b[A].Db=function(){if(this.$&&!this.cg&&(!this.fb||this.Md))u(this.$,"gsc-tabsArea")};
ra(p[H].b[A],function(c){var d;if(c){d=c;this[D].onfocus&&this[D].onfocus();na(this[D],d)}else d=this[D][Ia];this.zb=b;if(d[z]){this.cb=g;u(this.za,"gsc-resultsbox-visible");this.Db();var e=this.Na;if(e&&this.pf&&this.W==p[H].b.ra)e=g;var f=this.uf();if(f==ca&&!this.Oa&&!this.hb)e=g;if(e){var h=this.Ib==p[H].a.ta;if(this.Fa==ca)this.Fa=h?2:1;var k="w"+this.Fa;if(this.Ba){if(this.xa==ca)this.xa=h?4:2;k=k+"n"+this.xa}var n;if(this.hb){var m="w"+this.Fa;n=p[K].GoogleApisBase+"/services/ads/afs?q="+i(d)+
"&hl="+i(p[H][ab])+"&ad="+i(m)+"&source="+this.d[0].f.rb}else n="http://www.google.com/"+(f?"cse":"search")+"?output=js&num=0&ie=utf8&oe=utf8&q="+i(d)+"&hl="+i(p[H][ab])+"&ad="+i(k)+"&js=uds";if(f)n+="&cx="+f;if(this.Oa)n+="&client="+i(this.Oa);if(this.Nd)n+="&channel="+i(this.Nd);if(this.$b)n+="&adtest=on";if(this.Od)n+="&ip="+i(this.Od);if(this.Pd)n+="&adsafe="+i(this.Pd);if(this.Qd)n+="&useragent="+i(this.Qd);if(this.hb){ta(this.za[G],"hidden");this.zb=new p[H].$a;this.jb();v(this.O,"");v(this.S,
"");if(jb()||kb())n+="&nocache="+_json_cache_defeater_++;n+="&referer="+l[Ja].host;if(this.Fa>0){if(this.we)n=n[F](/&ad=[^&]*/,"&ad=n1w0");var o=this.$d(g),s=n.substring(0,2000);s=s[F](/%\w?$/,"");o.src=s;this.O[w](o)}if(this.Ba&&this.xa>0){var x=n[F](/&ad=[^&]*/,"&ad="+("n"+this.xa)),y=this.$d(a);s=x.substring(0,2000);s=s[F](/%\w?$/,"");y.src=s;this.S[w](y)}}else{var I=this;l.google_afs_request_done=function(T){I.yf(T)};_json_request_require_prep=g;fb(n,b);_json_request_require_prep=a}}for(var B=
0;B<this.d[z];B++){if(!this.d[B].kb){$(this.d[B].j,"gsc-resultsbox-invisible");Y(this.d[B].j,"gsc-resultsbox-visible")}this.yc&&this.yc(this,this.d[B].f,d);if(this.d[B].f.oa)this.d[B].f.oa=b;this.d[B].f[L](d)}this.zb&&this.zb.start(2000)}});O(p[H].b[A],"execute",p[H].b[A][L]);M=p[H].b[A];M.af=function(c,d){var e=this;return function(f){p[K][Za]("afsq","1");if(d)e.sc=f;else e.tc=f;e.wf(c,d,f);var h=f>0;if(e.$){var k=e.q[e.I].zc;if(e.qb(k))h=g}h&&e.Wd()}};
M.Te=function(c,d){var e=function(f){f=f?f:l.event;var h=0;try{var k=c.contentWindow;if(k.frames&&k.frames[z])h=k.frames[0].name}catch(n){}d(h)};if(jb())ja(c,function(){if(c[Ra]=="loaded"||c[Ra]=="complete"){ja(c,b);e()}});else ia(c,function(){ia(c,b);e()})};
M.Ue=function(c,d){var e=function(f){f=f?f:l.event;if(f.source==c.contentWindow){if(l.detachEvent)l.detachEvent("onmessage",e);else l.removeEventListener&&l.removeEventListener("message",e,g);d(f.data)}};if(l.attachEvent)l.attachEvent("onmessage",e);else l.addEventListener&&l.addEventListener("message",e,g)};
M.$d=function(c){var d=q[J]("iframe");d.name="google_afs_ads_frame";la(d,0);sa(d,0);d.frameBorder=0;d.marginWidth=0;d.marginHeight=0;d.vspace=0;d.hspace=0;d.mg="true";d.scrolling="no";ta(d[G],"hidden");var e=this.zb.gg(this.af(d,c)),f=l;(f.postMessage?f:f.document.postMessage?f.document:b)?this.Ue(d,e):this.Te(d,e);return d};M.wf=function(c,d,e){la(c,"100%");sa(c,"100%");sa(c[G],d?e*5.65+3+"em":this.we?e*5+(jb()?3:2)+"em":e*3+1+"em");if(e>0)ta(c[G],"visible")};
M.uf=function(){for(var c=0;c<this.d[z];c++){var d=this.d[c].f;if(d.z=="web")if(d.J!=p[H].g.ea)if(d.J==p[H].g.db)return d.m}return b};
M.yf=function(c){l.google_afs_request_done=b;if(this.O){p[K][Za]("afsq","1");v(this.O,"");v(this.S,"");this.tc=this.sc=0;if(!c||c[z]<1)this.jb();else{if(!this.$)for(var d=0;d<this.d[z];d++){var e=this.d[d].f;if(this.qb(e)){this.jb();return}}u(this.O,"gsc-adBlock");var f=g,h=q[J]("h2"),k="";if(this.$b)k="*DEBUG* ";k+=P["ads-by-google"];v(h,k);S(this.O,h);var n=c[z];for(d=0;d<n;d++){var m=c[d];if(m[Wa]=="text/wide"){this.tc++;var o=V("gsc-ad"),s=X(m.url,m.line1,p[H].a.ab);S(o,s);var x=q[J]("cite");
v(x,m.visible_url);S(o,x);var y=nb();v(y,m.line2);S(o,y);S(this.O,o)}else if(this.Ba){this.sc++;if(!f){f=a;Y(this.aa,"gsc-thinWrapper");S(this.S,h[Va](a));u(this.S,"gsc-adBlockVertical")}o=V("gsc-ad");s=X(m.url,m.line1,p[H].a.ab);S(o,s);y=nb();v(y,m.line2+"<br/>"+m.line3);S(o,y);x=q[J]("cite");v(x,m.visible_url);S(o,x);S(this.S,o)}}this.Ba&&!f&&Bb(this.aa,"gsc-thinWrapper");if(this.$){e=this.q[this.I].zc;this.qb(e)&&this.jb()}this.pb&&this.ne&&this.pb(this,"ads")}}};
M.Af=function(){var c=this[D][Ia];if(c&&c!=""){this.Ua&&l[za](this.Ua);this.Ua=l[Da](R(this,p[H].b[A][L],[b]),this.Nb)}};M.Bf=function(){this.Ua&&l[za](this.Ua);this.Ua=l[Da](R(this,p[H].b[A][L],[b]),this.Nb)};M.pa=function(c){switch(c){case p[H].a.ta:this.Ib=c;break;default:case p[H].a.ba:this.Ib=p[H].a.ba;break}for(var d=0;d<this.d[z];d++)this.d[d].f.pa(c)};O(p[H].b[A],"setResultSetSize",p[H].b[A].pa);p[H].b[A].sb=function(c){this.Ea=c;for(var d=0;d<this.d[z];d++)this.d[d].f.sb(c)};
O(p[H].b[A],"setLinkTarget",p[H].b[A].sb);p[H].b[A].Kb=function(c){for(var d=0;d<this.d[z];d++)this.d[d].u.Kb(c)};O(p[H].b[A],"setNoResultsString",p[H].b[A].Kb);M=p[H].b[A];M.Ef=function(c){c.ic?this.Ha(c,g):this.Ha(c,a)};M.Ha=function(c,d,e){if(d){$(c.Ia,"gsc-twiddle-closed");Y(c.Ia,"gsc-twiddle-opened");c.ic=a;qa(c.Q[G],"block")}else{$(c.Ia,"gsc-twiddle-opened");Y(c.Ia,"gsc-twiddle-closed");c.ic=g;qa(c.Q[G],"none");v(c.ib,e?"(0)":"("+c.f.results[z]+")")}};M.zf=function(c){this.ub(c,g,a);return g};
M.Df=function(c){if(c.f.Ra)c.dc?this.ub(c,g,a):this.ub(c,a,a)};M.ub=function(c,d,e){if(d){if(c.P&&c.f.da){Y(c.P,"gsc-twiddle-opened");$(c.P,"gsc-twiddle-closed");v(c.P,P[Oa]);c.dc=a;qa(c.va[G],"block");c.f.da(c.Sa,a)}}else if(c.P&&c.f.da){$(c.P,"gsc-twiddle-opened");Y(c.P,"gsc-twiddle-closed");v(c.P,P.blank);c.dc=g;c.f.da(c.Sa,g);qa(c.va[G],"none");e&&this[L]()}};M.Cf=function(c,d){if(this.Hb){d.f.rf();this.Hb(c)}};M.Ve=function(){this.cb=a};O(p[H].b[A],"cancelSearch",p[H].b[A].Ve);
p[H].b[A].bc=function(){na(this[D],"");this[D].onblur&&this[D].onblur();u(this.za,"gsc-resultsbox-invisible");this.$&&Ab(this.$,"gsc-tabsAreaInvisible");this.O&&Ab(this.O,"gsc-adBlockInvisible");if(this.S){u(this.S,"gsc-adBlockVerticalInvisible");$(this.aa,"gsc-thinWrapper")}for(var c=0;c<this.d[z];c++){if(!this.d[c].kb){$(this.d[c].j,"gsc-resultsbox-visible");Y(this.d[c].j,"gsc-resultsbox-invisible")}var d=this.d[c];mb(d.Q);d.w=b;this.Ha(d,g,a);this.ub(d,g,g)}};O(p[H].b[A],"clearAllResults",p[H].b[A].bc);
p[H].b[A].U=function(c){if(this.hb&&c==this.d[this.I])ta(this.za[G],"visible");var d,e,f=g,h;if(!this.cb){mb(c.Q);c.w=b;this.Ha(c,g,a);this.ub(c,g,g);c.Ac(p[H].A.Wb);var k=c.f.context,n=this.$&&k;if(this.fb&&!this.Md){if(n){var m=k[va];for(e=0;e<this.q[z];e++){var o=this.q[e];if(o.z==c.f.z){var s=c.f;if(m&&!c.f.Za)v(o.T,m);break}}}this.Md=a;this.Db()}var x=c.f.promotions;if(x&&x[z]>0)for(e=0;e<x[z];e++){var y=x[e];y.html||c.f.Td(y);if(y.html){h=V(c.f.lc());Y(h,"gsc-result");var I=y.html[Va](a);S(h,
I);S(c.Q,h)}}var B=c.f.results;if(c.f.gb&&c.f.completionStatus>=400){B=[];B[ua](c.f.gf())}else if(B[z]==0&&c.u.mb&&c.f.completionStatus==200){B=[];B[ua](c.f.hf(c.u.mb))}for(e=0;e<B[z];e++){d=B[e];d.html||c.f.D(d);if(d.html){f=a;h=V(c.f.lc());Y(h,"gsc-result");c.f.wb&&yb(h,"gsc-result-"+c.f.wb);I=d.html[Va](a);if(d.GsearchResultClass==p[H].c.C){if(c.u.M)if(c.u.M[E]!=c.f.M[E]||c.u.M[bb]!=c.f.M[bb])for(var T=I.getElementsByTagName("img"),Z=0;Z<T[z];Z++)p[H].a.Xa(d.tbWidth,d.tbHeight,c.u.M,T[Z],a)}else if(d.GsearchResultClass==
p[H].s.C)if(c.u.Qb){T=I.getElementsByTagName("img");for(Z=0;Z<T[z];Z++)p[H].a.Xa(d.tbWidth,d.tbHeight,c.u.Qb,T[Z])}S(h,I);if(this.Hb){var Xa=this.qc,ea=U("","gsc-keeper");v(ea,Xa);S(h,ea);pa(ea,R(this,p[H].b[A].Cf,[d,c]))}if(e>=c.f.ie){if(!c.w){c.w=V("gsc-expansionArea");S(c.Q,c.w);if(c.u.X==p[H].b.Ca)qa(c.w[G],"none")}S(c.w,h)}else S(c.Q,h)}}if(!c.w&&c.f[C]){c.w=V("gsc-expansionArea");S(c.Q,c.w)}if(c.w&&c.f.v&&c.f.gwsUrl){h=X(c.f.gwsUrl,P["more-results"]+"&nbsp;&raquo;",c.f.t(),"gsc-trailing-more-results");
if(c.f[C]){var wa=V("gsc-cursor-box"),fa=this.bf(c);wa[w](fa);wa[w](h);S(c.w,wa)}else S(c.w,h)}if(f){v(c.ib,"("+c.f.results[z]+")");c.u.X==p[H].b.Ca||c.u.X==p[H].b.Ka?this.Ha(c,a):this.Ha(c,g);var xa=c.f.be();xa&&S(c.Q,xa)}else{v(c.ib,"(0)");v(c.Q,"");this.Ha(c,g)}c.u.X=c.u.je;this.pb&&this.pb(this,c.f);if(this.fb&&n&&!this.Qe&&k.facets){var sb=this[D][Ia],Ma=k.facets;for(e=0;e<Ma[z];e++){var Na=Ma[e],ub=new p[H].g;ub.qa(s.m,Na.label);ub.vb(Na.anchor);this.La(ub);ub[L](sb)}for(e=0;e<this.d[z];e++)if(!this.q[e]){this.Vd(e);
this.Ud(e);Y(this.q[e].T,"gsc-tabHeader");Y(this.q[e].fa,"gsc-tabData");Y(this.q[e].T,"gsc-tabhInactive");Y(this.q[e].fa,"gsc-tabdInactive")}this.Qe=a}}};O(p[H].b[A],"onSearchComplete",p[H].b[A].U);p[H].b[A].bf=function(c){for(var d=V("gsc-cursor"),e=c.f[C],f=0;f<e.pages[z];f++){var h="gsc-cursor-page";if(f==e.currentPageIndex)h=h+" gsc-cursor-current-page";var k=U(e.pages[f].label,h);pa(k,R(this,p[H].b[A].Hf,[c,f]));d[w](k)}return d};
p[H].b.wd={border:"border",borderColor:"border-color",borderStyle:"border-style",borderWidth:"border-width",borderTop:"border-top",borderTopColor:"border-top-color",borderTopStyle:"border-top-style",borderTopWidth:"border-top-width",borderRight:"border-right",borderRightColor:"border-right-color",borderRightStyle:"border-right-style",borderRightWidth:"border-right-width",borderBottom:"border-bottom",borderBottomColor:"border-bottom-color",borderBottomStyle:"border-bottom-style",borderBottomWidth:"border-bottom-width",
borderLeft:"border-left",borderLeftColor:"border-left-color",borderLeftStyle:"border-left-style",borderLeftWidth:"border-left-width",color:"color",cssFloat:"float",styleFloat:"float",clear:"clear",cursor:"cursor",display:"display",font:"font",fontFamily:"font-family",fontSize:"font-size",fontStyle:"font-style",fontWeight:"font-weight",height:"height",margin:"margin",marginTop:"margin-top",marginRight:"margin-right",marginBottom:"margin-bottom",marginLeft:"margin-left",overflow:"overflow",padding:"padding",
paddingTop:"padding-top",paddingRight:"padding-right",paddingBottom:"padding-bottom",paddingLeft:"padding-left",textAlign:"text-align",textDecoration:"text-decoration",textTransform:"text-transform",verticalAlign:"vertical-align",visibility:"visibility",width:"width"};
p[H].b.fe=function(c,d){if(kb())alert("google.search.SearchControl.inlineCurrentStyle is not supported on Safari");else{var e=a;if(d)e=d;if(e)for(var f=0;f<c.childNodes[z];f++)p[H].b.fe(c.childNodes[f],a);if(c.nodeType==1){var h,k,n=g,m=g;if(l[La]){h=l[La](c,b);n=k=a}else if(c[Ua]){h=c[Ua];k=g;n=a}if(n){for(var o in h)if(p[H].b.wd[o]){var s=p[H].b.wd[o],x=h[o];if(o=="display"&&x=="none"){v(c,"");m=a}if(h[o]!="")k?c[G].setProperty(s,x):c[G][Ta](s,x)}if(m)if(!k)c.outerHTML='<div style="display:none"/>'}}}};
O(p[H].b,"inlineCurrentStyle",p[H].b.fe);p[H].b[A].kf=function(c){var d=c?c:this.j,e=b;if(l[La])e=l[La](d,b);else if(d[Ua])e=d[Ua];else if(q.defaultView[La])e=q.defaultView[La](d,b);return e?da(e[E],10):300};p[H].b[A].tb=function(c,d){this.pb=lb(c,d)};O(p[H].b[A],"setSearchCompleteCallback",p[H].b[A].tb);p[H].b[A].Wf=function(c,d){this.yc=lb(c,d)};O(p[H].b[A],"setSearchStartingCallback",p[H].b[A].Wf);
p[H].b[A].uc=function(c,d){c.Ac(d);var e=g;switch(d){default:case p[H].A.Yb:if(c.w)qa(c.w[G],"none");break;case p[H].A.Xb:if(c.w)qa(c.w[G],"block");if(c.f.Wa!=p[H].a.ba)e=a;c.f.pa(p[H].a.ba);break;case p[H].A.xd:if(c.w)qa(c.w[G],"block");if(c.f.Wa!=p[H].a.ta)e=a;c.f.pa(p[H].a.ta);break}if(e){var f;f=this[D][Ia];if(f[z]){this.cb=g;u(this.za,"gsc-resultsbox-visible");this.Db();if(!c.kb){$(c.j,"gsc-resultsbox-invisible");Y(c.j,"gsc-resultsbox-visible")}c.u.X=p[H].b.Ka;c.f[L](f)}}};
p[H].b[A].Hf=function(c,d){this.cb=g;u(this.za,"gsc-resultsbox-visible");this.Db();if(!c.kb){$(c.j,"gsc-resultsbox-invisible");Y(c.j,"gsc-resultsbox-visible")}c.u.X=p[H].b.Ka;c.f.de(d)};
p[H].L=function(c,d,e){var f=vb("gsc-search-box");f.acceptCharset="utf-8";var h=b,k=P["search-uc"],n=P[H];if(e){if(e.buttonText)n=k=e.buttonText;if(e.clickableBrandingUrl){var m="http://www.google.com";if(typeof e.clickableBrandingUrl=="string"&&e.clickableBrandingUrl[Qa](/^http:\/\/[a-z]*\.google\.com/))m=e.clickableBrandingUrl;h=tb(m,b,"_BLANK");u(h,"gsc-branding-clickable")}}this.Jb=wb(k,"gsc-search-button");t(this.Jb,n);var o;if(c){o="gsc-branding-img";this.cc=U(P.blank,"gsc-clear-button");t(this.cc,
P["clear-results"])}else o="gsc-branding-img-noclear";ka(this,xb(b,"gsc-input",b));this[D].name="search";t(this[D],n);var s=ob(b,b,"gsc-search-box");S(f,s);var x=pb(s,0);this.ge=W(x,"gsc-input");var y=W(x,"gsc-search-button");if(c){var I=W(x,"gsc-clear-button");S(I,this.cc)}S(this.ge,this[D]);S(y,this.Jb);var B=ob(b,b,"gsc-branding");S(f,B);x=pb(B,0);this.userDefinedCell=W(x,"gsc-branding-user-defined");var T=W(x,"gsc-branding-text"),Z=W(x,o),Xa=U(P["powered-by"],"gsc-branding-text"),ea,wa=p[K][$a]+
"/css/small-logo.png",fa;if(jb()){fa=V(o);fa[G].filter='progid:DXImageTransform.Microsoft.AlphaImageLoader(src="'+wa+'")';la(fa[G],"51px");sa(fa[G],"15px")}else fa=rb(wa,b,b,o);ea=fa;S(T,Xa);if(h){S(h,ea);S(Z,h)}else S(Z,ea);this.me=f;mb(d);S(d,this.me)};N("google.search.SearchForm",p[H].L);p[H].L[A].se=function(c,d){this.ve=R(this,this.bg,[this]);this.Lb=R(c,d,[this]);this.me.onsubmit=this.ve;pa(this.Jb,this.ve)};O(p[H].L[A],"setOnSubmitCallback",p[H].L[A].se);
p[H].L[A].re=function(c,d){pa(this.cc,R(c,d,[this]))};O(p[H].L[A],"setOnClearCallback",p[H].L[A].re);p[H].L[A].bg=function(){var c=this.ge.offsetWidth,d=this[D][Ia];this.Lb&&this.Lb();if(jb()){var e=this,f;f=d[z]*8>=c?c-6:"99%";l[Da](function(){la(e[D][G],f)},1)}return g};ra(p[H].L[A],function(c){if(c)na(this[D],c);this.Lb&&this.Lb()});O(p[H].L[A],"execute",p[H].L[A][L]);
p[H].L[A].qf=function(){var c=this[D],d=function(){if(c[Ia]=="")c[G].background="#FFFFFF url(http://www.google.com/coop/intl/"+p[H][ab]+"/images/google_custom_search_watermark.gif) left no-repeat"},e=function(){c[G].background="#FFFFFF"};c.onblur=d;c.onfocus=e;d()};p[H].$a=function(){this.vc=0;this.Zd=g;this.nb=[]};p[H].$a[A].gg=function(c){this.vc++;var d=this;return function(){for(var e=[],f=0;f<arguments[z];++f)e[ua](arguments[f]);if(d.Zd)this.Xd(c,e);else{d.nb[ua]([c,e]);d.vc--;d.vc==0&&d.Yd()}}};
p[H].$a[A].Yd=function(){for(var c=0;c<this.nb[z];c++)this.Xd(this.nb[c][0],this.nb[c][1]);this.nb=[];this.Zd=a};p[H].$a[A].Xd=function(c,d){l[Da](function(){c[Ya](b,d)},0)};p[H].$a[A].start=function(c){l[Da](R(this,this.Yd,[]),c)};p[H].p=function(c){p[H].b[Pa](this);this.fb=a;this.pa(p[H].a.ta);this.eb("",{iframes:a});this.Bb=new p[H].g;if(c==ca){c={crefUrl:"http://www.google.com/coop/tools/autocse?referer="+l[Ja]};this.hg=a}this.Bb.qa(c);this.Bb.Mb=P.cse;this.La(this.Bb)};N("google.search.CustomSearchControl",p[H].p);eb(p[H].p,p[H].b);p[H].p[A].Eb=function(c,d){var e=d;e||(e=new p[H].R);e.pe(p[H].b.Ja);if(this.hg&&this.d[z]==1)this.cg=a;p[H].b[A].Eb[Pa](this,c,e);u(this.j,"gsc-control-cse")};O(p[H].p[A],"draw",p[H].p[A].Eb);
ra(p[H].p[A],function(c){var d=this.j.offsetWidth;$(this.aa,"gsc-thinWrapper");if(d<p[H].p.He)this.Na=g;else d<p[H].p.Je?this.eb(this.Oa,{useNarrowTopAd:a,includeVerticalAds:g}):this.eb(this.Oa,{useNarrowTopAd:g,includeVerticalAds:d>p[H].p.Ie});p[H].b[A][L][Pa](this,c)});O(p[H].p[A],"execute",p[H].p[A][L]);p[H].p[A].vb=function(c){this.Bb.vb(c)};O(p[H].p[A],"setUserDefinedLabel",p[H].p[A].vb);p[H].p[A].La=function(c,d){p[H].b[A].La[Pa](this,c,d);c.rb="gcsc"};O(p[H].p[A],"addSearcher",p[H].p[A].La);
p[H].p[A].df=function(){p[H].b[A].eb("",{numTopAds:0,numSideAds:0});this.Oa=b;this.ne=g};O(p[H].p[A],"disableAds",p[H].p[A].df);p[H].p.xe="";O(p[H].p,"AUTO_PUBID",p[H].p.xe);p[H].p.He=250;p[H].p.Je=500;p[H].p.Ie=800;p[H].s=function(){p[H].a[Pa](this);this.z="video";this.Aa="/GvideoSearch";this.ma="http://video.google.com/videosearch";this.N=g;this.Ra=a;this.da=lb(this,this.na);this.Qa="gsc-videoConfig";this.k=b};N("google.search.VideoSearch",p[H].s);eb(p[H].s,p[H].a);p[H].s.C="GvideoSearch";O(p[H].s,"RESULT_CLASS",p[H].s.C);p[H].s.o=[];p[H].s.H=function(c,d,e,f,h){var k=0;if(c)k=da(c,10);var n=p[H].s.o[k];p[H].s.o[k]=b;n.U(d,e,f,h)};O(p[H].s,"RawCompletion",p[H].s.H);
p[H].s[A].ga=function(c,d,e,f){var h;h=e==b?p[H].a.ia(p[H].s.o,this):e;var k;k=d==b?"google.search.VideoSearch.RawCompletion":d;var n=this.ya(k,h,f);if(c){var m,o=c;if(this.G)o=o+" "+this.G;m="&q="+i(o);if(this.N)m=m+"&scoring=d";n=n+m;this.v=m;if(f&&f!=0)this.v=this.v+"&start="+f}return n};
p[H].s[A].D=function(c){c.html&&delete c.html;var d=V(this.ha());Y(d,"gs-result");var e=V("gs-image-box"),f=V("gs-text-box"),h=ob(),k=pb(h,0),n=W(k,"gs-image-box"),m=W(k,"gs-text-box");S(n,e);S(m,f);S(d,h);var o=p[H].a.Xa(c.tbWidth,c.tbHeight,this.M),s=rb(c.tbUrl,o[E],o[bb],"gs-image"),x=tb(c.url,b,this.t(),"gs-image");u(x,"gs-image");S(x,s);S(e,x);var y;y=X(c.url,c[va],this.t(),"gs-title");S(f,y);var I=U(c[Ga],"gs-snippet");if(jb())sa(I[G],"2.6em");S(f,I);y=U(this.Ta(new Date(c.published)),"gs-publishedDate");
S(f,y);y=X("http://"+c.publisher,c.publisher,this.t(),"gs-publisher");S(f,y);c.html=d;this.ua(c.html)};O(p[H].s[A],"createResultHtml",p[H].s[A].D);
p[H].s.cf=function(c,d){var e=b;if(c.playUrl&&c.playUrl!=""){var f=c.playUrl,h="gsc-video-player";if(d)h=d;if(gb("opera")){var k=q[J]("object");u(k,h);k[Ta]("type","application/x-shockwave-flash");k[Ta]("data",f);e=V(d);e[w](k)}else{k=q[J]("embed");u(k,h);k[Ta]("type","application/x-shockwave-flash");k[Ta]("src",f);if(c.videoType)c.videoType=="Google"?k[Ta]("bgcolor","#000000"):k[Ta]("wmode","transparent");else k[Ta]("bgcolor","#000000");e=V(d);e[w](k)}}return e};O(p[H].s,"createPlayer",p[H].s.cf);
p[H].s[A].K=function(c){this.N=c==p[H].a.ka?a:c==p[H].a.la?g:g};O(p[H].s[A],"setResultOrder",p[H].s[A].K);p[H].s[A].na=function(c,d){if(d)if(this.k==b){var e=V("gsc-configSetting");this.k=zb(b,"0",this.N,"gsc-configSettingCheckbox");S(e,this.k);S(e,U(P["sort-by-date"],"gsc-configSettingCheckboxLabel"));var f=V("gsc-configSettingSubmit");S(f,wb(P[Oa],"gsc-configSettingSubmit"));S(e,f);S(c,e);this.k[Sa]()}else{ma(this.k,this.N);this.k[Sa]()}else if(this.k)this.k[Ca]?this.K(p[H].a.ka):this.K(p[H].a.la)};p[H].g=function(){p[H].a[Pa](this);this.z="web";this.Aa="/GwebSearch";this.ma="http://www.google.com/search";this.m=b;this.J=p[H].g.ea;this.h=this.Ga=this.wa=this.hc=this.Da=b};N("google.search.WebSearch",p[H].g);eb(p[H].g,p[H].a);p[H].g.C="GwebSearch";O(p[H].g,"RESULT_CLASS",p[H].g.C);p[H].g.db="cx";O(p[H].g,"cxRestriction_CX",p[H].g.db);p[H].g.Cb="cref";O(p[H].g,"cxRestriction_CREF",p[H].g.Cb);p[H].g.ea="none";O(p[H].g,"cxRestriction_NONE",p[H].g.ea);p[H].g.o=[];
p[H].g.H=function(c,d,e,f,h){var k=0;if(c)k=da(c,10);var n=p[H].g.o[k];p[H].g.o[k]=b;n.U(d,e,f,h)};O(p[H].g,"RawCompletion",p[H].g.H);
p[H].g[A].ga=function(c,d,e,f){var h;h=e==b?p[H].a.ia(p[H].g.o,this):e;var k;k=d==b?"google.search.WebSearch.RawCompletion":d;var n=this.ya(k,h,f);if(c){var m,o=c;if(this.G)o=o+" "+this.G;if(this.m&&this.J!=p[H].g.ea&&this.hc){var s=this.hc,x=o;if(this.Da!=b)x=o+" more:"+this.Da;s=s[F](/__HL__/,p[H][ab]);this.wa=s=s[F](/__QUERY__/,i(x))}if(this.m&&this.J==p[H].g.ea)o=o+" site:"+this.m;m="";if(this.m&&this.J!=p[H].g.ea){if(this.J==p[H].g.db)m=m+"&cx="+this.m;else if(this.J==p[H].g.Cb)m=m+"&cref="+
i(this.m);if(this.Da!=b)o=o+" more:"+this.Da}m=m+"&q="+i(o);if(this.Ga)m=m+"&safe="+this.Ga;if(this.h)m=m+this.h;n=n+m;this.v=m;if(f&&f!=0)this.v=this.v+"&start="+f}return n};
p[H].g[A].Td=function(c){c.html&&delete c.html;var d=V("gs-promotion");Y(d,"gs-result");var e=X(c.url,c[va],this.t(),"gs-title");S(d,e);var f=ob(0,0),h=pb(f,0),k;S(d,f);if(c.image){var n=c.image;e=rb(n.url,n[E],n[bb],"gs-promotion-image");k=qb("gs-promotion-image-td");S(k,e);S(h,k)}if(c.bodyLines){k=qb();var m=V();S(h,k);S(k,m);for(var o=c.bodyLines,s=0;s<o[z];s++){var x=o[s],y=x[va],I=x.url,B=x.visibleUrl;e=V();if(I&&B){var T=tb(I,B,this.t(),"gs-title");S(e,T)}y&&S(e,q.createTextNode(y?y:""));S(m,
e)}}e=U(c.visibleUrl,"gs-visibleUrl");S(m,e);Y(e,"gs-visibleUrl-short");c.html=d};O(p[H].g[A],"createPromotionHtml",p[H].g[A].Td);
p[H].g[A].D=function(c){c.html&&delete c.html;var d=V(this.ha());Y(d,"gs-result");var e;e=X(c.unescapedUrl,c[va],this.t(),"gs-title");S(d,e);e=U(c[Ga],"gs-snippet");S(d,e);e=U(c.visibleUrl,"gs-visibleUrl");S(d,e);Y(e,"gs-visibleUrl-short");var f=c.unescapedUrl[Ka](c.visibleUrl),h=c.visibleUrl;if(f!=-1&&f!=0)h=c.unescapedUrl.substring(f);e=U(h,"gs-visibleUrl");Y(e,"gs-visibleUrl-long");S(d,e);c.html=d;this.ua(c.html)};O(p[H].g[A],"createResultHtml",p[H].g[A].D);
p[H].g[A].qa=function(c,d,e){this.gb=this.wa=b;var f=g;if(c==b||typeof c=="string"&&c==""){f=g;this.m=b;this.J=p[H].g.ea;this.gb=this.Da=b}else if(typeof c=="string")if(f=c[Qa](/(^partner-pub-\d*:.*)|(^\d{21}:.*)/)){this.m=c;this.J=p[H].g.db}else{this.m=c;this.J=p[H].g.ea}else if(c.siteUrl){f=g;this.m=c.siteUrl}else if(c.cseId){f=a;this.m=c.cseId;this.J=p[H].g.db}else if(c.crefUrl){f=a;this.m=c.crefUrl;this.J=p[H].g.Cb;this.gb=P["linked-cse-error-results"]}else{f=g;this.m=b;this.J=p[H].g.ea;this.Da=
b}if(f){if(d)this.Da=d;if(e)if(e[Qa](/__HL__/)&&e[Qa](/__QUERY__/))this.hc=e;if(this.J==p[H].g.Cb)if(!this.m[Qa](/^http:\/\/www\.google\.com\/coop\/tools\/autocse\?referer=/))(new Image).src="http://www.google.com/cse/tools/ping?cref="+i(this.m)+"&nocache="+Number(new Date)}};O(p[H].g[A],"setSiteRestriction",p[H].g[A].qa);
p[H].g[A].V=function(c,d){if(c==p[H].a.Sb)this.Ga=d?d==p[H].a.Vb||d==p[H].a.Ub||d==p[H].a.Tb?d:b:b;if(c==p[H].a.Rb)if(d)for(var e in d){var f=d[e];if(e=="lr"||e=="usg"||e=="filter"){if(this.h==b)this.h="&";else this.h+="&";this.h+=e+"="+i(f)}}else this.h=b};O(p[H].g[A],"setRestriction",p[H].g[A].V);if(!p[H].NoOldNames){j("GwebSearch",p[H].g);j("GbookSearch",p[H].l);j("GblogSearch",p[H].r);j("GvideoSearch",p[H].s);j("GnewsSearch",p[H].n);j("GlocalSearch",p[H].e);j("GimageSearch",p[H].c);j("GpatentSearch",p[H].i);j("GSearch",p[H].a);j("GSearchControl",p[H].b);j("GSearchForm",p[H].L);j("GsearcherOptions",p[H].B);j("GdrawOptions",p[H].R)};
google.loader.loaded({"module":"search","version":"1.0","components":["default"]});
google.loader.eval.search = function() {eval(arguments[0])}})()