######################################################################
# Automatically generated by qmake (2.01a) ? ?? 6 10:38:59 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += hello.cpp
