(function(){
var f=true,h=null,j=false,k=navigator,aa=undefined,ba=encodeURIComponent,l=parseInt,m=window,n=document,p=Math;function ca(a,b){return a.toString=b}
var q="push",s="toString",t="valueOf",u="length",da="plugins",v="prototype",ea="round",w="slice",x="replace",y="document",z="split",fa="cookie",ga="charAt",A="userAgent",C="screen",D="indexOf",ha="domain",E="write",F="call",ia="random",G="getParameter",ja="referrer",H="substring",ka="apply",la="contentWindow",J="getTime",K="join",ma="toLowerCase",na=this,oa=function(a,b,c){var d=a[z]("."),e=c||na;!(d[0]in e)&&e.execScript&&e.execScript("var "+d[0]);for(var g;d[u]&&(g=d.shift());)if(!d[u]&&b!==aa)e[g]=
b;else e=e[g]?e[g]:(e[g]={})};p.floor(p[ia]()*2147483648)[s](36);var pa=function(a,b){var c=a.Y;if(arguments[u]>2){var d=Array[v][w][F](arguments,2);c&&d.unshift[ka](d,c);c=d}b=a.$||b;a=a.Z||a;var e,g=b||na;e=c?function(){var i=Array[v][w][F](arguments);i.unshift[ka](i,c);return a[ka](g,i)}:function(){return a[ka](g,arguments)};e.Y=c;e.$=b;e.Z=a;return e},L=function(a,b,c){oa(a,b,c)},qa=function(a,b){function c(){}c.prototype=b[v];a.la=b[v];a.prototype=new c};function ra(a,b){var c=parseFloat(a);return isNaN(c)||c>1||c<0?b:c}function sa(a,b){if(a=="true")return f;if(a=="false")return j;return b}function ta(a,b){var c=/^([\w-]+\.)+[\w-]{2,}(\:[0-9]+)?$/;return c.test(a)?a:b};var ua="pagead2.googlesyndication.com",va="googleads.g.doubleclick.net",wa="pubads.g.doubleclick.net",xa="securepubads.g.doubleclick.net",ya="partner.googleadservices.com",za=ta("pagead2.googlesyndication.com",ua);ta("googleads.g.doubleclick.net",va);ta("pagead2.googlesyndication.com",ua);var Aa=ta("pubads.g.doubleclick.net",wa),Ba=ta("partner.googleadservices.com",ya),Ca=ta("securepubads.g.doubleclick.net",xa);function M(a){return typeof ba=="function"?ba(a):escape(a)}function Da(a){if(a in Ea)return Ea[a];return Ea[a]=k[A][ma]()[D](a)!=-1}var Ea={};function Fa(){return Da("msie")&&!m.opera}
function Ga(){if(k[da]&&k.mimeTypes[u]){var a=k[da]["Shockwave Flash"];if(a&&a.description)return a.description[x](/([a-zA-Z]|\s)+/,"")[x](/(\s)+r/,".")}else if(k[A]&&k[A][D]("Windows CE")>=0){for(var b=3,c=1;c;)try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+(b+1));b++}catch(d){c=h}return b[s]()}else if(Fa()){c=h;try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7")}catch(e){b=0;try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");b=6;c.AllowScriptAccess="always"}catch(g){if(b==
6)return b[s]()}try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(i){}}if(c){b=c.GetVariable("$version")[z](" ")[1];return b[x](/,/g,".")}}return"0"};var Ha={google_ad_channel:"channel",google_ad_host:"host",google_ad_host_channel:"h_ch",google_ad_host_tier_id:"ht_id",google_ad_section:"region",google_ad_type:"ad_type",google_adtest:"adtest",google_allow_expandable_ads:"ea",google_alternate_ad_url:"alternate_ad_url",google_alternate_color:"alt_color",google_bid:"bid",google_city:"gcs",google_color_bg:"color_bg",google_color_border:"color_border",google_color_line:"color_line",google_color_link:"color_link",google_color_text:"color_text",google_color_url:"color_url",
google_contents:"contents",google_country:"gl",google_cust_age:"cust_age",google_cust_ch:"cust_ch",google_cust_gender:"cust_gender",google_cust_id:"cust_id",google_cust_interests:"cust_interests",google_cust_job:"cust_job",google_cust_l:"cust_l",google_cust_lh:"cust_lh",google_cust_u_url:"cust_u_url",google_disable_video_autoplay:"disable_video_autoplay",google_ed:"ed",google_encoding:"oe",google_feedback:"feedback_link",google_flash_version:"flash",google_font_face:"f",google_font_size:"fs",google_hints:"hints",
google_kw:"kw",google_kw_type:"kw_type",google_language:"hl",google_page_url:"url",google_referrer_url:"ref",google_region:"gr",google_reuse_colors:"reuse_colors",google_safe:"adsafe",google_tag_info:"gut",google_targeting:"targeting",google_ui_features:"ui",google_ui_version:"uiv",google_video_doc_id:"video_doc_id",google_video_product_type:"video_product_type"},Ia={google_ad_client:"client",google_ad_format:"format",google_ad_output:"output",google_ad_callback:"callback",google_ad_height:"h",google_ad_override:"google_ad_override",
google_ad_slot:"slotname",google_ad_width:"w",google_analytics_uacct:"ga_wpids",google_ctr_threshold:"ctr_t",google_image_size:"image_size",google_last_modified_time:"lmt",google_max_num_ads:"num_ads",google_max_radlink_len:"max_radlink_len",google_num_radlinks:"num_radlinks",google_num_radlinks_per_unit:"num_radlinks_per_unit",google_only_ads_with_video:"only_ads_with_video",google_page_location:"loc",google_rl_dest_url:"rl_dest_url",google_rl_filtering:"rl_filtering",google_rl_mode:"rl_mode",google_rt:"rt",
google_skip:"skip"},Ja={google_only_pyv_ads:"pyv",google_with_pyv_ads:"withpyv"};var Ka=n,N=k,O=m;
function La(){var a=Ka[fa],b=p[ea]((new Date)[J]()/1000),c=O.google_analytics_domain_name,d=typeof c=="undefined"?Ma("auto"):Ma(c),e=a[D]("__utma="+d+".")>-1,g=a[D]("__utmb="+d)>-1,i=a[D]("__utmc="+d)>-1,r,o={},B=!!O&&!!O.gaGlobal;if(e){r=a[z]("__utma="+d+".")[1][z](";")[0][z](".");o.sid=g&&i?r[3]+"":B&&O.gaGlobal.sid?O.gaGlobal.sid:b+"";o.vid=r[0]+"."+r[1];o.from_cookie=f}else{o.sid=B&&O.gaGlobal.sid?O.gaGlobal.sid:b+"";o.vid=B&&O.gaGlobal.vid?O.gaGlobal.vid:(p[ea](p[ia]()*2147483647)^Na()&2147483647)+
"."+b;o.from_cookie=j}o.dh=d;o.hid=B&&O.gaGlobal.hid?O.gaGlobal.hid:p[ea](p[ia]()*2147483647);return O.gaGlobal=o}function Na(){var a=Ka[fa]?Ka[fa]:"",b=O.history[u],c,d,e=[N.appName,N.version,N.language?N.language:N.browserLanguage,N.platform,N[A],N.javaEnabled()?1:0][K]("");if(O[C])e+=O[C].width+"x"+O[C].height+O[C].colorDepth;else if(O.java){d=java.awt.Toolkit.getDefaultToolkit().getScreenSize();e+=d[C].width+"x"+d[C].height}e+=a;e+=Ka[ja]?Ka[ja]:"";for(c=e[u];b>0;)e+=b--^c++;return Oa(e)}
function Oa(a){var b=1,c=0,d,e;if(!(a==aa||a=="")){b=0;for(d=a[u]-1;d>=0;d--){e=a.charCodeAt(d);b=(b<<6&268435455)+e+(e<<14);c=b&266338304;b=c!=0?b^c>>21:b}}return b}function Ma(a){if(!a||a==""||a=="none")return 1;if("auto"==a){a=Ka[ha];if("www."==a[H](0,4))a=a[H](4,a[u])}return Oa(a[ma]())};n.URL&&(n.URL[D]("?google_debug")>0||n.URL[D]("&google_debug")>0);function Pa(a,b,c,d){this._value_=a;this._expires_=b;this._path_=c;this._domain_=d;if(!this._path_)this._path_="/";if(this._domain_==h)this._domain_=n[ha]}ca(Pa[v],function(){return"[GA_GoogleCookieInfo: value="+this._value_+", expires="+this._expires_+", path="+this._path_+"]"});function Va(){this.v=Wa(this);this.L=j;if(!this.v)this.L=Xa(this)}Va[v].K="__gads=";Va[v].B="GoogleAdServingTest=";Va[v].setCookieInfo=function(a){this.q=a._cookies_[0];if(this.q!=h){this.v=this.q._value_;Ya(this)}};
var Za=function(a,b){var c=(new Date)[t](),d=new Date;d.setTime(c+b);return d},$a=function(a){var b=15552000000,c=Za(a,b),d="ID=12345:T="+b,e="/",g=n[ha];return new Pa(d,c[t](),e,g)},ab="http://"+Ba+"/gampad/cookie.js?callback=_GA_googleCookieHelper.setCookieInfo",bb=function(a,b){if(!(a.v||!a.L)){var c="script",d=n[ha],e=ab+"&client="+M(b)+"&domain="+M(d);n[E]("<"+c+' src="'+e+'"></'+c+">")}},Xa=function(a){n.cookie=a.B+"Good";var b=cb(a,a.B),c=b=="Good";if(c){var d=Za(a,-1);n.cookie=a.B+"; expires="+
d.toGMTString()}return c},Wa=function(a){var b=cb(a,a.K);return b},cb=function(a,b){var c=n[fa],d=c[D](b),e="";if(d!=-1){var g=d+b[u],i=c[D](";",g);if(i==-1)i=c[u];e=c[H](g,i)}return e},Ya=function(a){if(!(a.q==h))if(a.v){var b=new Date;b.setTime(1000*a.q._expires_);var c=a.q._domain_,d=a.K+a.v+"; expires="+b.toGMTString()+"; path="+a.q._path_+"; domain=."+c;n.cookie=d}};function db(a,b){try{return a.top[y].URL==b.URL}catch(c){}return j};sa("false",j);sa("false",j);sa("false",j);var eb=sa("false",j),fb=m;var gb=function(a){this.X=(this.M=a&&a.GA_jstiming)&&this.M.load};gb[v].tick=function(a,b){this.X.tick(a,b)};gb[v].report=function(a){var b={};b.e=a;this.M.report(this.X,b)};var hb=function(){};qa(hb,gb);hb[v].tick=function(){};hb[v].report=function(){};var kb=function(a,b,c,d){if(c<=4){var e=b+"_"+c;d?a.tick(e,d+"_"+c):a.tick(e)}};var P=fb&&p[ia]()<ra("0.005",0.0010)&&fb.GA_jstiming&&fb.GA_jstiming.load&&fb.location.protocol=="http:"?new gb(fb):new hb(fb);P.tick("js_load");function Q(a){return typeof a=="function"}function lb(a,b){if(typeof a!="string"||a[u]==0)return h;else if(typeof b!="string"||b[u]==0)return h;return mb(R(),a,b)}L("GA_googleAddSlot",lb);function _GA_googleInitializeAdEngine(a){if(!S()){nb(ob(a));pb(S())}}L("_GA_googleInitializeAdEngine",_GA_googleInitializeAdEngine);
function qb(){R().ba=f;_GA_googleInitializeAdEngine(h);var a=S().h;a=="sync"||a=="sync_sra"?S().i():rb(R())}L("GA_googleFetchAds",qb);function sb(){_GA_googleInitializeAdEngine("iframe");bb(m._GA_googleCookieHelper,m.GS_googleGetIdsForAdSenseService())}L("GA_googleUseIframeRendering",sb);function tb(){var a=m.GA_googleEnv[G]("google_ad_impl");a==h&&m.GA_googleEnv.setParameter("google_ad_impl","sync_sra")}L("GA_googleUseSyncSRARendering",tb);
function ub(a){if(!(S()==h))if(!(S().h=="iframe")){if(vb(S()))if(S().J){var b=wb(R(),a);if(b==h)return;else if(!b._enabled_)return}else return;else if(xb(S(),a)!=h&&!S().k)return;S().n(a)}}L("GA_googleFillSlot",ub);function yb(a,b,c,d){a=a||"";b=b||"";c=c||0;d=d||0;if(!(S()==h))if(!(S().h!="iframe")){mb(R(),a,b);var e=new zb(c,d,j,f);Ab(R(),b,e);S().n(b)}}L("GA_googleFillSlotWithSize",yb);function Bb(){Cb(new Db(Ha));nb(h)}L("GA_googleResetAll",Bb);m.google_noFetch=j;
function Eb(){m.google_noFetch=f}L("GA_googleNoFetch",Eb);function Fb(){m.google_delayFetch=f}L("GA_googleDelayFetch",Fb);function zb(a,b,c,d){this._width_=a;this._height_=b;this._expandable_=c;this._enabled_=d}ca(zb[v],function(){return"[GA_GoogleAdSlotAttr: width="+this._width_+", height="+this._height_+", expandable="+this._expandable_+", enabled="+this._enabled_+"]"});
function Gb(a){for(var b={},c=a[z]("?"),d=c[c[u]-1][z]("&"),e=0;e<d[u];e++){var g=d[e][z]("=");if(g[0])try{b[g[0][ma]()]=g[u]>1?m.decodeURIComponent?decodeURIComponent(g[1][x](Hb," ")):unescape(g[1]):""}catch(i){}}return b}function Ib(a){var b=a||n.URL;this.V=Gb(b)}Ib[v].getParameter=function(a){return a==h?h:this.V[a]};Ib[v].setParameter=function(a,b){this.V[a]=b};var Jb=function(a){if(!eb)return a?"http://"+Aa:"http://"+Ba;return"https://"+Ca};
function Kb(a){return a[x](/&/g,"&amp;")[x](/</g,"&lt;")[x](/>/g,"&gt;")[x](/\"/g,"&quot;")}function Lb(){this.D=h;this.W=j;this.ka=(new Date)[t]()}
var Nb=function(a,b){if(!(a.D!=h))if(!a.W){a.D=m.open("","GoogleAdCapture","width=1100, height=1400, status=no, resizable=yes, scrollbars=yes,menubar=yes, toolbar=yes");if(a.D){var c=a.D[y],d=[];d[q]('<html>\n<head>\n<title>Google Ad Capture Window</title>\n<script>function displayTime(id, start){var delta=(new Date()).valueOf() - start;document.getElementById(id).innerHTML=""+delta;}var pageStartTime = (new Date()).valueOf();var slotStartTime = 0;window.onload=function(){displayTime("total", pageStartTime);};<\/script></head>\n<body>\n');d[q]("<p>Google Ad Capture Window</p>");
for(var e in b)Q(b[e])||d[q](Mb(a,e,b[e]));d[q]("<p>Time blocked rendering ads (ms): <label id='blocked'></label>");d[q]("<script>displayTime('blocked', pageStartTime);<\/script>");d[q]("<p>Total Page Load Time (ms): <label id='total'></label>");d[q]("</body>\n</html>");var g=d[K]("\n"),i=m.GA_googleEnv[G]("google_capture_norender")!=h;i?c[E](Kb(g)):c[E](g);c.close()}else a.W=f}},Mb=function(a,b,c){var d="<script>slotStartTime = (new Date()).valueOf();<\/script>",e="<p>Slot "+b+"</p>",g;g=c==h||c._html_==
h?"No ad":c._html_;var i="<p>Slot Time (ms): <label id='"+b+"'></label>",r='<script>displayTime("'+b+'", slotStartTime);<\/script>';return d+e+"\n"+g+"\n"+i+r};function Ob(a){this.d={};this.C=a}var Pb=function(a,b,c,d){if(b){c||(c="");if(b=="google_gl")b="google_country";else if(b=="google_region")b="google_section";if(b in a.C)if((d=typeof d=="undefined"||d)||!a.d[b])a.d[b]=c}},Qb=function(a,b){for(var c in b.d)Q(b.d[c])||a.d[c]||(a.d[c]=b.d[c])};Ob[v].getAttribute=function(a){return this.d[a]};
Ob[v].g=function(){var a=[];for(var b in this.d)if(!Q(this.d[b])){var c=Ha[b]||Ia[b]||Ja[b]||h,d=this.d[b];c&&d&&a[q](c+"="+M(d))}return a[K]("&")};
var Sb=function(a,b,c,d){var e=Rb(a,b,c,d),g=[];e[0]&&e[0][u]>0&&g[q](e[0][K]("&"));e[1]&&e[1][u]>0&&g[q]("sps="+e[1][K]("|"));return g[K]("&")},Rb=function(a,b,c,d){var e=[],g=[],i=b.d;for(var r in d)if(!Q(r)){var o=d[r];if(o){var B="";if(i[r]!=h)B=M(i[r]);var I=[],ib=-1,Qa=-1;for(var Ra in a)if(!Q(a[Ra])){++ib;if(c[Ra]==h)I[q]("");else{var jb=c[Ra].d;if(jb[r]!=h){I[q](M(M(jb[r])));Qa=ib}else I[q]("")}}if(Qa>=0){var tc=M(B),Sa=[];Sa[q](tc);for(var Ta=0;Ta<=Qa;++Ta)Sa[q](I[Ta]);g[q](o+","+Sa[K](","))}else B&&
e[q](o+"="+B)}}var Ua=[];Ua[q](e);Ua[q](g);return Ua};function Tb(a,b){this.I=a;this.s=b;this.Q=0;this.ha=this.N=this.O=j;this.fa=this.ga=this.S=this.ca=h}var Ub=function(a){a.N=f;a.ca=(new Date)[t]()},Vb=function(a){a.S=(new Date)[t]()},Wb=function(a){a.ha=f;a.ga=(new Date)[t]()},Xb=function(a){a.fa=(new Date)[t]()};ca(Tb[v],function(){return"[GA_GoogleAdSlot: pubid="+this.I+", name="+this.s+", loaded="+this.O+", tries="+this.Q+"]"});
function Db(a){this.a={};this.c=[];this.r={};this.C=a;this.U=new Ob(this.C);this.A={};this.ba=j;this.o=h}
var mb=function(a,b,c){var d=new Tb(b,c);return a.a[d.s]=d},Yb=function(a,b){var c=[];for(var d in a.a)if(!Q(a.a[d])){if(b){var e=wb(a,d);if(e==h||!e._enabled_)continue}var g=a.a[d];g.N||c[q](g)}return c},Zb=function(a,b){return Yb(a,b)[u]},$b=function(a){var b=[];for(var c in a.a){var d=a.a[c];Q(d)||d.N&&d.S==h&&b[q](c)}return b},ac=function(a){var b=0;for(var c in a.a)if(!Q(a.a[c])){var d=wb(a,c);d!=h&&d._enabled_&&b++}return b},bc=function(a){for(var b in a.a)if(!Q(a.a[b])){var c=a.a[b];Ub(c)}},
cc=function(a,b){var c=a.a[b];Ub(c)},dc=function(a,b){var c=a.a[b];Vb(c)},ec=function(a,b){var c=a.a[b];Wb(c)},T=function(a,b){var c=a.a[b];Xb(c);kb(P,"ga_render",a.c[u],"ga_srt")},fc=function(a){var b=0;for(var c in a.a)Q(a.a[c])||b++;return b};ca(Db[v],function(){var a="[AdData:",b=[];for(var c in this.a)Q(this.a[c])||b[q](this.a[c][s]());for(var d in this.r)Q(this.r[d])||b[q]("["+d+","+this.r[d]+"]");a+=b[K]();a+="]";return a});
var gc=function(a,b){return a.a[b]},hc=function(a,b,c){if(!(b==h||b[u]==0)){if(c==h||c[u]==0)c="";var d=a.r[b];a.r[b]=d==h?c:d+","+c}};function ic(a,b){hc(R(),a,b)}L("GA_googleAddAttr",ic);var jc=function(a,b,c){Pb(a.U,b,c)};function kc(a,b){jc(R(),a,b)}L("GA_googleAddAdSensePageAttr",kc);var lc=function(a){return a.U},mc=function(a,b,c,d){if(!(b==h||b[u]==0)){if(S()==h||S().h!="iframe"){var e=a.a[b];if(e==h)return}var g=a.A[b];if(g==h)a.A[b]=new Ob(a.C);Pb(a.A[b],c,d)}};
function nc(a,b,c){mc(R(),a,b,c)}L("GA_googleAddAdSenseSlotAttr",nc);var oc=function(a,b){return a.A[b]},pc=function(a){var b=Jb(a.google_new_gam_domain_enabled);return b+"/gampad/slotdata.js?callback=GA_googleSetAdSlotAttributes"},rb=function(a){if(a.o!=h)S().i();else{var b=[];for(var c in a.a)Q(a.a[c])||b[q](c);var d=m.GS_googleGetIdsForAdSenseService(),e=pc(m)+"&client="+escape(d)+"&page_slots="+escape(b[K]());n[E]("<script src = '"+e+"'><\/script>")}};
Db[v].setAdSlotAttributes=function(a){this.o=a;S().J=f;S().i()};function qc(a){R().setAdSlotAttributes(a)}L("GA_googleSetAdSlotAttributes",qc);var Ab=function(a,b,c){if(a.o==h)a.o={};a.o[b]=c;S().J=f},wb=function(a,b){return a.o!=h?a.o[b]:h};function rc(a,b){this.ma=a;this.aa=b}function sc(a,b){this.AdSlotContent=rc;this.AdSlotConent(sc.HTML_TYPE,a);this._html_=b}ca(sc[v],function(){return"[GA_HTMLAdSlotContent expandable="+this.aa+", html="+this._html_+"]"});sc.prototype=new rc(sc.HTML_TYPE,j);
function uc(a,b,c){if(!c||c<0||c>1)c=0;this.ia=p[ia]()<c;this.da=a;this.R=b+"/pagead/gen_204?id="+M(a);this.ea=[]}var U=function(a,b,c){if(b&&b.match(/^\w+$/)&&c)a.R+="&"+b+"="+M(c)},vc=function(a){var b=R();for(var c in b.a){var d=b.a[c];if(!Q(d)&&d.I!=h){U(a,"pub_id",d.I);break}}U(a,"nslots",fc(b)[s]());U(a,"pub_url",n.URL);U(a,"pub_ref",n[ja])},wc=function(a){if(!a.ia||!a.da||!a.R)return j;var b=new Image;b.src=a.R;a.ea[q](b);return f};
function V(a){this.f=h;this.o={};this.p=this.b="";this.k=a;this.l=this.H=this.t=j;this.h="sync";this.ja=Ha;this.u=f;this.J=j;this.P=m.google_new_gam_domain_enabled}
var pb=function(a){a.t=m.GA_googleEnv[G]("google_nofetch")!=h||m.google_noFetch;a.H=m.GA_googleEnv[G]("google_norender")!=h;a.l=m.GA_googleEnv[G]("google_capture")!=h||m.GA_googleEnv[G]("google_capture_norender")!=h;if(a.l)a.H=f;xc(a,m);a.b=a.p;var b=pa(a.T,a);yc(a,m,b)},yc=function(a,b,c){if(b.attachEvent){b.attachEvent("onload",c);return f}if(b.addEventListener){b.addEventListener("load",c,j);return f}return j};V[v].F=function(){this.l&&Nb(m.GA_googleAdCapture,this.f)};
var zc=function(a){if(a.h=="sync_sra"){var b=R(),c=fc(b),d=b.c[u];if(c!=d){a.G=new uc("sra_mismatch",Jb(a.P),ra("0.001",0.0010));U(a.G,"correlator",a.m);U(a.G,"fslots",d[s]());vc(a.G);wc(a.G)}}},Ac=function(a){P.tick("ga_onload");P.report(a.h)},Bc=function(a){var b=$b(R());if(b[u]>0){a.z=new uc("missing_cb",Jb(a.P),ra("0.01",0.0010));U(a.z,"pending",b[K]());U(a.z,"correlator",a.m);U(a.z,"impl",a.h);vc(a.z);wc(a.z)}};
V[v].T=function(){Ac(this);this.F();zc(this);Bc(this)};var xc=function(a){var b=m.GA_googleEnv[G]("google_ad_url");if(b==h||b[u]==0)a.p=Jb(a.P)+"/gampad/ads?";else{if(b[ga](b[u]-1)!="?")b+="?";a.p=b}};V[v].j=function(){};
var xb=function(a,b){return a.f!=h?a.f[b]:h},Cc=function(){var a=k[A],b=a[D]("MSIE ");return b==-1?0:parseFloat(a[H](b+5,a[D](";",b)))},Hb=/\+/g,Dc=function(a,b){b=b[ma]();if(b[H](0,3)!="ca-")b="ca-"+b;return b},X=function(a,b,c){c!=h&&W(a,b,M(c[s]()))},W=function(a,b,c){if(c!=h)a.b+=a.b[ga](a.b[u]-1)!="?"?"&"+b+"="+c:b+"="+c},Ec=function(a,b){for(var c=Yb(R(),a.u),d=[],e=[],g=[],i=c[u],r=0;r<i;r++){var o=c[r];g[q](o.s);if(!(b!=h&&b!=o.s)){d[q](o.s);e[q](Dc(a,o.I))}}X(a,"client",e[0]);if(a.k)g[u]>
0&&X(a,"page_slots",g[K]());else{X(a,"slotname",d[K]());R().c[u]>0&&X(a,"page_slots",R().c[K]())}},Fc=function(a,b,c){if(c!=h){var d=b.lastIndexOf("?"),e=b[D]("google_preview=",d),g=b[D]("&",e);if(g==-1){g=b[u]-1;e-=1}return b[H](0,e)+b[H](g+1,b[u])}return b},Gc=function(a,b,c){if(db(b,c))return c.URL;return c[ja]},Ic=function(a,b,c){if(Hc(a,b,c)!=c.URL)return c[ha];return""},Hc=function(a,b,c){var d=lc(R()).getAttribute("google_page_url");if(d)return d;return Gc(a,b,c)},Jc=function(a,b,c,d){X(a,
"url",Fc(a,Hc(a,m,n),m.GA_googleEnv[G]("google_preview")));X(a,"ref",n[ja]);X(a,"lmt",(Date.parse(n.lastModified)/1000)[s]());W(a,"dt",b[J]());if(n.body){var e=n.body.scrollHeight,g=n.body.clientHeight;g&&e&&X(a,"cc",p[ea](g*100/e)[s]())}var i=m.GA_googleEnv[G]("deb");i!=h&&X(a,"deb",i);var r=m.GA_googleEnv[G]("haonly");r!=h&&X(a,"haonly",r);var o=lc(R());k[A][D]("MSIE ")>0&&Pb(o,"google_encoding",n.charset,j);var B="";if(d)B=Sb(R().a,o,R().A,a.ja);else{var I=oc(R(),c);if(I==h)I=o;else Qb(I,o);B=
I.g()}if(B)a.b+="&"+B},Kc=function(a,b,c){var d=R().r,e=[];for(var g in d)Q(d[g])||e[q](M(g)+"="+M(d[g]));X(a,"cust_params",e[K]("&"));if(b._GA_googleCookieHelper){X(a,"cookie",b._GA_googleCookieHelper.v);b._GA_googleCookieHelper.L&&X(a,"cookie_enabled","1")}b.google_new_gam_domain_checked==1&&b.google_new_gam_domain_enabled!=1&&W(a,"dblk",1);var i=Ic(a,b,c);i&&X(a,"cdm",i)},Lc=function(a){La();var b=m;W(a,"ga_vid",b.gaGlobal.vid);W(a,"ga_sid",b.gaGlobal.sid);W(a,"ga_hid",b.gaGlobal.hid);W(a,"ga_fc",
b.gaGlobal.from_cookie);X(a,"ga_wpids",b.google_analytics_uacct)},Mc=function(a,b,c){var d=b[C],e=k.javaEnabled(),g=-c.getTimezoneOffset();if(d){W(a,"u_h",d.height);W(a,"u_w",d.width);W(a,"u_ah",d.availHeight);W(a,"u_aw",d.availWidth);W(a,"u_cd",d.colorDepth)}W(a,"u_tz",g);W(a,"u_his",m.history[u]);W(a,"u_java",e[s]());k[da]&&W(a,"u_nplug",k[da][u]);k.mimeTypes&&W(a,"u_nmime",k.mimeTypes[u]);W(a,"flash",Ga())};
V[v].g=function(a){this.j();var b=new Date;Ec(this,a);Kc(this,m,n);m.GA_googleEnv[G]("google_preview")!=h&&W(this,"gct",m.GA_googleEnv[G]("google_preview"));Lc(this);Jc(this,b,a,this.k);Mc(this,m,b);this.b=this.b[H](0,2000);return this.b=this.b[x](/%\w?$/,"")};
var Nc="google_ads_iframe_"[u],vb=function(a){return a.u},Oc=function(a,b){var c=b.getAttribute("id"),d=c.substr(Nc,c[u]-Nc);return d},Pc=function(a,b,c,d,e,g,i){var r="google_ads_iframe_"+b,o=[];if(i){var B="google_ads_div_"+b;o[q]("<div id=",B,">")}o[q]("<iframe id=",r," name=",r,' width="',e,'" height="',g,'" vspace="0" hspace="0" allowtransparency="true" ',"scrolling=",a.l?'"auto"':'"no"',' marginwidth="0" marginheight="0" frameborder="0" style="border:0px;"',' src="',Kb(c),'"');d!=h&&o[q](' onload="',
d,'"');o[q]("></iframe>");i&&o[q]("</div>");var I=o[K]("");n[E](I)};
V[v].createDOMIframe=function(a,b){var c=xb(this,b),d=c._width_,e=c._height_,g=c._html_,i=n.createElement("iframe");i.id="google_ads_iframe_"+b;i.name="google_ads_iframe_"+b;i.width=d;i.height=e;i.vspace=0;i.hspace=0;i.allowTransparency="true";i.scrolling="no";i.marginWidth=0;i.marginHeight=0;i.frameBorder=0;i.style.border=0;var r=n.getElementById(a);r.appendChild(i);if(this.l){i[la][y][E](Kb(g));i.scrolling="auto"}else i[la][y][E](g);i[la][y].close();T(R(),b)};
function Qc(a,b){S().createDOMIframe(a,b)}L("GA_googleCreateDomIframe",Qc);
var Rc=function(){var a=[],b=n.getElementsByTagName("base");if(b)for(var c=0,d=b[u];c<d;++c){var e=b[c],g=e.getAttribute("target");if(g){a[q]({baseElement:e,originalTagValue:g});e.removeAttribute("target")}}return a},Sc=function(a){if(a)for(var b=0,c=a[u];b<c;++b){var d=a[b];d.baseElement.setAttribute("target",d.originalTagValue)}},Tc=function(a){var b="http://"+za+"/pagead/inject_object_div.js";if(l(Cc(),10)>6)return j;if(a[D](b)<0)return j;return f},Uc=function(a,b,c){if(a.l)c=Kb(c);var d=Rc();
m.frames[b.name].contents=c;b.src=Tc(c)?'javascript:document.write(window["contents"]);document.close();':'javascript:window["contents"]';Sc(d)},Vc=function(a,b,c){var d=Oc(a,b),e=b[la]?b[la][y]:b.contentDocument;if(e==h)if(n.implementation&&n.implementation.createDocument)e=n.implementation.createDocument("",d,h);else if(typeof ActiveXObject!="undefined")e=new ActiveXObject("Msxml.DOMDocument");else return;e.open("text/html","replace");a.l?e[E](Kb(c)):e[E](c);e.close()},Wc=function(a,b){var c=Oc(a,
b),d=gc(R(),c);if(!d.O){d.O=f;var e=xb(a,c),g=b.parentNode;if(e==h||e._html_==h){g.removeChild(b);T(R(),c)}else if(e._expandable_){g.innerHTML=e._html_;T(R(),c)}else{e._is_3pas_?Uc(a,b,e._html_):Vc(a,b,e._html_);T(R(),c)}}},Xc=function(a,b){var c="google_ads_div_"+b,d="<div id="+c+">",e=xb(a,b);if(!(e==h)){d+=e._html_;d+="\n</div>\n";n[E](d);T(R(),b)}},Yc=function(a,b){var c="google_ads_div_"+b,d="<div id="+c+">";d+="\n</div>\n";n[E](d);return c},Zc=function(a){if(!a.u)return f;if(Zb(R(),a.u)>0)return f;
else if(ac(R())==0)return j};V[v].setAdContentsBySlot=function(a){kb(P,"ga_srt",R().c[u],"_ga_start");if(this.f==h){this.f=a;for(var b in a)Q(a[b])||dc(R(),b)}else for(b in a)if(!Q(a[b])){this.f[b]=a[b];dc(R(),b)}var c=j;for(b in a)if(!Q(a[b])){var d=a[b];if(c){d._cookies_=[$a(m._GA_googleCookieHelper)];c=j}d!=h&&d._cookies_!=h&&m._GA_googleCookieHelper.setCookieInfo(d)}};function $c(a){S().setAdContentsBySlot(a)}L("GA_googleSetAdContentsBySlot",$c);
function Y(a){V[F](this,a);this.u=j;this.m=(new Date)[J]();this.h=a?"sync_sra":"sync"}qa(Y,V);Y[v].j=function(){this.b=this.p;X(this,"correlator",this.m[s]());W(this,"output","json_html");W(this,"callback","GA_googleSetAdContentsBySlotForSync");this.k?W(this,"impl","ss"):W(this,"impl","s");var a=0,b=f;for(var c in this.f)if(!Q(this.f[c])){var d=this.f[c];if(d._is_afc_==aa){b=j;break}else a=2*a+(d._is_afc_?1:0)}b&&W(this,"prev_afc",a);this.k||ad(this,R().c,this.f)};
var ad=function(a,b,c){if(b&&c){for(var d=[],e=[],g=b[u]-1,i=0;i<g;i++){var r=b[i],o=c[r];if(o&&o._cids_&&o._a2ids_){d[q](o._cids_[0]);e[q](o._a2ids_[0])}else{d[q]("");e[q]("")}}if(d[u]>0){var B=d[K](","),I=e[K](",");X(a,"a2ids",I);X(a,"cids",B)}}},bd=function(a,b){var c=R().a,d=c[b];if(!(d==h))if(!a.t){a.g(d.s);cc(R(),b);n[E]("<script src = '"+a.b+"'><\/script>")}};
Y[v].setAdContentsBySlotForSync=function(a){this.setAdContentsBySlot(a);if(this.k)if(R().c[u]==1){var b=R().c[0];cd(this,b);return}for(var c in a)Q(a[c])||cd(this,c)};function dd(a){S().setAdContentsBySlotForSync(a)}L("GA_googleSetAdContentsBySlotForSync",dd);Y[v].i=function(){Zc(this)};var ed=function(a){a.g(h);n[E]("<script src = '"+a.b+"'><\/script>");bc(R())};Y[v].n=function(a){R().c[q](a);kb(P,"_ga_start",R().c[u]);if(this.k)R().c[u]==1?ed(this):cd(this,a);else bd(this,a)};
var fd=function(a,b,c){if(b.google_js_backfill){var d="script";c[E]("<"+d+' src="http://pagead2.googlesyndication.com/pagead/show_ads.js"></'+d+">")}},cd=function(a,b){gd(a,m,n,b)},gd=function(a,b,c,d){var e=gc(R(),d);if(!(e==h)){var g=xb(a,d);ec(R(),d);if(g==h||g._empty_){fd(a,b,c,d);T(R(),d)}else if(a.H&&!a.l)T(R(),d);else if(g._snippet_&&!g._is_afc_&&!a.l)Xc(a,d);else if(k[A][D]("MSIE ")>0){var i="GA_googleSyncAdSlotLoaded(this);";Pc(a,d,"about:blank",i,g._width_,g._height_,f)}else{var r=Yc(a,
d);c[E]("<script>GA_googleCreateDomIframe('"+r+"' ,'"+d+"');<\/script>")}}};Y[v].syncAdSlotLoaded=function(a){var b=Oc(this,a);gc(R(),b);Wc(this,a)};function hd(a){S().syncAdSlotLoaded(a)}L("GA_googleSyncAdSlotLoaded",hd);function Z(a){V[F](this,a);this.m=(new Date)[J]();this.h="async"}qa(Z,V);Z[v].j=function(){this.b=this.p;id(this);X(this,"correlator",this.m[s]());W(this,"output","json_html");W(this,"callback","GA_googleSetAdContentsBySlot");W(this,"impl","a")};
var id=function(a){a.delay=500;var b=m.GA_googleEnv[G]("google_async_delay");if(b!=h)a.delay=1000*b};Z[v].i=function(){if(Zc(this))this.t||m.setTimeout("GA_googleReallyFetchAds();",this.INITIAL_ASYNC_DELAY)};
Z[v].reallyFetchAds=function(){if(!(Zb(R(),this.u)==0)){var a=n.getElementsByTagName("head")[0];if(this.k){var b=n.createElement("script");b.src=this.g(h);a.appendChild(b);bc(R())}else{var c=R().a;for(var d in c)if(!Q(c[d])){b=n.createElement("script");b.src=this.g(d);a.appendChild(b);cc(R(),d)}}}};function jd(){S().reallyFetchAds()}L("GA_googleReallyFetchAds",jd);
Z[v].n=function(a){var b=gc(R(),a);if(!(b==h)){R().c[q](a);var c="GA_googleAsyncAdSlotLoaded(this);",d=wb(R(),a);Pc(this,a,"about:blank",c,d._width_,d._height_,f)}};Z[v].asyncAdSlotLoaded=function(a){var b=Oc(this,a);gc(R(),b);!this.t&&!this.H&&kd(this,a)};function ld(a){S().asyncAdSlotLoaded(a)}L("GA_googleAsyncAdSlotLoaded",ld);var kd=function(a,b){var c=Oc(a,b),d=gc(R(),c);if(a.f==h||a.f[c]==h){if(!(d.Q>30)){m.setTimeout(function(){kd(S(),b)},a.delay);d.Q++}}else Wc(a,b)};Z[v].F=function(){};
function $(a){V[F](this,a);this.m=(new Date)[J]();this.h="fallback"}qa($,V);$[v].j=function(){this.b=this.p;X(this,"correlator",this.m[s]());W(this,"output","html");W(this,"impl","fb")};$[v].i=function(){Zc(this)};$[v].w=function(a){var b;if(this.k){this.g(h);b=this.b+"&currentslot="+M(a)}else b=this.g(a);return b};$[v].n=function(a){var b=wb(R(),a);if(!(b==h)){R().c[q](a);if(!this.t){var c=this.w(a);Pc(this,a,c,h,b._width_,b._height_,f)}}};
function md(a){V[F](this,a);this.m=(new Date)[J]();this.J=f;this.h="iframe"}qa(md,V);md[v].j=function(){this.b=this.p;X(this,"correlator",this.m[s]());W(this,"output","html");W(this,"impl","ifr")};md[v].i=function(){Zc(this)};md[v].w=function(a){var b;if(this.k){this.g(h);b=this.b+"&currentslot="+M(a)}else b=this.g(a);return b};md[v].n=function(a){var b=wb(R(),a);if(!(b==h)){R().c[q](a);if(!this.t){var c=this.w(a);Pc(this,a,c,h,b._width_,b._height_,f)}}};
var nd=function(){if(Fa()){var a=Cc();return a<=5}else if(Da("firefox")){var b=k[A][D]("Firefox")+8,c=l(k[A][ga](b),10),d=k[A][w](b);return c<1}else if(Da("safari")){b=k[A][D]("Safari")+7;d=k[A][w](b);var e=l(d,10);return e<412}else if(m.opera!=h){b=k[A][D]("Opera")+6;d=k[A][w](b);c=l(d,10);return c<9}else if(!Fa()&&!Da("safari")&&Da("mozilla")){b=k[A][D]("Netscape")+9;d=k[A][w](b);c=l(d,10);return c<7}else return f},od=function(){if(Fa()){var a=Cc();return a>5}else if(Da("firefox")){var b=k[A][D]("Firefox")+
8,c=l(k[A][ga](b),10);k[A][w](b);return c>1}return j},pd=function(){if(nd())return"fallback";else if(m.google_delayFetch&&od())return"async";return"sync"},ob=function(a){var b=h;if(typeof a!="undefined"&&a!=h)b=a;else{b=m.GA_googleEnv[G]("google_ad_impl");if(b==h)b=pd()}switch(b){case "async":return new Z(j);case "sync":return new Y(j);case "sync_sra":return new Y(f);case "fallback":return new $(j);case "iframe":return new md(j);default:return new $(j)}},qd;
function R(){qd||(qd=new Db(Ha));return qd}function Cb(a){delete qd;qd=a}var rd;function S(){rd||(rd=h);return rd}function nb(a){delete rd;rd=a}if(typeof m.GA_googleEnv=="undefined")m.GA_googleEnv=new Ib;if(typeof m.GA_googleAdCapture=="undefined")m.GA_googleAdCapture=new Lb;if(m._GA_googleCookieHelper==h)m._GA_googleCookieHelper=new Va;P.tick("js_parse","js_load");P.tick("jl");
})()
