
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Jul 03 17:33:53 GMT+08:00 2009
//----------------------------------------------------

package rubyToSwf.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int kUNDEF = 75;
  public static final int tLEFT_SHIFT = 20;
  public static final int tLEQ = 26;
  public static final int tHASH_ARROW = 47;
  public static final int tLESS = 24;
  public static final int tAMP = 45;
  public static final int tNLINE = 11;
  public static final int kNOT = 65;
  public static final int tLCURLYBRACE = 39;
  public static final int kDEF = 70;
  public static final int kCLASS = 72;
  public static final int kNIL = 61;
  public static final int tQMARK = 41;
  public static final int kSUPER = 77;
  public static final int tCONSTANT = 10;
  public static final int kALIAS = 74;
  public static final int kTHEN = 56;
  public static final int tGEQ = 27;
  public static final int kWHILE = 62;
  public static final int kDO = 52;
  public static final int tDOUBLE_QUOTE_STR = 5;
  public static final int kWHEN = 80;
  public static final int tUMINUS = 17;
  public static final int tPOW = 19;
  public static final int kBREAK = 68;
  public static final int tCOMMA = 35;
  public static final int tEQQ = 23;
  public static final int kTRUE = 59;
  public static final int tNOT = 30;
  public static final int kDEFINED = 78;
  public static final int tVAR_INSTANCE = 8;
  public static final int kREDO = 76;
  public static final int kUNLESS = 66;
  public static final int kOR = 64;
  public static final int tOROP = 32;
  public static final int tINTEGER = 2;
  public static final int tBIT_XOR = 46;
  public static final int kELSE = 57;
  public static final int kIF = 55;
  public static final int kMODULE = 81;
  public static final int tFLOAT = 3;
  public static final int kLOAD = 82;
  public static final int tCOMPARE = 29;
  public static final int tRCURLYBRACE = 40;
  public static final int tRPAREN = 34;
  public static final int kRETURN = 73;
  public static final int tCOLON2 = 49;
  public static final int tANDOP = 31;
  public static final int tDOT3 = 51;
  public static final int tDOT2 = 50;
  public static final int tSEMI_COLON = 44;
  public static final int tUPLUS = 18;
  public static final int tLSQUAREBRACE = 36;
  public static final int tRIGHT_SHIFT = 21;
  public static final int tPLUS = 12;
  public static final int kEND = 53;
  public static final int tDOT = 48;
  public static final int EOF = 0;
  public static final int tVAR_CLASS = 7;
  public static final int kAS = 54;
  public static final int tLPAREN = 33;
  public static final int kCASE = 79;
  public static final int tGREAT = 25;
  public static final int tMULTIPLY = 14;
  public static final int tEQ = 22;
  public static final int tMODULO = 16;
  public static final int kAND = 63;
  public static final int error = 1;
  public static final int tDIVIDE = 15;
  public static final int tASSIGN = 43;
  public static final int kRAISE = 83;
  public static final int tMINUS = 13;
  public static final int kUNTIL = 67;
  public static final int tVAR_GLOBAL = 9;
  public static final int kELSIF = 58;
  public static final int tVAR_LOCAL = 6;
  public static final int tCOLON = 42;
  public static final int tRSQUAREBRACE = 37;
  public static final int tNEQ = 28;
  public static final int kYIELD = 71;
  public static final int kFALSE = 60;
  public static final int tBAR = 38;
  public static final int kNEXT = 69;
  public static final int tSINGLE_QUOTE_STR = 4;
}

