######################################################################
# Automatically generated by qmake (2.01a) ? ?? 6 10:45:10 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
