######################################################################
# Automatically generated by qmake (2.01a) ? ?? 6 10:47:17 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += qttest.h
FORMS += qttest.ui
SOURCES += main.cpp qttest.cpp
