(function(){
var h=true,l=null,m=false,aa=(new Date).getTime(),ba=function(a){var b=(new Date).getTime()-aa,c="&dtd="+(b<1000?b:"M");return a+c};var n=this,ca=function(a,b,c){var d=a.split("."),e=c||n;!(d[0]in e)&&e.execScript&&e.execScript("var "+d[0]);for(var f;d.length&&(f=d.shift());)if(!d.length&&b!==undefined)e[f]=b;else e=e[f]?e[f]:(e[f]={})},o=function(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array||!(a instanceof Object)&&Object.prototype.toString.call(a)=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";
if(!(a instanceof Object)&&(Object.prototype.toString.call(a)=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call")))return"function"}else return"null";else if(b=="function"&&typeof a.call=="undefined")return"object";return b},p=function(a){return o(a)=="array"},da=function(a){var b=o(a);return b=="array"||b=="object"&&typeof a.length=="number"},q=function(a){return typeof a=="string"},ea=function(a){var b=o(a);return b=="object"||
b=="array"||b=="function"};Math.floor(Math.random()*2147483648).toString(36);
var fa=function(a){var b=o(a);if(b=="object"||b=="array"){if(a.clone)return a.clone.call(a);var c=b=="array"?[]:{};for(var d in a)c[d]=fa(a[d]);return c}return a},ga=function(a,b){var c=a.u;if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);c&&d.unshift.apply(d,c);c=d}b=a.w||b;a=a.v||a;var e,f=b||n;e=c?function(){var i=Array.prototype.slice.call(arguments);i.unshift.apply(i,c);return a.apply(f,i)}:function(){return a.apply(f,arguments)};e.u=c;e.w=b;e.v=a;return e},ha=Date.now||function(){return(new Date).getTime()},
r=function(a,b,c){ca(a,b,c)};function s(a,b){var c=parseFloat(a);return isNaN(c)||c>1||c<0?b:c}function ia(a,b){if(a=="true")return h;if(a=="false")return m;return b}function t(a,b){var c=/^([\w-]+\.)+[\w-]{2,}(\:[0-9]+)?$/;return c.test(a)?a:b};var ja="pagead2.googlesyndication.com",ka="googleads.g.doubleclick.net",la="pubads.g.doubleclick.net",ma="securepubads.g.doubleclick.net",oa="partner.googleadservices.com",u=t("pagead2.googlesyndication.com",ja),pa=t("googleads.g.doubleclick.net",ka),qa=t("pagead2.googlesyndication.com",ja);t("pubads.g.doubleclick.net",la);t("partner.googleadservices.com",oa);t("securepubads.g.doubleclick.net",ma);function v(a){return typeof encodeURIComponent=="function"?encodeURIComponent(a):escape(a)}function ra(a,b,c){var d=document.createElement("script");d.type="text/javascript";if(b)d.onload=b;if(c)d.id=c;d.src=a;var e=document.getElementsByTagName("head")[0];if(!e)return m;window.setTimeout(function(){e.appendChild(d)},0);return h}function sa(a,b){a.google_image_requests||(a.google_image_requests=[]);var c=new Image;c.src=b;a.google_image_requests.push(c)}
function ta(a){if(a in ua)return ua[a];return ua[a]=navigator.userAgent.toLowerCase().indexOf(a)!=-1}var ua={};
function va(){if(navigator.plugins&&navigator.mimeTypes.length){var a=navigator.plugins["Shockwave Flash"];if(a&&a.description)return a.description.replace(/([a-zA-Z]|\s)+/,"").replace(/(\s)+r/,".")}else if(navigator.userAgent&&navigator.userAgent.indexOf("Windows CE")>=0){for(var b=3,c=1;c;)try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+(b+1));b++}catch(d){c=l}return b.toString()}else if(ta("msie")&&!window.opera){c=l;try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7")}catch(e){b=
0;try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");b=6;c.AllowScriptAccess="always"}catch(f){if(b==6)return b.toString()}try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(i){}}if(c){b=c.GetVariable("$version").split(" ")[1];return b.replace(/,/g,".")}}return"0"}function wa(a){var b=a.google_ad_format;if(b)return b.indexOf("_0ads")>0;return a.google_ad_output!="html"&&a.google_num_radlinks>0}function w(a){return!!a&&a.indexOf("_sdo")!=-1}
function xa(a){return wa(a)||w(a.google_ad_format)}function A(a,b){var c=Math.random();if(c<b){var d=Math.floor(c/b*a.length);return a[d]}return""};var ya={google_ad_channel:"channel",google_ad_host:"host",google_ad_host_channel:"h_ch",google_ad_host_tier_id:"ht_id",google_ad_section:"region",google_ad_type:"ad_type",google_adtest:"adtest",google_allow_expandable_ads:"ea",google_alternate_ad_url:"alternate_ad_url",google_alternate_color:"alt_color",google_bid:"bid",google_city:"gcs",google_color_bg:"color_bg",google_color_border:"color_border",google_color_line:"color_line",google_color_link:"color_link",google_color_text:"color_text",google_color_url:"color_url",
google_contents:"contents",google_country:"gl",google_cust_age:"cust_age",google_cust_ch:"cust_ch",google_cust_gender:"cust_gender",google_cust_id:"cust_id",google_cust_interests:"cust_interests",google_cust_job:"cust_job",google_cust_l:"cust_l",google_cust_lh:"cust_lh",google_cust_u_url:"cust_u_url",google_disable_video_autoplay:"disable_video_autoplay",google_ed:"ed",google_encoding:"oe",google_feedback:"feedback_link",google_flash_version:"flash",google_font_face:"f",google_font_size:"fs",google_hints:"hints",
google_kw:"kw",google_kw_type:"kw_type",google_language:"hl",google_page_url:"url",google_referrer_url:"ref",google_region:"gr",google_reuse_colors:"reuse_colors",google_safe:"adsafe",google_tag_info:"gut",google_targeting:"targeting",google_ui_features:"ui",google_ui_version:"uiv",google_video_doc_id:"video_doc_id",google_video_product_type:"video_product_type"},za={google_ad_client:"client",google_ad_format:"format",google_ad_output:"output",google_ad_callback:"callback",google_ad_height:"h",google_ad_override:"google_ad_override",
google_ad_slot:"slotname",google_ad_width:"w",google_analytics_uacct:"ga_wpids",google_ctr_threshold:"ctr_t",google_image_size:"image_size",google_last_modified_time:"lmt",google_max_num_ads:"num_ads",google_max_radlink_len:"max_radlink_len",google_num_radlinks:"num_radlinks",google_num_radlinks_per_unit:"num_radlinks_per_unit",google_only_ads_with_video:"only_ads_with_video",google_page_location:"loc",google_rl_dest_url:"rl_dest_url",google_rl_filtering:"rl_filtering",google_rl_mode:"rl_mode",google_rt:"rt",
google_skip:"skip"},Ca={google_only_pyv_ads:"pyv",google_with_pyv_ads:"withpyv"};function Da(a,b){try{return a.top.document.URL==b.URL}catch(c){}return m}function Ea(a,b,c,d){var e=c||a.google_ad_width,f=d||a.google_ad_height;if(Da(a,b))return m;var i=b.documentElement;if(e&&f){var j=1,k=1;if(a.innerHeight){j=a.innerWidth;k=a.innerHeight}else if(i&&i.clientHeight){j=i.clientWidth;k=i.clientHeight}else if(b.body){j=b.body.clientWidth;k=b.body.clientHeight}if(k>2*f||j>2*e)return m}return h}function Fa(a,b){for(var c in b)a["google_"+c]=b[c]}
function Ga(a,b){if(!b)return a.URL;return a.referrer}function Ha(a,b){if(!b&&a.google_referrer_url==l)return"0";else if(b&&a.google_referrer_url==l)return"1";else if(!b&&a.google_referrer_url!=l)return"2";else if(b&&a.google_referrer_url!=l)return"3";return"4"}function Ia(a,b,c,d){a.page_url=Ga(c,d);a.page_location=l}function Ja(a,b,c,d){a.page_url=b.google_page_url;a.page_location=Ga(c,d)||"EMPTY"}
function Ka(a,b){var c={},d=Ea(a,b,a.google_ad_width,a.google_ad_height);c.iframing=Ha(a,d);a.google_page_url?Ja(c,a,b,d):Ia(c,a,b,d);c.last_modified_time=b.URL==c.page_url?Date.parse(b.lastModified)/1000:l;c.referrer_url=d?a.google_referrer_url:a.google_page_url&&a.google_referrer_url?a.google_referrer_url:b.referrer;return c}function La(a){var b={},c=a.URL.substring(a.URL.lastIndexOf("http"));b.iframing=l;b.page_url=c;b.page_location=a.URL;b.last_modified_time=l;b.referrer_url=c;return b}
function Ma(a,b){var c=Na(a,b);Fa(a,c)}function Na(a,b){var c;return c=a.google_page_url==l&&Oa[b.domain]?La(b):Ka(a,b)}var Oa={};Oa["ad.yieldmanager.com"]=h;var B="",Ra=function(){if(window.google_ad_frameborder==l)window.google_ad_frameborder=0;if(window.google_ad_output==l)window.google_ad_output="html";if(w(window.google_ad_format)){var a=window.google_ad_format.match(/^(\d+)x(\d+)_.*/);if(a){window.google_ad_width=parseInt(a[1],10);window.google_ad_height=parseInt(a[2],10);window.google_ad_output="html"}}window.google_ad_format=Pa(window.google_ad_format,window.google_ad_output,window.google_ad_width,window.google_ad_height,window.google_ad_slot,
!!window.google_override_format);B=window.google_ad_client||"";window.google_ad_client=Qa(window.google_ad_format,window.google_ad_client);Ma(window,document);if(window.google_num_slots_by_channel==l)window.google_num_slots_by_channel={};if(window.google_viewed_host_channels==l)window.google_viewed_host_channels={};if(window.google_num_slots_by_client==l)window.google_num_slots_by_client={};if(window.google_prev_ad_formats_by_region==l)window.google_prev_ad_formats_by_region={};if(window.google_prev_ad_slotnames_by_region==
l)window.google_prev_ad_slotnames_by_region={};if(window.google_correlator==l)window.google_correlator=(new Date).getTime();if(window.google_adslot_loaded==l)window.google_adslot_loaded={};if(window.google_adContentsBySlot==l)window.google_adContentsBySlot={};if(window.google_flash_version==l)window.google_flash_version=va();if(window.google_new_domain_checked==l)window.google_new_domain_checked=0;if(window.google_new_domain_enabled==l)window.google_new_domain_enabled=0;window.google_ad_section=window.google_ad_section||
window.google_ad_region||"";window.google_country=window.google_country||window.google_gl||"";var b=(new Date).getTime();if(p(window.google_color_bg))window.google_color_bg=window.google_color_bg[b%window.google_color_bg.length];if(p(window.google_color_text))window.google_color_text=window.google_color_text[b%window.google_color_text.length];if(p(window.google_color_link))window.google_color_link=window.google_color_link[b%window.google_color_link.length];if(p(window.google_color_url))window.google_color_url=
window.google_color_url[b%window.google_color_url.length];if(p(window.google_color_border))window.google_color_border=window.google_color_border[b%window.google_color_border.length];if(p(window.google_color_line))window.google_color_line=window.google_color_line[b%window.google_color_line.length]},Sa=function(a){var b;for(b in ya)a[b]=l;for(b in za)a[b]=l;for(b in Ca)a[b]=l;a.google_container_id=l;a.google_eids=l;a.google_ad_region=l;a.google_gl=l},Qa=function(a,b){if(!b)return"";b=b.toLowerCase();
return b=w(a)?Ta(b):Ua(b)},Ua=function(a){if(a&&a.substring(0,3)!="ca-")a="ca-"+a;return a},Ta=function(a){if(a&&a.substring(0,9)!="dist-aff-")a="dist-aff-"+a;return a},Pa=function(a,b,c,d,e,f){if(!a&&b=="html")a=c+"x"+d;return a=Va(a,e,f)?a.toLowerCase():""},Va=function(a,b,c){if(!a)return m;if(!b)return h;return c};var C=document,D=navigator,F=window;
function Wa(){var a=C.cookie,b=Math.round((new Date).getTime()/1000),c=F.google_analytics_domain_name,d=typeof c=="undefined"?Xa("auto"):Xa(c),e=a.indexOf("__utma="+d+".")>-1,f=a.indexOf("__utmb="+d)>-1,i=a.indexOf("__utmc="+d)>-1,j,k={},g=!!F&&!!F.gaGlobal;if(e){j=a.split("__utma="+d+".")[1].split(";")[0].split(".");k.sid=f&&i?j[3]+"":g&&F.gaGlobal.sid?F.gaGlobal.sid:b+"";k.vid=j[0]+"."+j[1];k.from_cookie=h}else{k.sid=g&&F.gaGlobal.sid?F.gaGlobal.sid:b+"";k.vid=g&&F.gaGlobal.vid?F.gaGlobal.vid:(Math.round(Math.random()*
2147483647)^Ya()&2147483647)+"."+b;k.from_cookie=m}k.dh=d;k.hid=g&&F.gaGlobal.hid?F.gaGlobal.hid:Math.round(Math.random()*2147483647);return F.gaGlobal=k}
function Ya(){var a=C.cookie?C.cookie:"",b=F.history.length,c,d,e=[D.appName,D.version,D.language?D.language:D.browserLanguage,D.platform,D.userAgent,D.javaEnabled()?1:0].join("");if(F.screen)e+=F.screen.width+"x"+F.screen.height+F.screen.colorDepth;else if(F.java){d=java.awt.Toolkit.getDefaultToolkit().getScreenSize();e+=d.screen.width+"x"+d.screen.height}e+=a;e+=C.referrer?C.referrer:"";for(c=e.length;b>0;)e+=b--^c++;return Za(e)}
function Za(a){var b=1,c=0,d,e;if(!(a==undefined||a=="")){b=0;for(d=a.length-1;d>=0;d--){e=a.charCodeAt(d);b=(b<<6&268435455)+e+(e<<14);c=b&266338304;b=c!=0?b^c>>21:b}}return b}function Xa(a){if(!a||a==""||a=="none")return 1;if("auto"==a){a=C.domain;if("www."==a.substring(0,4))a=a.substring(4,a.length)}return Za(a.toLowerCase())};var $a={google:1,googlegroups:1,gmail:1,googlemail:1,googleimages:1,googleprint:1};function ab(a){var b=a.google_page_location||a.google_page_url;if(!b)return m;b=b.toString();if(b.indexOf("http://")==0)b=b.substring(7,b.length);else if(b.indexOf("https://")==0)b=b.substring(8,b.length);var c=b.indexOf("/");if(c==-1)c=b.length;var d=b.substring(0,c),e=d.split("."),f=m;if(e.length>=3)f=e[e.length-3]in $a;if(e.length>=2)f=f||e[e.length-2]in $a;return f}
function bb(a,b,c){if(ab(a)){a.google_new_domain_checked=1;return m}if(a.google_new_domain_checked==0){var d=Math.random();if(d<=c){var e="http://"+pa+"/pagead/test_domain.js",f="script";b.write("<"+f+' src="'+e+'"></'+f+">");a.google_new_domain_checked=1;return h}}return m}function cb(a){if(!ab(a)&&a.google_new_domain_enabled==1)return"http://"+pa;return"http://"+qa};var db=document,eb=ia("false",m),fb=ia("false",m),gb=ia("false",m);ia("false",m);var G=window;document.URL&&(document.URL.indexOf("?google_debug")>0||document.URL.indexOf("&google_debug")>0);var hb=function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},nb=function(a,b){if(b)return a.replace(ib,"&amp;").replace(jb,"&lt;").replace(kb,"&gt;").replace(lb,"&quot;");else{if(!mb.test(a))return a;if(a.indexOf("&")!=-1)a=a.replace(ib,"&amp;");if(a.indexOf("<")!=-1)a=a.replace(jb,"&lt;");if(a.indexOf(">")!=-1)a=a.replace(kb,"&gt;");if(a.indexOf('"')!=-1)a=a.replace(lb,"&quot;");return a}},ib=/&/g,jb=/</g,kb=/>/g,lb=/\"/g,mb=/[&<>\"]/,qb=function(a){if(H(a,"&"))return"document"in n&&!H(a,"<")?
ob(a):pb(a);return a},ob=function(a){var b=n.document.createElement("a");b.innerHTML=a;b.normalize&&b.normalize();a=b.firstChild.nodeValue;b.innerHTML="";return a},pb=function(a){return a.replace(/&([^;]+);/g,function(b,c){switch(c){case "amp":return"&";case "lt":return"<";case "gt":return">";case "quot":return'"';default:if(c.charAt(0)=="#"){var d=Number("0"+c.substr(1));if(!isNaN(d))return String.fromCharCode(d)}return b}})},rb=function(a,b){for(var c=b.length,d=0;d<c;d++){var e=c==1?b:b.charAt(d);
if(a.charAt(0)==e&&a.charAt(a.length-1)==e)return a.substring(1,a.length-1)}return a},H=function(a,b){return a.indexOf(b)!=-1},wb=function(a,b){for(var c=0,d=hb(String(a)).split("."),e=hb(String(b)).split("."),f=Math.max(d.length,e.length),i=0;c==0&&i<f;i++){var j=d[i]||"",k=e[i]||"",g=new RegExp("(\\d*)(\\D*)","g"),y=new RegExp("(\\d*)(\\D*)","g");do{var E=g.exec(j)||["","",""],z=y.exec(k)||["","",""];if(E[0].length==0&&z[0].length==0)break;var W=E[1].length==0?0:parseInt(E[1],10),na=z[1].length==
0?0:parseInt(z[1],10);c=sb(W,na)||sb(E[2].length==0,z[2].length==0)||sb(E[2],z[2])}while(c==0)}return c},sb=function(a,b){if(a<b)return-1;else if(a>b)return 1;return 0};ha();var I=function(a){this.t=a;this.i=[];this.p=this.h=0;this.d=[];this.n=m};I.prototype.s=function(a,b){var c=this.t[b],d=this.i;this.t[b]=function(e){if(e&&e.length>0){var f=e.length>1?e[1].url:l;d.push([a,qb(e[0].url),f])}c(e)}};I.prototype.r=function(){this.h++};I.prototype.o=function(){if(!this.n){ra("http://"+u+"/pagead/osd.js");this.n=h}};I.prototype.j=function(a){if(this.h>0)for(var b=document.getElementsByTagName("iframe"),c=0;c<b.length;c++)b.item(c).name=="google_ads_frame"&&a(b.item(c),b.item(c).src)};
I.prototype.k=function(a){var b=this.i;if(b.length>0)for(var c=document.getElementsByTagName("a"),d=function(g,y){return g.innerHTML.indexOf(y)>0},e=0;e<c.length;e++)for(var f=0;f<b.length;f++)if(c.item(e).href==b[f][1]){var i=c.item(e).parentNode;if(b[f][2])for(var j=i,k=0;k<4;k++){if(d(j,b[f][2])){i=j;break}j=j.parentNode}a(i,b[f][0]);b.splice(f,1);break}};I.prototype.e=function(a){this.k(a);this.j(a)};I.prototype.a=function(a){this.p=a};I.prototype.g=function(){return this.p};
I.prototype.f=function(){return this.i.length+this.h};I.prototype.b=function(a){this.d=a};I.prototype.q=function(a,b){if(this.d.length>0){for(var c=0;c<this.d.length;c++)if(this.d[c]==a)if(a=="js")this.s(b,"google_ad_request_done");else a=="html"&&this.r();this.o()}};var xb=function(){window.__google_ad_urls||(window.__google_ad_urls=new I(window));return window.__google_ad_urls};r("Goog_AdSense_getAdAdapterInstance",xb);r("Goog_AdSense_OsdAdapter",I);
r("Goog_AdSense_OsdAdapter.prototype.numBlocks",I.prototype.f);r("Goog_AdSense_OsdAdapter.prototype.findBlocks",I.prototype.e);r("Goog_AdSense_OsdAdapter.prototype.getOsdMode",I.prototype.g);var yb=function(a,b,c){var d=ga(b,n,a),e=window.onerror;window.onerror=d;try{c()}catch(f){var i=f.toString(),j="";if(f.fileName)j=f.fileName;var k=-1;if(f.lineNumber)k=f.lineNumber;var g=d(i,j,k);if(!g)throw f;}window.onerror=e};r("google_protectAndRun",yb);
var Ab=function(a,b,c,d){if(Math.random()<0.01){var e=db,f=["http://",u,"/pagead/gen_204","?id=jserror","&cb=",eb?1:0,"&cd=",fb?1:0,"&context=",v(a),"&msg=",v(b),"&file=",v(c),"&line=",v(d.toString()),"&url=",v(e.URL.substring(0,512)),"&ref=",v(e.referrer.substring(0,512))];f.push(zb());sa(G,f.join(""))}return!gb};r("google_handleError",Ab);
var zb=function(){var a=["&client=",v(G.google_ad_client),"&format=",v(G.google_ad_format),"&slotname=",v(G.google_ad_slot),"&output=",v(G.google_ad_output),"&ad_type=",v(G.google_ad_type)];return a.join("")};var Bb=function(a,b,c){if(a.forEach)a.forEach(b,c);else if(Array.forEach)Array.forEach(a,b,c);else for(var d=a.length,e=q(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},Cb=function(a){if(p(a))return a.concat();else{for(var b=[],c=0,d=a.length;c<d;c++)b[c]=a[c];return b}};var J=function(a,b){this.x=a!==undefined?a:0;this.y=b!==undefined?b:0};J.prototype.clone=function(){return new J(this.x,this.y)};J.prototype.toString=function(){return"("+this.x+", "+this.y+")"};var K=function(a,b){this.width=a;this.height=b};K.prototype.clone=function(){return new K(this.width,this.height)};K.prototype.toString=function(){return"("+this.width+" x "+this.height+")"};K.prototype.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};K.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
K.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};K.prototype.scale=function(a){this.width*=a;this.height*=a;return this};var Db=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};var L,Eb,Fb,Gb,Hb,Ib,Jb,Kb,Lb,Mb,Nb=function(){return n.navigator?n.navigator.userAgent:l},Ob=function(){return n.navigator},Pb=function(){Ib=Hb=Gb=Fb=Eb=L=m;var a;if(a=Nb()){var b=Ob();L=a.indexOf("Opera")==0;Eb=!L&&a.indexOf("MSIE")!=-1;Gb=(Fb=!L&&a.indexOf("WebKit")!=-1)&&a.indexOf("Mobile")!=-1;Ib=(Hb=!L&&!Fb&&b.product=="Gecko")&&b.vendor=="Camino"}};Pb();
var M=L,N=Eb,Qb=Hb,O=Fb,Rb=Gb,Sb=function(){var a=Ob();return a&&a.platform||""},Tb=Sb(),Ub=function(){Jb=H(Tb,"Mac");Kb=H(Tb,"Win");Lb=H(Tb,"Linux");Mb=!!Ob()&&H(Ob().appVersion||"","X11")};Ub();
var Vb=Jb,Wb=Kb,Xb=Lb,Yb=function(){var a="",b;if(M&&n.opera){var c=n.opera.version;a=typeof c=="function"?c():c}else{if(Qb)b=/rv\:([^\);]+)(\)|;)/;else if(N)b=/MSIE\s+([^\);]+)(\)|;)/;else if(O)b=/WebKit\/(\S+)/;if(b){var d=b.exec(Nb());a=d?d[1]:""}}return a},Zb=Yb(),$b={},P=function(a){return $b[a]||($b[a]=wb(Zb,a)>=0)};var ac;var bc=function(a){return q(a)?document.getElementById(a):a},cc=bc,ec=function(a,b){Db(b,function(c,d){if(d=="style")a.style.cssText=c;else if(d=="class")a.className=c;else if(d=="for")a.htmlFor=c;else if(d in dc)a.setAttribute(dc[d],c);else a[d]=c})},dc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",rowspan:"rowSpan",valign:"vAlign",height:"height",width:"width",usemap:"useMap",frameborder:"frameBorder",type:"type"},fc=function(a){var b=a.document;if(O&&!P("500")&&!Rb){if(typeof a.innerHeight==
"undefined")a=window;var c=a.innerHeight,d=a.document.documentElement.scrollHeight;if(a==a.top)if(d<c)c-=15;return new K(a.innerWidth,c)}var e=b.compatMode=="CSS1Compat"&&(!M||M&&P("9.50"))?b.documentElement:b.body;return new K(e.clientWidth,e.clientHeight)},gc=function(a){var b=!O&&a.compatMode=="CSS1Compat"?a.documentElement:a.body;return new J(b.scrollLeft,b.scrollTop)},ic=function(){return hc(document,arguments)},hc=function(a,b){var c=b[0],d=b[1];if(N&&d&&(d.name||d.type)){var e=["<",c];d.name&&
e.push(' name="',nb(d.name),'"');if(d.type){e.push(' type="',nb(d.type),'"');d=fa(d);delete d.type}e.push(">");c=e.join("")}var f=a.createElement(c);if(d)if(q(d))f.className=d;else ec(f,d);if(b.length>2){function i(g){if(g)f.appendChild(q(g)?a.createTextNode(g):g)}for(var j=2;j<b.length;j++){var k=b[j];da(k)&&!(ea(k)&&k.nodeType>0)?Bb(jc(k)?Cb(k):k,i):i(k)}}return f},kc=function(a,b){a.appendChild(b)},lc=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):l},mc=function(a,b){var c=b.parentNode;
c&&c.replaceChild(a,b)},nc=O&&P("522"),oc=function(a,b){if(typeof a.contains!="undefined"&&!nc&&b.nodeType==1)return a==b||a.contains(b);if(typeof a.compareDocumentPosition!="undefined")return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a},Q=function(a){return a.nodeType==9?a:a.ownerDocument||a.document},jc=function(a){if(a&&typeof a.length=="number")if(ea(a))return typeof a.item=="function"||typeof a.item=="string";else if(o(a)=="function")return typeof a.item==
"function";return m},R=function(a){this.c=a||n.document||document};R.prototype.createElement=function(a){return this.c.createElement(a)};R.prototype.createTextNode=function(a){return this.c.createTextNode(a)};R.prototype.m=function(){return this.c.compatMode=="CSS1Compat"};R.prototype.l=function(){return gc(this.c)};R.prototype.appendChild=kc;R.prototype.removeNode=lc;R.prototype.replaceNode=mc;R.prototype.contains=oc;var pc,qc,rc,sc,tc,uc,vc=function(){uc=tc=sc=rc=qc=pc=m;var a=Nb();if(a)if(a.indexOf("Firefox")!=-1)pc=h;else if(a.indexOf("Camino")!=-1)qc=h;else if(a.indexOf("iPhone")!=-1||a.indexOf("iPod")!=-1)rc=h;else if(a.indexOf("Android")!=-1)sc=h;else if(a.indexOf("Chrome")!=-1)tc=h;else if(a.indexOf("Safari")!=-1)uc=h};vc();var wc=function(a,b){var c=Q(a);if(c.defaultView&&c.defaultView.getComputedStyle){var d=c.defaultView.getComputedStyle(a,"");if(d)return d[b]}return l},S=function(a,b){return wc(a,b)||(a.currentStyle?a.currentStyle[b]:l)||a.style[b]},xc=function(a){var b;b=a?a.nodeType==9?a:Q(a):document;if(N&&!(b?new R(Q(b)):ac||(ac=new R)).m())return b.body;return b.documentElement},yc=function(a){var b=a.getBoundingClientRect();if(N){var c=a.ownerDocument;b.left-=c.documentElement.clientLeft+c.body.clientLeft;
b.top-=c.documentElement.clientTop+c.body.clientTop}return b},zc=function(a){if(N)return a.offsetParent;for(var b=Q(a),c=S(a,"position"),d=c=="fixed"||c=="absolute",e=a.parentNode;e&&e!=b;e=e.parentNode){c=S(e,"position");d=d&&c=="static"&&e!=b.documentElement&&e!=b.body;if(!d&&(e.scrollWidth>e.clientWidth||e.scrollHeight>e.clientHeight||c=="fixed"||c=="absolute"))return e}return l},Ac=function(a){var b,c=Q(a),d=S(a,"position"),e=Qb&&c.getBoxObjectFor&&!a.getBoundingClientRect&&d=="absolute"&&(b=
c.getBoxObjectFor(a))&&(b.screenX<0||b.screenY<0),f=new J(0,0),i=xc(c);if(a==i)return f;if(a.getBoundingClientRect){b=yc(a);var j=(c?new R(Q(c)):ac||(ac=new R)).l();f.x=b.left+j.x;f.y=b.top+j.y}else if(c.getBoxObjectFor&&!e){b=c.getBoxObjectFor(a);var k=c.getBoxObjectFor(i);f.x=b.screenX-k.screenX;f.y=b.screenY-k.screenY}else{var g=a;do{f.x+=g.offsetLeft;f.y+=g.offsetTop;if(g!=a){f.x+=g.clientLeft||0;f.y+=g.clientTop||0}if(O&&S(g,"position")=="fixed"){f.x+=c.body.scrollLeft;f.y+=c.body.scrollTop;
break}g=g.offsetParent}while(g&&g!=a);if(M||O&&d=="absolute")f.y-=c.body.offsetTop;for(g=a;(g=zc(g))&&g!=c.body&&g!=i;){f.x-=g.scrollLeft;if(!M||g.tagName!="TR")f.y-=g.scrollTop}}return f};Qb&&P("1.9");
var Bc=function(a,b,c,d){if(/^\d+px?$/.test(b))return parseInt(b,10);else{var e=a.style[c],f=a.runtimeStyle[c];a.runtimeStyle[c]=a.currentStyle[c];a.style[c]=b;var i=a.style[d];a.style[c]=e;a.runtimeStyle[c]=f;return i}},Cc=function(a){var b=Q(a),c="";if(b.createTextRange){var d=b.body.createTextRange();d.moveToElementText(a);c=d.queryCommandValue("FontName")}if(!c){c=S(a,"fontFamily");if(M&&Xb)c=c.replace(/ \[[^\]]*\]/,"")}var e=c.split(",");if(e.length>1)c=e[0];return rb(c,"\"'")},Dc=function(a){var b=
a.match(/[^\d]+$/);return b&&b[0]||l},Ec={cm:1,"in":1,mm:1,pc:1,pt:1},Fc={em:1,ex:1},Gc=function(a){var b=S(a,"fontSize"),c=Dc(b);if(b&&"px"==c)return parseInt(b,10);if(N)if(c in Ec)return Bc(a,b,"left","pixelLeft");else if(a.parentNode&&a.parentNode.nodeType==1&&c in Fc){var d=a.parentNode,e=S(d,"fontSize");return Bc(d,b==e?"1em":b,"left","pixelLeft")}var f=ic("span",{style:"visibility:hidden;position:absolute;line-height:0;padding:0;margin:0;border:0;height:1em;"});kc(a,f);b=f.offsetHeight;lc(f);
return b};var T={};function Hc(a){if(a==1)return h;return!T[a]}function U(a,b){if(a)if(b==1)if(T[b])T[b]+=","+a;else T[b]=a;else T[b]=a}function Ic(){var a=[];for(var b in T)a.push(T[b]);return a.join(",")}function Jc(a,b){if(a&&a instanceof Array)for(var c=0;c<a.length;c++)a[c]&&typeof a[c]=="string"&&U(a[c],b)}var Kc=m;
function Lc(a,b){var c="script";(Kc=Mc(a,b))||(a.google_allow_expandable_ads=m);var d=!Nc();Kc&&d&&b.write("<"+c+' src="http://'+u+'/pagead/expansion_embed.js"></'+c+">");var e=bb(a,b,s("1",0.01)),f=d||e;f&&ta("msie")&&!window.opera?b.write("<"+c+' src="http://'+u+'/pagead/render_ads.js"></'+c+">"):b.write("<"+c+'>google_protectAndRun("ads_core.google_render_ad", google_handleError, google_render_ad);</'+c+">")}function V(a){return a!=l?'"'+a+'"':'""'}
var Oc=function(a,b,c){var d=c.slice(-1)=="?"?"":"&";return[c,d,a,"=",b.toString()].join("")};function X(a,b){if(a&&b)window.google_ad_url=Oc(a,b,window.google_ad_url)}function Y(a){var b=window,c=ya[a]||za[a]||Ca[a]||l,d=b[a];X(c,d)}function Z(a,b){b!=l&&X(a,v(b))}function $(a){var b=window,c=ya[a]||za[a]||Ca[a]||l,d=b[a];Z(c,d)}
function Pc(a){var b=a.screen,c=navigator.javaEnabled(),d=-(new Date).getTimezoneOffset();if(b){X("u_h",b.height);X("u_w",b.width);X("u_ah",b.availHeight);X("u_aw",b.availWidth);X("u_cd",b.colorDepth)}X("u_tz",d);X("u_his",history.length);X("u_java",c);navigator.plugins&&X("u_nplug",navigator.plugins.length);navigator.mimeTypes&&X("u_nmime",navigator.mimeTypes.length)}function Qc(a){var b="google_unique_id";if(a[b])++a[b];else a[b]=1;return a[b]}
function Rc(){var a=N&&P("6"),b=Qb&&P("1.8.1"),c=O&&P("525");if(Wb&&(a||b||c))return h;else if(Vb&&(c||b))return h;else if(Xb&&b)return h;return m}function Nc(){return(typeof ExpandableAdSlotFactory=="function"||typeof ExpandableAdSlotFactory=="object")&&typeof ExpandableAdSlotFactory.createIframe=="function"}function Mc(a,b){if(a.google_allow_expandable_ads===m||!b.body||a.google_ad_output!="html"||Ea(a,b)||!Sc(a)||isNaN(a.google_ad_height)||isNaN(a.google_ad_width)||!Rc())return m;return h}
function Sc(a){var b=a.google_ad_format;if(w(b))return m;if(wa(a)&&!(b=="468x15_0ads_al"))return m;return h}function Tc(){var a;if(G.google_ad_output=="html"&&!xa(G)&&Hc(0)){var b=["6083035","6083034"];a=A(b,s("0",0));U(a,0)}return a=="6083035"}function Uc(a,b){if((a.google_unique_id||0)==0&&a.google_ad_output=="html"&&document.body&&typeof b.body.getBoundingClientRect=="function")return A(["36812001","36812002"],s("0.01",0));return""}
function Vc(a){var b="";if((a.google_unique_id||0)==0&&(a.google_ad_output=="js"||a.google_ad_output=="html")){xa(a)||(b=A(["36813001","36813002","36813003","36813004"],s("0.012",0)));if(b=="")b=A(["36813005","36813006"],s("0.008",0))}return b}function Wc(a,b){switch(a){case "36813002":b.a(1);b.b(["js"]);break;case "36813003":b.a(1);b.b(["html"]);break;case "36813004":b.a(2);b.b(["html","js"]);break;case "36813006":b.a(0);b.b(["html","js"]);break}}
function Xc(a){if(a.body)try{return fc(window)}catch(b){return new K(-12245933,-12245933)}else return new K(-1,-1)}
function Yc(a,b,c,d){var e=Qc(a);c=Oc("ifi",e,c);c=c.substring(0,1992);c=c.replace(/%\w?$/,"");var f="script";if((a.google_ad_output=="js"||a.google_ad_output=="json_html")&&(a.google_ad_request_done||a.google_radlink_request_done))b.write("<"+f+' language="JavaScript1.1" src='+V(ba(c))+"></"+f+">");else if(a.google_ad_output=="html")if(Kc&&Nc()){var i=a.google_container_id||d||l;a["google_expandable_ad_slot"+e]=ExpandableAdSlotFactory.createIframe("google_ads_frame"+e,ba(c),a.google_ad_width,a.google_ad_height,
i)}else{var j='<iframe name="google_ads_frame" width='+V(a.google_ad_width)+" height="+V(a.google_ad_height)+" frameborder="+V(a.google_ad_frameborder)+" src="+V(ba(c))+' marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" scrolling="no"></iframe>';a.google_container_id?Zc(a.google_container_id,b,j):b.write(j)}}function $c(a){Sa(a)}
function ad(a,b){var c=aa,d=window.google_ad_format,e=cb(window);window.google_ad_url=w(d)?e+"/pagead/sdo?":Tc()?e+"/pagead/render_iframe_ads.html#":e+"/pagead/ads?";$("google_ad_client");Y("google_ad_host");Y("google_ad_host_tier_id");var f=window.google_num_slots_by_client,i=window.google_num_slots_by_channel,j=window.google_prev_ad_formats_by_region,k=window.google_prev_ad_slotnames_by_region,g=window.google_ad_section;if(w(d)){window.google_num_sdo_slots=window.google_num_sdo_slots?window.google_num_sdo_slots+
1:1;if(window.google_num_sdo_slots>4)return m}else if(wa(window)){window.google_num_0ad_slots=window.google_num_0ad_slots?window.google_num_0ad_slots+1:1;if(window.google_num_0ad_slots>3)return m}else if(window.google_cpa_choice==l){window.google_num_ad_slots=window.google_num_ad_slots?window.google_num_ad_slots+1:1;if(window.google_num_slots_to_rotate){j[g]=l;k[g]=l;if(window.google_num_slot_to_show==l)window.google_num_slot_to_show=c%window.google_num_slots_to_rotate+1;if(window.google_num_slot_to_show!=
window.google_num_ad_slots)return m}else if(window.google_num_ad_slots>6&&g=="")return m}X("dt",aa);Y("google_language");Y("google_country");Y("google_region");$("google_city");$("google_hints");Y("google_safe");Y("google_encoding");Y("google_last_modified_time");$("google_alternate_ad_url");Y("google_alternate_color");Y("google_skip");Y("google_targeting");if(f[B])f[B]+=1;else{f[B]=1;f.length+=1}if(j[g])if(!w(d)){Z("prev_fmts",j[g].toLowerCase());f.length>1&&X("slot",f[B])}k[g]&&Z("prev_slotnames",
k[g].toLowerCase());if(d)w(d)||(j[g]=j[g]?j[g]+","+d:d);else if(window.google_ad_slot)k[g]=k[g]?k[g]+","+window.google_ad_slot:window.google_ad_slot;Y("google_max_num_ads");$("google_ad_output");Y("google_adtest");Y("google_ad_callback");$("google_ad_format");Y("google_ad_slot");Z("correlator",window.google_correlator);window.google_new_domain_checked==1&&window.google_new_domain_enabled==0&&X("dblk",1);$("google_ad_channel");if(window.google_ad_channel){for(var y="",E=window.google_ad_channel.split(bd),
z=0;z<E.length;z++){var W=E[z];if(i[W])y+=W+"+";else i[W]=1}Z("pv_ch",y)}$("google_ad_host_channel");if(window.google_ad_host_channel){var na=cd(window.google_ad_host_channel,window.google_viewed_host_channels);Z("pv_h_ch",na)}$("google_page_url");$("google_color_bg");$("google_color_text");$("google_color_link");$("google_color_url");$("google_color_border");$("google_color_line");window.google_reuse_colors?X("reuse_colors",1):X("reuse_colors",0);Y("google_font_face");Y("google_font_size");Y("google_kw_type");
$("google_kw");$("google_contents");Y("google_num_radlinks");Y("google_max_radlink_len");Y("google_rl_filtering");Y("google_rl_mode");Y("google_rt");$("google_rl_dest_url");Y("google_num_radlinks_per_unit");Y("google_ad_type");Y("google_image_size");Y("google_ad_section");Jc(window.google_eids,1);var Aa;if(Hc(0)){Aa=A(["36814001","36814002"],s("0.005",0));U(Aa,0)}Z("eid",Ic());var tb=window.google_allow_expandable_ads;if(tb!=l)tb?X("ea","1"):X("ea","0");eb&&X("cb",1);fb&&X("cd",
1);Y("google_feedback");$("google_referrer_url");$("google_page_location");X("frm",window.google_iframing);Y("google_bid");Y("google_ctr_threshold");Y("google_cust_age");Y("google_cust_gender");Y("google_cust_interests");Y("google_cust_id");Y("google_cust_job");Y("google_cust_u_url");Y("google_cust_l");Y("google_cust_lh");Y("google_cust_ch");Y("google_ed");Y("google_video_doc_id");Y("google_video_product_type");$("google_ui_features");$("google_ui_version");$("google_tag_info");$("google_only_ads_with_video");
$("google_only_pyv_ads");$("google_with_pyv_ads");$("google_disable_video_autoplay");var ub=m;if(a){Z("dff",Cc(a));Z("dfs",Gc(a));var x;if(b)if(typeof a.getBoundingClientRect=="function"){var vb=a.getBoundingClientRect();x={x:vb.left,y:vb.top}}else{x={};x.x="-252738";x.y="-252738"}else try{x=Ac(a)}catch(td){x={};x.x="-252738";x.y="-252738"}if(x){ub=h;Z("adx",x.x);Z("ady",x.y)}}if(ub||Aa=="36814002"){var Ba=Xc(document);if(Ba){Z("biw",Ba.width);Z("bih",Ba.height)}}Wa();X("ga_vid",window.gaGlobal.vid);
X("ga_sid",window.gaGlobal.sid);X("ga_hid",window.gaGlobal.hid);X("ga_fc",window.gaGlobal.from_cookie);$("google_analytics_uacct");Y("google_ad_override");Y("google_flash_version");X("w",window.google_ad_width||-1);X("h",window.google_ad_height||-1);Pc(window);return h}
function cd(a,b){for(var c=a.split("|"),d=-1,e=[],f=0;f<c.length;f++){var i=c[f].split(bd);b[f]||(b[f]={});for(var j="",k=0;k<i.length;k++){var g=i[k];if(!(g==""))if(b[f][g])j+="+"+g;else b[f][g]=1}j=j.slice(1);e[f]=j;if(j!="")d=f}var y="";if(d>-1){for(f=0;f<d;f++)y+=e[f]+"|";y+=e[d]}return y}
function dd(){var a=xb(),b=window.google_enable_osd,c="";if(b===h){c="36813006";Wc(c,a)}else if(b!==m&&Hc(0)){c=A(["68120011","68120021","68120031","68120041"],s("0",0));if(c==""){c=Uc(window,document);if(c==""){c=Vc(window);c!=""&&Wc(c,a)}}}U(c,0);var d=m,e=m,f=m;switch(c){case "68120031":f=h;case "68120021":e=h;case "68120041":d=h;break;case "36812002":if(!window.google_atf_included){window.google_atf_included=h;ra("http://"+u+"/pagead/atf.js")}break}var i;if(d){var j=
"google_temp_span";i=window.google_container_id&&cc(window.google_container_id)||cc(j);if(!i&&!window.google_container_id){document.write("<span id="+j+"></span>");i=cc(j)}}var k=m;k=e?ad(i,f):ad();i&&i.id==j&&lc(i);if(k){a.q(window.google_ad_output,window.google_ad_url);Yc(window,document,window.google_ad_url);$c(window)}}function ed(a,b,c,d){var e=Ab(a,b,c,d);Lc(window,document);return e}function fd(){Ra()}
function gd(a){for(var b={},c=a.split("?"),d=c[c.length-1].split("&"),e=0;e<d.length;e++){var f=d[e].split("=");if(f[0])try{b[f[0].toLowerCase()]=f.length>1?window.decodeURIComponent?decodeURIComponent(f[1].replace(/\+/g," ")):unescape(f[1]):""}catch(i){}}return b}function hd(){var a=window,b=gd(document.URL);if(b.google_ad_override){a.google_ad_override=b.google_ad_override;a.google_adtest="on"}}
function Zc(a,b,c){if(a){var d=b.getElementById(a);if(d&&c&&c.length!=""){d.style.visibility="visible";d.innerHTML=c}}}var bd=/[+, ]/;window.google_render_ad=dd;var id=["30143070","30143071","30143075"],jd=typeof window.postMessage=="function"||typeof window.postMessage=="object"||typeof document.postMessage=="function",ld=function(a,b){typeof A1_googleCreateSlot=="function"?A1_googleCreateSlot(a.google_ad_client):kd(a,b)},nd=function(){if(!md())return m;return h},od=function(a){if(xa(a))return m;var b=a.google_ad_output;if(b&&b!="html")return m;var c=a.google_ad_client;if(typeof c!="string"||c.substring(0,4)!="pub-"&&c.substring(0,7)!="ca-pub-")return m;
return h},qd=function(a){if(typeof a.google_a1_eid=="string")return a.google_a1_eid;var b=s("0.001",0);a.google_a1_eid=pd(id,b);return a.google_a1_eid},kd=function(a,b){if(!a.google_included_a1_script){var c="script",d="/pagead/show_ads_sra3.js?v\x3d1";b.write("<"+c+' src="http://'+u+d+'"></'+c+">");a.google_included_a1_script=h}},md=function(){if(N&&P("8"))return m;return jd||!O},pd=function(a,b){var c=Math.random();if(c<b){var d=Math.floor(c/b*a.length);return a[d]}return""};function rd(){hd();yb("show_ads.google_init_globals",ed,fd);Lc(window,document)}function sd(){if(!nd(window)||!od(window))rd();else if(gb&&window.google_use_a1===h)ld(window,document);else{var a=qd(window);if(a){U(a,0);window.google_allow_expandable_ads=m}!a||a=="30143070"?rd():ld(window,document)}}yb("show_ads.main",Ab,sd);
})()
